[package]
name = "reliquary-proc-macro"
version = "0.1.1"
edition = "2024"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = "2.0"
tracing = "0.1"
