// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `APMHDGPDGNP.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:APMHDGPDGNP)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct APMHDGPDGNP {
    // message fields
    // @@protoc_insertion_point(field:APMHDGPDGNP.NLILNONCNFC)
    pub NLILNONCNFC: ::protobuf::MessageField<super::KGABJENCFDC::KGABJENCFDC>,
    // @@protoc_insertion_point(field:APMHDGPDGNP.LPHOAIJFPNP)
    pub LPHOAIJFPNP: ::protobuf::MessageField<super::PNKEBBADONJ::PNKEBBADONJ>,
    // message oneof groups
    pub BPIHFAJCLOC: ::std::option::Option<apmhdgpdgnp::BPIHFAJCLOC>,
    // special fields
    // @@protoc_insertion_point(special_field:APMHDGPDGNP.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a APMHDGPDGNP {
    fn default() -> &'a APMHDGPDGNP {
        <APMHDGPDGNP as ::protobuf::Message>::default_instance()
    }
}

impl APMHDGPDGNP {
    pub fn new() -> APMHDGPDGNP {
        ::std::default::Default::default()
    }

    // .BCIFMHFCDMG OPDJKKPPPOD = 1042;

    pub fn OPDJKKPPPOD(&self) -> &super::BCIFMHFCDMG::BCIFMHFCDMG {
        match self.BPIHFAJCLOC {
            ::std::option::Option::Some(apmhdgpdgnp::BPIHFAJCLOC::OPDJKKPPPOD(ref v)) => v,
            _ => <super::BCIFMHFCDMG::BCIFMHFCDMG as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_OPDJKKPPPOD(&mut self) {
        self.BPIHFAJCLOC = ::std::option::Option::None;
    }

    pub fn has_OPDJKKPPPOD(&self) -> bool {
        match self.BPIHFAJCLOC {
            ::std::option::Option::Some(apmhdgpdgnp::BPIHFAJCLOC::OPDJKKPPPOD(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_OPDJKKPPPOD(&mut self, v: super::BCIFMHFCDMG::BCIFMHFCDMG) {
        self.BPIHFAJCLOC = ::std::option::Option::Some(apmhdgpdgnp::BPIHFAJCLOC::OPDJKKPPPOD(v))
    }

    // Mutable pointer to the field.
    pub fn mut_OPDJKKPPPOD(&mut self) -> &mut super::BCIFMHFCDMG::BCIFMHFCDMG {
        if let ::std::option::Option::Some(apmhdgpdgnp::BPIHFAJCLOC::OPDJKKPPPOD(_)) = self.BPIHFAJCLOC {
        } else {
            self.BPIHFAJCLOC = ::std::option::Option::Some(apmhdgpdgnp::BPIHFAJCLOC::OPDJKKPPPOD(super::BCIFMHFCDMG::BCIFMHFCDMG::new()));
        }
        match self.BPIHFAJCLOC {
            ::std::option::Option::Some(apmhdgpdgnp::BPIHFAJCLOC::OPDJKKPPPOD(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_OPDJKKPPPOD(&mut self) -> super::BCIFMHFCDMG::BCIFMHFCDMG {
        if self.has_OPDJKKPPPOD() {
            match self.BPIHFAJCLOC.take() {
                ::std::option::Option::Some(apmhdgpdgnp::BPIHFAJCLOC::OPDJKKPPPOD(v)) => v,
                _ => panic!(),
            }
        } else {
            super::BCIFMHFCDMG::BCIFMHFCDMG::new()
        }
    }

    // .HPMJCOCCBJJ KFPBACEHAMH = 636;

    pub fn KFPBACEHAMH(&self) -> &super::HPMJCOCCBJJ::HPMJCOCCBJJ {
        match self.BPIHFAJCLOC {
            ::std::option::Option::Some(apmhdgpdgnp::BPIHFAJCLOC::KFPBACEHAMH(ref v)) => v,
            _ => <super::HPMJCOCCBJJ::HPMJCOCCBJJ as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_KFPBACEHAMH(&mut self) {
        self.BPIHFAJCLOC = ::std::option::Option::None;
    }

    pub fn has_KFPBACEHAMH(&self) -> bool {
        match self.BPIHFAJCLOC {
            ::std::option::Option::Some(apmhdgpdgnp::BPIHFAJCLOC::KFPBACEHAMH(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_KFPBACEHAMH(&mut self, v: super::HPMJCOCCBJJ::HPMJCOCCBJJ) {
        self.BPIHFAJCLOC = ::std::option::Option::Some(apmhdgpdgnp::BPIHFAJCLOC::KFPBACEHAMH(v))
    }

    // Mutable pointer to the field.
    pub fn mut_KFPBACEHAMH(&mut self) -> &mut super::HPMJCOCCBJJ::HPMJCOCCBJJ {
        if let ::std::option::Option::Some(apmhdgpdgnp::BPIHFAJCLOC::KFPBACEHAMH(_)) = self.BPIHFAJCLOC {
        } else {
            self.BPIHFAJCLOC = ::std::option::Option::Some(apmhdgpdgnp::BPIHFAJCLOC::KFPBACEHAMH(super::HPMJCOCCBJJ::HPMJCOCCBJJ::new()));
        }
        match self.BPIHFAJCLOC {
            ::std::option::Option::Some(apmhdgpdgnp::BPIHFAJCLOC::KFPBACEHAMH(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_KFPBACEHAMH(&mut self) -> super::HPMJCOCCBJJ::HPMJCOCCBJJ {
        if self.has_KFPBACEHAMH() {
            match self.BPIHFAJCLOC.take() {
                ::std::option::Option::Some(apmhdgpdgnp::BPIHFAJCLOC::KFPBACEHAMH(v)) => v,
                _ => panic!(),
            }
        } else {
            super::HPMJCOCCBJJ::HPMJCOCCBJJ::new()
        }
    }

    // .KHILIFOOIGH CIMGCEEGDCF = 1742;

    pub fn CIMGCEEGDCF(&self) -> &super::KHILIFOOIGH::KHILIFOOIGH {
        match self.BPIHFAJCLOC {
            ::std::option::Option::Some(apmhdgpdgnp::BPIHFAJCLOC::CIMGCEEGDCF(ref v)) => v,
            _ => <super::KHILIFOOIGH::KHILIFOOIGH as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_CIMGCEEGDCF(&mut self) {
        self.BPIHFAJCLOC = ::std::option::Option::None;
    }

    pub fn has_CIMGCEEGDCF(&self) -> bool {
        match self.BPIHFAJCLOC {
            ::std::option::Option::Some(apmhdgpdgnp::BPIHFAJCLOC::CIMGCEEGDCF(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_CIMGCEEGDCF(&mut self, v: super::KHILIFOOIGH::KHILIFOOIGH) {
        self.BPIHFAJCLOC = ::std::option::Option::Some(apmhdgpdgnp::BPIHFAJCLOC::CIMGCEEGDCF(v))
    }

    // Mutable pointer to the field.
    pub fn mut_CIMGCEEGDCF(&mut self) -> &mut super::KHILIFOOIGH::KHILIFOOIGH {
        if let ::std::option::Option::Some(apmhdgpdgnp::BPIHFAJCLOC::CIMGCEEGDCF(_)) = self.BPIHFAJCLOC {
        } else {
            self.BPIHFAJCLOC = ::std::option::Option::Some(apmhdgpdgnp::BPIHFAJCLOC::CIMGCEEGDCF(super::KHILIFOOIGH::KHILIFOOIGH::new()));
        }
        match self.BPIHFAJCLOC {
            ::std::option::Option::Some(apmhdgpdgnp::BPIHFAJCLOC::CIMGCEEGDCF(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_CIMGCEEGDCF(&mut self) -> super::KHILIFOOIGH::KHILIFOOIGH {
        if self.has_CIMGCEEGDCF() {
            match self.BPIHFAJCLOC.take() {
                ::std::option::Option::Some(apmhdgpdgnp::BPIHFAJCLOC::CIMGCEEGDCF(v)) => v,
                _ => panic!(),
            }
        } else {
            super::KHILIFOOIGH::KHILIFOOIGH::new()
        }
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(1);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::KGABJENCFDC::KGABJENCFDC>(
            "NLILNONCNFC",
            |m: &APMHDGPDGNP| { &m.NLILNONCNFC },
            |m: &mut APMHDGPDGNP| { &mut m.NLILNONCNFC },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::PNKEBBADONJ::PNKEBBADONJ>(
            "LPHOAIJFPNP",
            |m: &APMHDGPDGNP| { &m.LPHOAIJFPNP },
            |m: &mut APMHDGPDGNP| { &mut m.LPHOAIJFPNP },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::BCIFMHFCDMG::BCIFMHFCDMG>(
            "OPDJKKPPPOD",
            APMHDGPDGNP::has_OPDJKKPPPOD,
            APMHDGPDGNP::OPDJKKPPPOD,
            APMHDGPDGNP::mut_OPDJKKPPPOD,
            APMHDGPDGNP::set_OPDJKKPPPOD,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::HPMJCOCCBJJ::HPMJCOCCBJJ>(
            "KFPBACEHAMH",
            APMHDGPDGNP::has_KFPBACEHAMH,
            APMHDGPDGNP::KFPBACEHAMH,
            APMHDGPDGNP::mut_KFPBACEHAMH,
            APMHDGPDGNP::set_KFPBACEHAMH,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::KHILIFOOIGH::KHILIFOOIGH>(
            "CIMGCEEGDCF",
            APMHDGPDGNP::has_CIMGCEEGDCF,
            APMHDGPDGNP::CIMGCEEGDCF,
            APMHDGPDGNP::mut_CIMGCEEGDCF,
            APMHDGPDGNP::set_CIMGCEEGDCF,
        ));
        oneofs.push(apmhdgpdgnp::BPIHFAJCLOC::generated_oneof_descriptor_data());
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<APMHDGPDGNP>(
            "APMHDGPDGNP",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for APMHDGPDGNP {
    const NAME: &'static str = "APMHDGPDGNP";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                82 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.NLILNONCNFC)?;
                },
                26 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.LPHOAIJFPNP)?;
                },
                8338 => {
                    self.BPIHFAJCLOC = ::std::option::Option::Some(apmhdgpdgnp::BPIHFAJCLOC::OPDJKKPPPOD(is.read_message()?));
                },
                5090 => {
                    self.BPIHFAJCLOC = ::std::option::Option::Some(apmhdgpdgnp::BPIHFAJCLOC::KFPBACEHAMH(is.read_message()?));
                },
                13938 => {
                    self.BPIHFAJCLOC = ::std::option::Option::Some(apmhdgpdgnp::BPIHFAJCLOC::CIMGCEEGDCF(is.read_message()?));
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.NLILNONCNFC.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.LPHOAIJFPNP.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let ::std::option::Option::Some(ref v) = self.BPIHFAJCLOC {
            match v {
                &apmhdgpdgnp::BPIHFAJCLOC::OPDJKKPPPOD(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &apmhdgpdgnp::BPIHFAJCLOC::KFPBACEHAMH(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &apmhdgpdgnp::BPIHFAJCLOC::CIMGCEEGDCF(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.NLILNONCNFC.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(10, v, os)?;
        }
        if let Some(v) = self.LPHOAIJFPNP.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        }
        if let ::std::option::Option::Some(ref v) = self.BPIHFAJCLOC {
            match v {
                &apmhdgpdgnp::BPIHFAJCLOC::OPDJKKPPPOD(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(1042, v, os)?;
                },
                &apmhdgpdgnp::BPIHFAJCLOC::KFPBACEHAMH(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(636, v, os)?;
                },
                &apmhdgpdgnp::BPIHFAJCLOC::CIMGCEEGDCF(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(1742, v, os)?;
                },
            };
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> APMHDGPDGNP {
        APMHDGPDGNP::new()
    }

    fn clear(&mut self) {
        self.NLILNONCNFC.clear();
        self.LPHOAIJFPNP.clear();
        self.BPIHFAJCLOC = ::std::option::Option::None;
        self.BPIHFAJCLOC = ::std::option::Option::None;
        self.BPIHFAJCLOC = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static APMHDGPDGNP {
        static instance: APMHDGPDGNP = APMHDGPDGNP {
            NLILNONCNFC: ::protobuf::MessageField::none(),
            LPHOAIJFPNP: ::protobuf::MessageField::none(),
            BPIHFAJCLOC: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for APMHDGPDGNP {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("APMHDGPDGNP").unwrap()).clone()
    }
}

impl ::std::fmt::Display for APMHDGPDGNP {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for APMHDGPDGNP {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `APMHDGPDGNP`
pub mod apmhdgpdgnp {

    #[derive(Clone,PartialEq,Debug)]
    #[non_exhaustive]
    // @@protoc_insertion_point(oneof:APMHDGPDGNP.BPIHFAJCLOC)
    pub enum BPIHFAJCLOC {
        // @@protoc_insertion_point(oneof_field:APMHDGPDGNP.OPDJKKPPPOD)
        OPDJKKPPPOD(super::super::BCIFMHFCDMG::BCIFMHFCDMG),
        // @@protoc_insertion_point(oneof_field:APMHDGPDGNP.KFPBACEHAMH)
        KFPBACEHAMH(super::super::HPMJCOCCBJJ::HPMJCOCCBJJ),
        // @@protoc_insertion_point(oneof_field:APMHDGPDGNP.CIMGCEEGDCF)
        CIMGCEEGDCF(super::super::KHILIFOOIGH::KHILIFOOIGH),
    }

    impl ::protobuf::Oneof for BPIHFAJCLOC {
    }

    impl ::protobuf::OneofFull for BPIHFAJCLOC {
        fn descriptor() -> ::protobuf::reflect::OneofDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::OneofDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| <super::APMHDGPDGNP as ::protobuf::MessageFull>::descriptor().oneof_by_name("BPIHFAJCLOC").unwrap()).clone()
        }
    }

    impl BPIHFAJCLOC {
        pub(in super) fn generated_oneof_descriptor_data() -> ::protobuf::reflect::GeneratedOneofDescriptorData {
            ::protobuf::reflect::GeneratedOneofDescriptorData::new::<BPIHFAJCLOC>("BPIHFAJCLOC")
        }
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11APMHDGPDGNP.proto\x1a\x11BCIFMHFCDMG.proto\x1a\x11HPMJCOCCBJJ.prot\
    o\x1a\x11KGABJENCFDC.proto\x1a\x11KHILIFOOIGH.proto\x1a\x11PNKEBBADONJ.p\
    roto\"\x95\x02\n\x0bAPMHDGPDGNP\x12.\n\x0bNLILNONCNFC\x18\n\x20\x01(\x0b\
    2\x0c.KGABJENCFDCR\x0bNLILNONCNFC\x12.\n\x0bLPHOAIJFPNP\x18\x03\x20\x01(\
    \x0b2\x0c.PNKEBBADONJR\x0bLPHOAIJFPNP\x121\n\x0bOPDJKKPPPOD\x18\x92\x08\
    \x20\x01(\x0b2\x0c.BCIFMHFCDMGH\0R\x0bOPDJKKPPPOD\x121\n\x0bKFPBACEHAMH\
    \x18\xfc\x04\x20\x01(\x0b2\x0c.HPMJCOCCBJJH\0R\x0bKFPBACEHAMH\x121\n\x0b\
    CIMGCEEGDCF\x18\xce\r\x20\x01(\x0b2\x0c.KHILIFOOIGHH\0R\x0bCIMGCEEGDCFB\
    \r\n\x0bBPIHFAJCLOCb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(5);
            deps.push(super::BCIFMHFCDMG::file_descriptor().clone());
            deps.push(super::HPMJCOCCBJJ::file_descriptor().clone());
            deps.push(super::KGABJENCFDC::file_descriptor().clone());
            deps.push(super::KHILIFOOIGH::file_descriptor().clone());
            deps.push(super::PNKEBBADONJ::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(APMHDGPDGNP::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
