// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `BKACBGFDDDA.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:BKACBGFDDDA)
pub enum BKACBGFDDDA {
    // @@protoc_insertion_point(enum_value:BKACBGFDDDA.BJLEJCIGLAO_PCPDHELPKEM)
    BJLEJCIGLAO_PCPDHELPKEM = 0,
    // @@protoc_insertion_point(enum_value:BKACBGFDDDA.BJLEJCIGLAO_AGJBLPLJGPD)
    BJLEJCIGLAO_AGJBLPLJGPD = 1,
    // @@protoc_insertion_point(enum_value:BKACBGFDDDA.BJLEJCIGLAO_ACBOMNNALDK)
    BJLEJCIGLAO_ACBOMNNALDK = 2,
}

impl ::protobuf::Enum for BKACBGFDDDA {
    const NAME: &'static str = "BKACBGFDDDA";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<BKACBGFDDDA> {
        match value {
            0 => ::std::option::Option::Some(BKACBGFDDDA::BJLEJCIGLAO_PCPDHELPKEM),
            1 => ::std::option::Option::Some(BKACBGFDDDA::BJLEJCIGLAO_AGJBLPLJGPD),
            2 => ::std::option::Option::Some(BKACBGFDDDA::BJLEJCIGLAO_ACBOMNNALDK),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<BKACBGFDDDA> {
        match str {
            "BJLEJCIGLAO_PCPDHELPKEM" => ::std::option::Option::Some(BKACBGFDDDA::BJLEJCIGLAO_PCPDHELPKEM),
            "BJLEJCIGLAO_AGJBLPLJGPD" => ::std::option::Option::Some(BKACBGFDDDA::BJLEJCIGLAO_AGJBLPLJGPD),
            "BJLEJCIGLAO_ACBOMNNALDK" => ::std::option::Option::Some(BKACBGFDDDA::BJLEJCIGLAO_ACBOMNNALDK),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [BKACBGFDDDA] = &[
        BKACBGFDDDA::BJLEJCIGLAO_PCPDHELPKEM,
        BKACBGFDDDA::BJLEJCIGLAO_AGJBLPLJGPD,
        BKACBGFDDDA::BJLEJCIGLAO_ACBOMNNALDK,
    ];
}

impl ::protobuf::EnumFull for BKACBGFDDDA {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("BKACBGFDDDA").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for BKACBGFDDDA {
    fn default() -> Self {
        BKACBGFDDDA::BJLEJCIGLAO_PCPDHELPKEM
    }
}

impl BKACBGFDDDA {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<BKACBGFDDDA>("BKACBGFDDDA")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11BKACBGFDDDA.proto*d\n\x0bBKACBGFDDDA\x12\x1b\n\x17BJLEJCIGLAO_PCPD\
    HELPKEM\x10\0\x12\x1b\n\x17BJLEJCIGLAO_AGJBLPLJGPD\x10\x01\x12\x1b\n\x17\
    BJLEJCIGLAO_ACBOMNNALDK\x10\x02b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(BKACBGFDDDA::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
