// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `BOOCAFOIFLF.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:BOOCAFOIFLF)
pub enum BOOCAFOIFLF {
    // @@protoc_insertion_point(enum_value:BOOCAFOIFLF.BOOCAFOIFLF_DAPCFOOOIGA)
    BOOCAFOIFLF_DAPCFOOOIGA = 0,
    // @@protoc_insertion_point(enum_value:BOOCAFOIFLF.BOOCAFOIFLF_OCHIFCBMILE)
    BOOCAFOIFLF_OCHIFCBMILE = 1,
    // @@protoc_insertion_point(enum_value:BOOCAFOIFLF.BOOCAFOIFLF_PEAGCBPJPMK)
    BOOCAFOIFLF_PEAGCBPJPMK = 32,
}

impl ::protobuf::Enum for BOOCAFOIFLF {
    const NAME: &'static str = "BOOCAFOIFLF";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<BOOCAFOIFLF> {
        match value {
            0 => ::std::option::Option::Some(BOOCAFOIFLF::BOOCAFOIFLF_DAPCFOOOIGA),
            1 => ::std::option::Option::Some(BOOCAFOIFLF::BOOCAFOIFLF_OCHIFCBMILE),
            32 => ::std::option::Option::Some(BOOCAFOIFLF::BOOCAFOIFLF_PEAGCBPJPMK),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<BOOCAFOIFLF> {
        match str {
            "BOOCAFOIFLF_DAPCFOOOIGA" => ::std::option::Option::Some(BOOCAFOIFLF::BOOCAFOIFLF_DAPCFOOOIGA),
            "BOOCAFOIFLF_OCHIFCBMILE" => ::std::option::Option::Some(BOOCAFOIFLF::BOOCAFOIFLF_OCHIFCBMILE),
            "BOOCAFOIFLF_PEAGCBPJPMK" => ::std::option::Option::Some(BOOCAFOIFLF::BOOCAFOIFLF_PEAGCBPJPMK),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [BOOCAFOIFLF] = &[
        BOOCAFOIFLF::BOOCAFOIFLF_DAPCFOOOIGA,
        BOOCAFOIFLF::BOOCAFOIFLF_OCHIFCBMILE,
        BOOCAFOIFLF::BOOCAFOIFLF_PEAGCBPJPMK,
    ];
}

impl ::protobuf::EnumFull for BOOCAFOIFLF {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("BOOCAFOIFLF").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = match self {
            BOOCAFOIFLF::BOOCAFOIFLF_DAPCFOOOIGA => 0,
            BOOCAFOIFLF::BOOCAFOIFLF_OCHIFCBMILE => 1,
            BOOCAFOIFLF::BOOCAFOIFLF_PEAGCBPJPMK => 2,
        };
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for BOOCAFOIFLF {
    fn default() -> Self {
        BOOCAFOIFLF::BOOCAFOIFLF_DAPCFOOOIGA
    }
}

impl BOOCAFOIFLF {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<BOOCAFOIFLF>("BOOCAFOIFLF")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11BOOCAFOIFLF.proto*d\n\x0bBOOCAFOIFLF\x12\x1b\n\x17BOOCAFOIFLF_DAPC\
    FOOOIGA\x10\0\x12\x1b\n\x17BOOCAFOIFLF_OCHIFCBMILE\x10\x01\x12\x1b\n\x17\
    BOOCAFOIFLF_PEAGCBPJPMK\x10\x20b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(BOOCAFOIFLF::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
