// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `CancelSyncExpiredItemCsReq.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:CancelSyncExpiredItemCsReq)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct CancelSyncExpiredItemCsReq {
    // message fields
    // @@protoc_insertion_point(field:CancelSyncExpiredItemCsReq.COOOFFKIDMC)
    pub COOOFFKIDMC: ::std::vec::Vec<u32>,
    // @@protoc_insertion_point(field:CancelSyncExpiredItemCsReq.type)
    pub type_: ::protobuf::EnumOrUnknown<super::JMGCDIANLGK::JMGCDIANLGK>,
    // @@protoc_insertion_point(field:CancelSyncExpiredItemCsReq.JLLKNNFAPEE)
    pub JLLKNNFAPEE: ::std::vec::Vec<::std::string::String>,
    // special fields
    // @@protoc_insertion_point(special_field:CancelSyncExpiredItemCsReq.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a CancelSyncExpiredItemCsReq {
    fn default() -> &'a CancelSyncExpiredItemCsReq {
        <CancelSyncExpiredItemCsReq as ::protobuf::Message>::default_instance()
    }
}

impl CancelSyncExpiredItemCsReq {
    pub fn new() -> CancelSyncExpiredItemCsReq {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "COOOFFKIDMC",
            |m: &CancelSyncExpiredItemCsReq| { &m.COOOFFKIDMC },
            |m: &mut CancelSyncExpiredItemCsReq| { &mut m.COOOFFKIDMC },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "type",
            |m: &CancelSyncExpiredItemCsReq| { &m.type_ },
            |m: &mut CancelSyncExpiredItemCsReq| { &mut m.type_ },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "JLLKNNFAPEE",
            |m: &CancelSyncExpiredItemCsReq| { &m.JLLKNNFAPEE },
            |m: &mut CancelSyncExpiredItemCsReq| { &mut m.JLLKNNFAPEE },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<CancelSyncExpiredItemCsReq>(
            "CancelSyncExpiredItemCsReq",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for CancelSyncExpiredItemCsReq {
    const NAME: &'static str = "CancelSyncExpiredItemCsReq";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                50 => {
                    is.read_repeated_packed_uint32_into(&mut self.COOOFFKIDMC)?;
                },
                48 => {
                    self.COOOFFKIDMC.push(is.read_uint32()?);
                },
                24 => {
                    self.type_ = is.read_enum_or_unknown()?;
                },
                114 => {
                    self.JLLKNNFAPEE.push(is.read_string()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::vec_packed_uint32_size(6, &self.COOOFFKIDMC);
        if self.type_ != ::protobuf::EnumOrUnknown::new(super::JMGCDIANLGK::JMGCDIANLGK::JMGCDIANLGK_PCPDHELPKEM) {
            my_size += ::protobuf::rt::int32_size(3, self.type_.value());
        }
        for value in &self.JLLKNNFAPEE {
            my_size += ::protobuf::rt::string_size(14, &value);
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        os.write_repeated_packed_uint32(6, &self.COOOFFKIDMC)?;
        if self.type_ != ::protobuf::EnumOrUnknown::new(super::JMGCDIANLGK::JMGCDIANLGK::JMGCDIANLGK_PCPDHELPKEM) {
            os.write_enum(3, ::protobuf::EnumOrUnknown::value(&self.type_))?;
        }
        for v in &self.JLLKNNFAPEE {
            os.write_string(14, &v)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> CancelSyncExpiredItemCsReq {
        CancelSyncExpiredItemCsReq::new()
    }

    fn clear(&mut self) {
        self.COOOFFKIDMC.clear();
        self.type_ = ::protobuf::EnumOrUnknown::new(super::JMGCDIANLGK::JMGCDIANLGK::JMGCDIANLGK_PCPDHELPKEM);
        self.JLLKNNFAPEE.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static CancelSyncExpiredItemCsReq {
        static instance: CancelSyncExpiredItemCsReq = CancelSyncExpiredItemCsReq {
            COOOFFKIDMC: ::std::vec::Vec::new(),
            type_: ::protobuf::EnumOrUnknown::from_i32(0),
            JLLKNNFAPEE: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for CancelSyncExpiredItemCsReq {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("CancelSyncExpiredItemCsReq").unwrap()).clone()
    }
}

impl ::std::fmt::Display for CancelSyncExpiredItemCsReq {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CancelSyncExpiredItemCsReq {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x20CancelSyncExpiredItemCsReq.proto\x1a\x11JMGCDIANLGK.proto\"\x82\
    \x01\n\x1aCancelSyncExpiredItemCsReq\x12\x20\n\x0bCOOOFFKIDMC\x18\x06\
    \x20\x03(\rR\x0bCOOOFFKIDMC\x12\x20\n\x04type\x18\x03\x20\x01(\x0e2\x0c.\
    JMGCDIANLGKR\x04type\x12\x20\n\x0bJLLKNNFAPEE\x18\x0e\x20\x03(\tR\x0bJLL\
    KNNFAPEEb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::JMGCDIANLGK::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(CancelSyncExpiredItemCsReq::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
