// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `CHDHAFCLEDB.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:CHDHAFCLEDB)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct CHDHAFCLEDB {
    // message fields
    // @@protoc_insertion_point(field:CHDHAFCLEDB.IEGFPJFFCAM)
    pub IEGFPJFFCAM: ::std::vec::Vec<super::JAFPMLLOGDI::JAFPMLLOGDI>,
    // @@protoc_insertion_point(field:CHDHAFCLEDB.MBCNAEAJMDM)
    pub MBCNAEAJMDM: u32,
    // special fields
    // @@protoc_insertion_point(special_field:CHDHAFCLEDB.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a CHDHAFCLEDB {
    fn default() -> &'a CHDHAFCLEDB {
        <CHDHAFCLEDB as ::protobuf::Message>::default_instance()
    }
}

impl CHDHAFCLEDB {
    pub fn new() -> CHDHAFCLEDB {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "IEGFPJFFCAM",
            |m: &CHDHAFCLEDB| { &m.IEGFPJFFCAM },
            |m: &mut CHDHAFCLEDB| { &mut m.IEGFPJFFCAM },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "MBCNAEAJMDM",
            |m: &CHDHAFCLEDB| { &m.MBCNAEAJMDM },
            |m: &mut CHDHAFCLEDB| { &mut m.MBCNAEAJMDM },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<CHDHAFCLEDB>(
            "CHDHAFCLEDB",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for CHDHAFCLEDB {
    const NAME: &'static str = "CHDHAFCLEDB";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.IEGFPJFFCAM.push(is.read_message()?);
                },
                112 => {
                    self.MBCNAEAJMDM = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.IEGFPJFFCAM {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if self.MBCNAEAJMDM != 0 {
            my_size += ::protobuf::rt::uint32_size(14, self.MBCNAEAJMDM);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.IEGFPJFFCAM {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        if self.MBCNAEAJMDM != 0 {
            os.write_uint32(14, self.MBCNAEAJMDM)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> CHDHAFCLEDB {
        CHDHAFCLEDB::new()
    }

    fn clear(&mut self) {
        self.IEGFPJFFCAM.clear();
        self.MBCNAEAJMDM = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static CHDHAFCLEDB {
        static instance: CHDHAFCLEDB = CHDHAFCLEDB {
            IEGFPJFFCAM: ::std::vec::Vec::new(),
            MBCNAEAJMDM: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for CHDHAFCLEDB {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("CHDHAFCLEDB").unwrap()).clone()
    }
}

impl ::std::fmt::Display for CHDHAFCLEDB {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CHDHAFCLEDB {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11CHDHAFCLEDB.proto\x1a\x11JAFPMLLOGDI.proto\"_\n\x0bCHDHAFCLEDB\x12\
    .\n\x0bIEGFPJFFCAM\x18\x01\x20\x03(\x0b2\x0c.JAFPMLLOGDIR\x0bIEGFPJFFCAM\
    \x12\x20\n\x0bMBCNAEAJMDM\x18\x0e\x20\x01(\rR\x0bMBCNAEAJMDMb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::JAFPMLLOGDI::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(CHDHAFCLEDB::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
