// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `CmdFiveDimType.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:CmdFiveDimType)
pub enum CmdFiveDimType {
    // @@protoc_insertion_point(enum_value:CmdFiveDimType.MKLPGBFEJMO_PCPDHELPKEM)
    MKLPGBFEJMO_PCPDHELPKEM = 0,
    // @@protoc_insertion_point(enum_value:CmdFiveDimType.CmdGetFiveDimMoneyScRsp)
    CmdGetFiveDimMoneyScRsp = 2261,
    // @@protoc_insertion_point(enum_value:CmdFiveDimType.CmdLeaveFiveDimGameScRsp)
    CmdLeaveFiveDimGameScRsp = 2258,
    // @@protoc_insertion_point(enum_value:CmdFiveDimType.MKLPGBFEJMO_DFILLFNLLAJ)
    MKLPGBFEJMO_DFILLFNLLAJ = 2253,
    // @@protoc_insertion_point(enum_value:CmdFiveDimType.CmdFiveDimJumpEnergyChangeScNotify)
    CmdFiveDimJumpEnergyChangeScNotify = 2265,
    // @@protoc_insertion_point(enum_value:CmdFiveDimType.CmdUpdateFiveDimGameDataScRsp)
    CmdUpdateFiveDimGameDataScRsp = 2259,
    // @@protoc_insertion_point(enum_value:CmdFiveDimType.MKLPGBFEJMO_LKLOBDJINOI)
    MKLPGBFEJMO_LKLOBDJINOI = 2257,
    // @@protoc_insertion_point(enum_value:CmdFiveDimType.CmdFiveDimGameTransferScRsp)
    CmdFiveDimGameTransferScRsp = 2270,
    // @@protoc_insertion_point(enum_value:CmdFiveDimType.MKLPGBFEJMO_CJMDBFOJPIC)
    MKLPGBFEJMO_CJMDBFOJPIC = 2251,
    // @@protoc_insertion_point(enum_value:CmdFiveDimType.MKLPGBFEJMO_HKGHBAHIOMC)
    MKLPGBFEJMO_HKGHBAHIOMC = 2252,
    // @@protoc_insertion_point(enum_value:CmdFiveDimType.MKLPGBFEJMO_FFBHNFPKLMD)
    MKLPGBFEJMO_FFBHNFPKLMD = 2269,
    // @@protoc_insertion_point(enum_value:CmdFiveDimType.CmdFiveDimMoneyChangeScNotify)
    CmdFiveDimMoneyChangeScNotify = 2272,
    // @@protoc_insertion_point(enum_value:CmdFiveDimType.CmdEnterFiveDimGameScRsp)
    CmdEnterFiveDimGameScRsp = 2264,
    // @@protoc_insertion_point(enum_value:CmdFiveDimType.MKLPGBFEJMO_OBOBBDGHCDN)
    MKLPGBFEJMO_OBOBBDGHCDN = 2268,
    // @@protoc_insertion_point(enum_value:CmdFiveDimType.CmdFiveDimGameDataUpdateScNotify)
    CmdFiveDimGameDataUpdateScNotify = 2275,
    // @@protoc_insertion_point(enum_value:CmdFiveDimType.CmdGetFiveDimGameDataScRsp)
    CmdGetFiveDimGameDataScRsp = 2254,
    // @@protoc_insertion_point(enum_value:CmdFiveDimType.MKLPGBFEJMO_IIDCMPNMCHM)
    MKLPGBFEJMO_IIDCMPNMCHM = 2260,
    // @@protoc_insertion_point(enum_value:CmdFiveDimType.CmdGetFiveDimMoneyDataScRsp)
    CmdGetFiveDimMoneyDataScRsp = 2274,
}

impl ::protobuf::Enum for CmdFiveDimType {
    const NAME: &'static str = "CmdFiveDimType";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<CmdFiveDimType> {
        match value {
            0 => ::std::option::Option::Some(CmdFiveDimType::MKLPGBFEJMO_PCPDHELPKEM),
            2261 => ::std::option::Option::Some(CmdFiveDimType::CmdGetFiveDimMoneyScRsp),
            2258 => ::std::option::Option::Some(CmdFiveDimType::CmdLeaveFiveDimGameScRsp),
            2253 => ::std::option::Option::Some(CmdFiveDimType::MKLPGBFEJMO_DFILLFNLLAJ),
            2265 => ::std::option::Option::Some(CmdFiveDimType::CmdFiveDimJumpEnergyChangeScNotify),
            2259 => ::std::option::Option::Some(CmdFiveDimType::CmdUpdateFiveDimGameDataScRsp),
            2257 => ::std::option::Option::Some(CmdFiveDimType::MKLPGBFEJMO_LKLOBDJINOI),
            2270 => ::std::option::Option::Some(CmdFiveDimType::CmdFiveDimGameTransferScRsp),
            2251 => ::std::option::Option::Some(CmdFiveDimType::MKLPGBFEJMO_CJMDBFOJPIC),
            2252 => ::std::option::Option::Some(CmdFiveDimType::MKLPGBFEJMO_HKGHBAHIOMC),
            2269 => ::std::option::Option::Some(CmdFiveDimType::MKLPGBFEJMO_FFBHNFPKLMD),
            2272 => ::std::option::Option::Some(CmdFiveDimType::CmdFiveDimMoneyChangeScNotify),
            2264 => ::std::option::Option::Some(CmdFiveDimType::CmdEnterFiveDimGameScRsp),
            2268 => ::std::option::Option::Some(CmdFiveDimType::MKLPGBFEJMO_OBOBBDGHCDN),
            2275 => ::std::option::Option::Some(CmdFiveDimType::CmdFiveDimGameDataUpdateScNotify),
            2254 => ::std::option::Option::Some(CmdFiveDimType::CmdGetFiveDimGameDataScRsp),
            2260 => ::std::option::Option::Some(CmdFiveDimType::MKLPGBFEJMO_IIDCMPNMCHM),
            2274 => ::std::option::Option::Some(CmdFiveDimType::CmdGetFiveDimMoneyDataScRsp),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<CmdFiveDimType> {
        match str {
            "MKLPGBFEJMO_PCPDHELPKEM" => ::std::option::Option::Some(CmdFiveDimType::MKLPGBFEJMO_PCPDHELPKEM),
            "CmdGetFiveDimMoneyScRsp" => ::std::option::Option::Some(CmdFiveDimType::CmdGetFiveDimMoneyScRsp),
            "CmdLeaveFiveDimGameScRsp" => ::std::option::Option::Some(CmdFiveDimType::CmdLeaveFiveDimGameScRsp),
            "MKLPGBFEJMO_DFILLFNLLAJ" => ::std::option::Option::Some(CmdFiveDimType::MKLPGBFEJMO_DFILLFNLLAJ),
            "CmdFiveDimJumpEnergyChangeScNotify" => ::std::option::Option::Some(CmdFiveDimType::CmdFiveDimJumpEnergyChangeScNotify),
            "CmdUpdateFiveDimGameDataScRsp" => ::std::option::Option::Some(CmdFiveDimType::CmdUpdateFiveDimGameDataScRsp),
            "MKLPGBFEJMO_LKLOBDJINOI" => ::std::option::Option::Some(CmdFiveDimType::MKLPGBFEJMO_LKLOBDJINOI),
            "CmdFiveDimGameTransferScRsp" => ::std::option::Option::Some(CmdFiveDimType::CmdFiveDimGameTransferScRsp),
            "MKLPGBFEJMO_CJMDBFOJPIC" => ::std::option::Option::Some(CmdFiveDimType::MKLPGBFEJMO_CJMDBFOJPIC),
            "MKLPGBFEJMO_HKGHBAHIOMC" => ::std::option::Option::Some(CmdFiveDimType::MKLPGBFEJMO_HKGHBAHIOMC),
            "MKLPGBFEJMO_FFBHNFPKLMD" => ::std::option::Option::Some(CmdFiveDimType::MKLPGBFEJMO_FFBHNFPKLMD),
            "CmdFiveDimMoneyChangeScNotify" => ::std::option::Option::Some(CmdFiveDimType::CmdFiveDimMoneyChangeScNotify),
            "CmdEnterFiveDimGameScRsp" => ::std::option::Option::Some(CmdFiveDimType::CmdEnterFiveDimGameScRsp),
            "MKLPGBFEJMO_OBOBBDGHCDN" => ::std::option::Option::Some(CmdFiveDimType::MKLPGBFEJMO_OBOBBDGHCDN),
            "CmdFiveDimGameDataUpdateScNotify" => ::std::option::Option::Some(CmdFiveDimType::CmdFiveDimGameDataUpdateScNotify),
            "CmdGetFiveDimGameDataScRsp" => ::std::option::Option::Some(CmdFiveDimType::CmdGetFiveDimGameDataScRsp),
            "MKLPGBFEJMO_IIDCMPNMCHM" => ::std::option::Option::Some(CmdFiveDimType::MKLPGBFEJMO_IIDCMPNMCHM),
            "CmdGetFiveDimMoneyDataScRsp" => ::std::option::Option::Some(CmdFiveDimType::CmdGetFiveDimMoneyDataScRsp),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [CmdFiveDimType] = &[
        CmdFiveDimType::MKLPGBFEJMO_PCPDHELPKEM,
        CmdFiveDimType::CmdGetFiveDimMoneyScRsp,
        CmdFiveDimType::CmdLeaveFiveDimGameScRsp,
        CmdFiveDimType::MKLPGBFEJMO_DFILLFNLLAJ,
        CmdFiveDimType::CmdFiveDimJumpEnergyChangeScNotify,
        CmdFiveDimType::CmdUpdateFiveDimGameDataScRsp,
        CmdFiveDimType::MKLPGBFEJMO_LKLOBDJINOI,
        CmdFiveDimType::CmdFiveDimGameTransferScRsp,
        CmdFiveDimType::MKLPGBFEJMO_CJMDBFOJPIC,
        CmdFiveDimType::MKLPGBFEJMO_HKGHBAHIOMC,
        CmdFiveDimType::MKLPGBFEJMO_FFBHNFPKLMD,
        CmdFiveDimType::CmdFiveDimMoneyChangeScNotify,
        CmdFiveDimType::CmdEnterFiveDimGameScRsp,
        CmdFiveDimType::MKLPGBFEJMO_OBOBBDGHCDN,
        CmdFiveDimType::CmdFiveDimGameDataUpdateScNotify,
        CmdFiveDimType::CmdGetFiveDimGameDataScRsp,
        CmdFiveDimType::MKLPGBFEJMO_IIDCMPNMCHM,
        CmdFiveDimType::CmdGetFiveDimMoneyDataScRsp,
    ];
}

impl ::protobuf::EnumFull for CmdFiveDimType {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("CmdFiveDimType").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = match self {
            CmdFiveDimType::MKLPGBFEJMO_PCPDHELPKEM => 0,
            CmdFiveDimType::CmdGetFiveDimMoneyScRsp => 1,
            CmdFiveDimType::CmdLeaveFiveDimGameScRsp => 2,
            CmdFiveDimType::MKLPGBFEJMO_DFILLFNLLAJ => 3,
            CmdFiveDimType::CmdFiveDimJumpEnergyChangeScNotify => 4,
            CmdFiveDimType::CmdUpdateFiveDimGameDataScRsp => 5,
            CmdFiveDimType::MKLPGBFEJMO_LKLOBDJINOI => 6,
            CmdFiveDimType::CmdFiveDimGameTransferScRsp => 7,
            CmdFiveDimType::MKLPGBFEJMO_CJMDBFOJPIC => 8,
            CmdFiveDimType::MKLPGBFEJMO_HKGHBAHIOMC => 9,
            CmdFiveDimType::MKLPGBFEJMO_FFBHNFPKLMD => 10,
            CmdFiveDimType::CmdFiveDimMoneyChangeScNotify => 11,
            CmdFiveDimType::CmdEnterFiveDimGameScRsp => 12,
            CmdFiveDimType::MKLPGBFEJMO_OBOBBDGHCDN => 13,
            CmdFiveDimType::CmdFiveDimGameDataUpdateScNotify => 14,
            CmdFiveDimType::CmdGetFiveDimGameDataScRsp => 15,
            CmdFiveDimType::MKLPGBFEJMO_IIDCMPNMCHM => 16,
            CmdFiveDimType::CmdGetFiveDimMoneyDataScRsp => 17,
        };
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for CmdFiveDimType {
    fn default() -> Self {
        CmdFiveDimType::MKLPGBFEJMO_PCPDHELPKEM
    }
}

impl CmdFiveDimType {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<CmdFiveDimType>("CmdFiveDimType")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x14CmdFiveDimType.proto*\xd8\x04\n\x0eCmdFiveDimType\x12\x1b\n\x17MKL\
    PGBFEJMO_PCPDHELPKEM\x10\0\x12\x1c\n\x17CmdGetFiveDimMoneyScRsp\x10\xd5\
    \x11\x12\x1d\n\x18CmdLeaveFiveDimGameScRsp\x10\xd2\x11\x12\x1c\n\x17MKLP\
    GBFEJMO_DFILLFNLLAJ\x10\xcd\x11\x12'\n\"CmdFiveDimJumpEnergyChangeScNoti\
    fy\x10\xd9\x11\x12\"\n\x1dCmdUpdateFiveDimGameDataScRsp\x10\xd3\x11\x12\
    \x1c\n\x17MKLPGBFEJMO_LKLOBDJINOI\x10\xd1\x11\x12\x20\n\x1bCmdFiveDimGam\
    eTransferScRsp\x10\xde\x11\x12\x1c\n\x17MKLPGBFEJMO_CJMDBFOJPIC\x10\xcb\
    \x11\x12\x1c\n\x17MKLPGBFEJMO_HKGHBAHIOMC\x10\xcc\x11\x12\x1c\n\x17MKLPG\
    BFEJMO_FFBHNFPKLMD\x10\xdd\x11\x12\"\n\x1dCmdFiveDimMoneyChangeScNotify\
    \x10\xe0\x11\x12\x1d\n\x18CmdEnterFiveDimGameScRsp\x10\xd8\x11\x12\x1c\n\
    \x17MKLPGBFEJMO_OBOBBDGHCDN\x10\xdc\x11\x12%\n\x20CmdFiveDimGameDataUpda\
    teScNotify\x10\xe3\x11\x12\x1f\n\x1aCmdGetFiveDimGameDataScRsp\x10\xce\
    \x11\x12\x1c\n\x17MKLPGBFEJMO_IIDCMPNMCHM\x10\xd4\x11\x12\x20\n\x1bCmdGe\
    tFiveDimMoneyDataScRsp\x10\xe2\x11b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(CmdFiveDimType::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
