// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `CmdHeartdialType.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:CmdHeartdialType)
pub enum CmdHeartdialType {
    // @@protoc_insertion_point(enum_value:CmdHeartdialType.NIOFDIFADEK_PCPDHELPKEM)
    NIOFDIFADEK_PCPDHELPKEM = 0,
    // @@protoc_insertion_point(enum_value:CmdHeartdialType.CmdSubmitEmotionItemCsReq)
    CmdSubmitEmotionItemCsReq = 6314,
    // @@protoc_insertion_point(enum_value:CmdHeartdialType.CmdHeartDialTraceScriptCsReq)
    CmdHeartDialTraceScriptCsReq = 6326,
    // @@protoc_insertion_point(enum_value:CmdHeartdialType.CmdSubmitEmotionItemScRsp)
    CmdSubmitEmotionItemScRsp = 6318,
    // @@protoc_insertion_point(enum_value:CmdHeartdialType.CmdHeartDialScriptChangeScNotify)
    CmdHeartDialScriptChangeScNotify = 6363,
    // @@protoc_insertion_point(enum_value:CmdHeartdialType.CmdGetHeartDialInfoCsReq)
    CmdGetHeartDialInfoCsReq = 6391,
    // @@protoc_insertion_point(enum_value:CmdHeartdialType.CmdHeartDialTraceScriptScRsp)
    CmdHeartDialTraceScriptScRsp = 6339,
    // @@protoc_insertion_point(enum_value:CmdHeartdialType.CmdChangeScriptEmotionCsReq)
    CmdChangeScriptEmotionCsReq = 6394,
    // @@protoc_insertion_point(enum_value:CmdHeartdialType.CmdFinishEmotionDialoguePerformanceScRsp)
    CmdFinishEmotionDialoguePerformanceScRsp = 6398,
    // @@protoc_insertion_point(enum_value:CmdHeartdialType.CmdChangeScriptEmotionScRsp)
    CmdChangeScriptEmotionScRsp = 6395,
    // @@protoc_insertion_point(enum_value:CmdHeartdialType.CmdFinishEmotionDialoguePerformanceCsReq)
    CmdFinishEmotionDialoguePerformanceCsReq = 6309,
    // @@protoc_insertion_point(enum_value:CmdHeartdialType.CmdGetHeartDialInfoScRsp)
    CmdGetHeartDialInfoScRsp = 6310,
}

impl ::protobuf::Enum for CmdHeartdialType {
    const NAME: &'static str = "CmdHeartdialType";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<CmdHeartdialType> {
        match value {
            0 => ::std::option::Option::Some(CmdHeartdialType::NIOFDIFADEK_PCPDHELPKEM),
            6314 => ::std::option::Option::Some(CmdHeartdialType::CmdSubmitEmotionItemCsReq),
            6326 => ::std::option::Option::Some(CmdHeartdialType::CmdHeartDialTraceScriptCsReq),
            6318 => ::std::option::Option::Some(CmdHeartdialType::CmdSubmitEmotionItemScRsp),
            6363 => ::std::option::Option::Some(CmdHeartdialType::CmdHeartDialScriptChangeScNotify),
            6391 => ::std::option::Option::Some(CmdHeartdialType::CmdGetHeartDialInfoCsReq),
            6339 => ::std::option::Option::Some(CmdHeartdialType::CmdHeartDialTraceScriptScRsp),
            6394 => ::std::option::Option::Some(CmdHeartdialType::CmdChangeScriptEmotionCsReq),
            6398 => ::std::option::Option::Some(CmdHeartdialType::CmdFinishEmotionDialoguePerformanceScRsp),
            6395 => ::std::option::Option::Some(CmdHeartdialType::CmdChangeScriptEmotionScRsp),
            6309 => ::std::option::Option::Some(CmdHeartdialType::CmdFinishEmotionDialoguePerformanceCsReq),
            6310 => ::std::option::Option::Some(CmdHeartdialType::CmdGetHeartDialInfoScRsp),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<CmdHeartdialType> {
        match str {
            "NIOFDIFADEK_PCPDHELPKEM" => ::std::option::Option::Some(CmdHeartdialType::NIOFDIFADEK_PCPDHELPKEM),
            "CmdSubmitEmotionItemCsReq" => ::std::option::Option::Some(CmdHeartdialType::CmdSubmitEmotionItemCsReq),
            "CmdHeartDialTraceScriptCsReq" => ::std::option::Option::Some(CmdHeartdialType::CmdHeartDialTraceScriptCsReq),
            "CmdSubmitEmotionItemScRsp" => ::std::option::Option::Some(CmdHeartdialType::CmdSubmitEmotionItemScRsp),
            "CmdHeartDialScriptChangeScNotify" => ::std::option::Option::Some(CmdHeartdialType::CmdHeartDialScriptChangeScNotify),
            "CmdGetHeartDialInfoCsReq" => ::std::option::Option::Some(CmdHeartdialType::CmdGetHeartDialInfoCsReq),
            "CmdHeartDialTraceScriptScRsp" => ::std::option::Option::Some(CmdHeartdialType::CmdHeartDialTraceScriptScRsp),
            "CmdChangeScriptEmotionCsReq" => ::std::option::Option::Some(CmdHeartdialType::CmdChangeScriptEmotionCsReq),
            "CmdFinishEmotionDialoguePerformanceScRsp" => ::std::option::Option::Some(CmdHeartdialType::CmdFinishEmotionDialoguePerformanceScRsp),
            "CmdChangeScriptEmotionScRsp" => ::std::option::Option::Some(CmdHeartdialType::CmdChangeScriptEmotionScRsp),
            "CmdFinishEmotionDialoguePerformanceCsReq" => ::std::option::Option::Some(CmdHeartdialType::CmdFinishEmotionDialoguePerformanceCsReq),
            "CmdGetHeartDialInfoScRsp" => ::std::option::Option::Some(CmdHeartdialType::CmdGetHeartDialInfoScRsp),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [CmdHeartdialType] = &[
        CmdHeartdialType::NIOFDIFADEK_PCPDHELPKEM,
        CmdHeartdialType::CmdSubmitEmotionItemCsReq,
        CmdHeartdialType::CmdHeartDialTraceScriptCsReq,
        CmdHeartdialType::CmdSubmitEmotionItemScRsp,
        CmdHeartdialType::CmdHeartDialScriptChangeScNotify,
        CmdHeartdialType::CmdGetHeartDialInfoCsReq,
        CmdHeartdialType::CmdHeartDialTraceScriptScRsp,
        CmdHeartdialType::CmdChangeScriptEmotionCsReq,
        CmdHeartdialType::CmdFinishEmotionDialoguePerformanceScRsp,
        CmdHeartdialType::CmdChangeScriptEmotionScRsp,
        CmdHeartdialType::CmdFinishEmotionDialoguePerformanceCsReq,
        CmdHeartdialType::CmdGetHeartDialInfoScRsp,
    ];
}

impl ::protobuf::EnumFull for CmdHeartdialType {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("CmdHeartdialType").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = match self {
            CmdHeartdialType::NIOFDIFADEK_PCPDHELPKEM => 0,
            CmdHeartdialType::CmdSubmitEmotionItemCsReq => 1,
            CmdHeartdialType::CmdHeartDialTraceScriptCsReq => 2,
            CmdHeartdialType::CmdSubmitEmotionItemScRsp => 3,
            CmdHeartdialType::CmdHeartDialScriptChangeScNotify => 4,
            CmdHeartdialType::CmdGetHeartDialInfoCsReq => 5,
            CmdHeartdialType::CmdHeartDialTraceScriptScRsp => 6,
            CmdHeartdialType::CmdChangeScriptEmotionCsReq => 7,
            CmdHeartdialType::CmdFinishEmotionDialoguePerformanceScRsp => 8,
            CmdHeartdialType::CmdChangeScriptEmotionScRsp => 9,
            CmdHeartdialType::CmdFinishEmotionDialoguePerformanceCsReq => 10,
            CmdHeartdialType::CmdGetHeartDialInfoScRsp => 11,
        };
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for CmdHeartdialType {
    fn default() -> Self {
        CmdHeartdialType::NIOFDIFADEK_PCPDHELPKEM
    }
}

impl CmdHeartdialType {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<CmdHeartdialType>("CmdHeartdialType")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x16CmdHeartdialType.proto*\xbc\x03\n\x10CmdHeartdialType\x12\x1b\n\
    \x17NIOFDIFADEK_PCPDHELPKEM\x10\0\x12\x1e\n\x19CmdSubmitEmotionItemCsReq\
    \x10\xaa1\x12!\n\x1cCmdHeartDialTraceScriptCsReq\x10\xb61\x12\x1e\n\x19C\
    mdSubmitEmotionItemScRsp\x10\xae1\x12%\n\x20CmdHeartDialScriptChangeScNo\
    tify\x10\xdb1\x12\x1d\n\x18CmdGetHeartDialInfoCsReq\x10\xf71\x12!\n\x1cC\
    mdHeartDialTraceScriptScRsp\x10\xc31\x12\x20\n\x1bCmdChangeScriptEmotion\
    CsReq\x10\xfa1\x12-\n(CmdFinishEmotionDialoguePerformanceScRsp\x10\xfe1\
    \x12\x20\n\x1bCmdChangeScriptEmotionScRsp\x10\xfb1\x12-\n(CmdFinishEmoti\
    onDialoguePerformanceCsReq\x10\xa51\x12\x1d\n\x18CmdGetHeartDialInfoScRs\
    p\x10\xa61b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(CmdHeartdialType::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
