// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `DCEBJIGAPEI.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:DCEBJIGAPEI)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct DCEBJIGAPEI {
    // message fields
    // @@protoc_insertion_point(field:DCEBJIGAPEI.reason)
    pub reason: ::protobuf::EnumOrUnknown<super::GLJLEEPOCDA::GLJLEEPOCDA>,
    // @@protoc_insertion_point(field:DCEBJIGAPEI.wave)
    pub wave: u32,
    // @@protoc_insertion_point(field:DCEBJIGAPEI.stage_id)
    pub stage_id: u32,
    // @@protoc_insertion_point(field:DCEBJIGAPEI.cur_hp)
    pub cur_hp: u32,
    // @@protoc_insertion_point(field:DCEBJIGAPEI.max_hp)
    pub max_hp: u32,
    // @@protoc_insertion_point(field:DCEBJIGAPEI.HAIOHANDIKI)
    pub HAIOHANDIKI: ::std::vec::Vec<super::LKFNDAOGMMO::LKFNDAOGMMO>,
    // special fields
    // @@protoc_insertion_point(special_field:DCEBJIGAPEI.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a DCEBJIGAPEI {
    fn default() -> &'a DCEBJIGAPEI {
        <DCEBJIGAPEI as ::protobuf::Message>::default_instance()
    }
}

impl DCEBJIGAPEI {
    pub fn new() -> DCEBJIGAPEI {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(6);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "reason",
            |m: &DCEBJIGAPEI| { &m.reason },
            |m: &mut DCEBJIGAPEI| { &mut m.reason },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "wave",
            |m: &DCEBJIGAPEI| { &m.wave },
            |m: &mut DCEBJIGAPEI| { &mut m.wave },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "stage_id",
            |m: &DCEBJIGAPEI| { &m.stage_id },
            |m: &mut DCEBJIGAPEI| { &mut m.stage_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "cur_hp",
            |m: &DCEBJIGAPEI| { &m.cur_hp },
            |m: &mut DCEBJIGAPEI| { &mut m.cur_hp },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "max_hp",
            |m: &DCEBJIGAPEI| { &m.max_hp },
            |m: &mut DCEBJIGAPEI| { &mut m.max_hp },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "HAIOHANDIKI",
            |m: &DCEBJIGAPEI| { &m.HAIOHANDIKI },
            |m: &mut DCEBJIGAPEI| { &mut m.HAIOHANDIKI },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<DCEBJIGAPEI>(
            "DCEBJIGAPEI",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for DCEBJIGAPEI {
    const NAME: &'static str = "DCEBJIGAPEI";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                120 => {
                    self.reason = is.read_enum_or_unknown()?;
                },
                48 => {
                    self.wave = is.read_uint32()?;
                },
                80 => {
                    self.stage_id = is.read_uint32()?;
                },
                72 => {
                    self.cur_hp = is.read_uint32()?;
                },
                56 => {
                    self.max_hp = is.read_uint32()?;
                },
                34 => {
                    self.HAIOHANDIKI.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.reason != ::protobuf::EnumOrUnknown::new(super::GLJLEEPOCDA::GLJLEEPOCDA::GLJLEEPOCDA_PCPDHELPKEM) {
            my_size += ::protobuf::rt::int32_size(15, self.reason.value());
        }
        if self.wave != 0 {
            my_size += ::protobuf::rt::uint32_size(6, self.wave);
        }
        if self.stage_id != 0 {
            my_size += ::protobuf::rt::uint32_size(10, self.stage_id);
        }
        if self.cur_hp != 0 {
            my_size += ::protobuf::rt::uint32_size(9, self.cur_hp);
        }
        if self.max_hp != 0 {
            my_size += ::protobuf::rt::uint32_size(7, self.max_hp);
        }
        for value in &self.HAIOHANDIKI {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.reason != ::protobuf::EnumOrUnknown::new(super::GLJLEEPOCDA::GLJLEEPOCDA::GLJLEEPOCDA_PCPDHELPKEM) {
            os.write_enum(15, ::protobuf::EnumOrUnknown::value(&self.reason))?;
        }
        if self.wave != 0 {
            os.write_uint32(6, self.wave)?;
        }
        if self.stage_id != 0 {
            os.write_uint32(10, self.stage_id)?;
        }
        if self.cur_hp != 0 {
            os.write_uint32(9, self.cur_hp)?;
        }
        if self.max_hp != 0 {
            os.write_uint32(7, self.max_hp)?;
        }
        for v in &self.HAIOHANDIKI {
            ::protobuf::rt::write_message_field_with_cached_size(4, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> DCEBJIGAPEI {
        DCEBJIGAPEI::new()
    }

    fn clear(&mut self) {
        self.reason = ::protobuf::EnumOrUnknown::new(super::GLJLEEPOCDA::GLJLEEPOCDA::GLJLEEPOCDA_PCPDHELPKEM);
        self.wave = 0;
        self.stage_id = 0;
        self.cur_hp = 0;
        self.max_hp = 0;
        self.HAIOHANDIKI.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static DCEBJIGAPEI {
        static instance: DCEBJIGAPEI = DCEBJIGAPEI {
            reason: ::protobuf::EnumOrUnknown::from_i32(0),
            wave: 0,
            stage_id: 0,
            cur_hp: 0,
            max_hp: 0,
            HAIOHANDIKI: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for DCEBJIGAPEI {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("DCEBJIGAPEI").unwrap()).clone()
    }
}

impl ::std::fmt::Display for DCEBJIGAPEI {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for DCEBJIGAPEI {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11DCEBJIGAPEI.proto\x1a\x11GLJLEEPOCDA.proto\x1a\x11LKFNDAOGMMO.prot\
    o\"\xc0\x01\n\x0bDCEBJIGAPEI\x12$\n\x06reason\x18\x0f\x20\x01(\x0e2\x0c.\
    GLJLEEPOCDAR\x06reason\x12\x12\n\x04wave\x18\x06\x20\x01(\rR\x04wave\x12\
    \x19\n\x08stage_id\x18\n\x20\x01(\rR\x07stageId\x12\x15\n\x06cur_hp\x18\
    \t\x20\x01(\rR\x05curHp\x12\x15\n\x06max_hp\x18\x07\x20\x01(\rR\x05maxHp\
    \x12.\n\x0bHAIOHANDIKI\x18\x04\x20\x03(\x0b2\x0c.LKFNDAOGMMOR\x0bHAIOHAN\
    DIKIb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(2);
            deps.push(super::GLJLEEPOCDA::file_descriptor().clone());
            deps.push(super::LKFNDAOGMMO::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(DCEBJIGAPEI::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
