// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `DLGEGGCHCID.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:DLGEGGCHCID)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct DLGEGGCHCID {
    // message fields
    // @@protoc_insertion_point(field:DLGEGGCHCID.role_star)
    pub role_star: u32,
    // @@protoc_insertion_point(field:DLGEGGCHCID.PGNMDJIIKJB)
    pub PGNMDJIIKJB: ::std::vec::Vec<super::LHPPIAKKFME::LHPPIAKKFME>,
    // special fields
    // @@protoc_insertion_point(special_field:DLGEGGCHCID.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a DLGEGGCHCID {
    fn default() -> &'a DLGEGGCHCID {
        <DLGEGGCHCID as ::protobuf::Message>::default_instance()
    }
}

impl DLGEGGCHCID {
    pub fn new() -> DLGEGGCHCID {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "role_star",
            |m: &DLGEGGCHCID| { &m.role_star },
            |m: &mut DLGEGGCHCID| { &mut m.role_star },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "PGNMDJIIKJB",
            |m: &DLGEGGCHCID| { &m.PGNMDJIIKJB },
            |m: &mut DLGEGGCHCID| { &mut m.PGNMDJIIKJB },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<DLGEGGCHCID>(
            "DLGEGGCHCID",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for DLGEGGCHCID {
    const NAME: &'static str = "DLGEGGCHCID";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                64 => {
                    self.role_star = is.read_uint32()?;
                },
                114 => {
                    self.PGNMDJIIKJB.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.role_star != 0 {
            my_size += ::protobuf::rt::uint32_size(8, self.role_star);
        }
        for value in &self.PGNMDJIIKJB {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.role_star != 0 {
            os.write_uint32(8, self.role_star)?;
        }
        for v in &self.PGNMDJIIKJB {
            ::protobuf::rt::write_message_field_with_cached_size(14, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> DLGEGGCHCID {
        DLGEGGCHCID::new()
    }

    fn clear(&mut self) {
        self.role_star = 0;
        self.PGNMDJIIKJB.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static DLGEGGCHCID {
        static instance: DLGEGGCHCID = DLGEGGCHCID {
            role_star: 0,
            PGNMDJIIKJB: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for DLGEGGCHCID {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("DLGEGGCHCID").unwrap()).clone()
    }
}

impl ::std::fmt::Display for DLGEGGCHCID {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for DLGEGGCHCID {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11DLGEGGCHCID.proto\x1a\x11LHPPIAKKFME.proto\"Z\n\x0bDLGEGGCHCID\x12\
    \x1b\n\trole_star\x18\x08\x20\x01(\rR\x08roleStar\x12.\n\x0bPGNMDJIIKJB\
    \x18\x0e\x20\x03(\x0b2\x0c.LHPPIAKKFMER\x0bPGNMDJIIKJBb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::LHPPIAKKFME::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(DLGEGGCHCID::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
