// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `DNJFGOLLCCB.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:DNJFGOLLCCB)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct DNJFGOLLCCB {
    // message fields
    // @@protoc_insertion_point(field:DNJFGOLLCCB.LGMNKILABNL)
    pub LGMNKILABNL: ::std::string::String,
    // @@protoc_insertion_point(field:DNJFGOLLCCB.CJBODNKDFAG)
    pub CJBODNKDFAG: ::std::string::String,
    // @@protoc_insertion_point(field:DNJFGOLLCCB.AJLGJKMEFJL)
    pub AJLGJKMEFJL: ::std::string::String,
    // @@protoc_insertion_point(field:DNJFGOLLCCB.GNCPFFHBIPN)
    pub GNCPFFHBIPN: ::std::string::String,
    // @@protoc_insertion_point(field:DNJFGOLLCCB.COOFHIGHJDN)
    pub COOFHIGHJDN: ::std::string::String,
    // @@protoc_insertion_point(field:DNJFGOLLCCB.NMBNLPOHJCM)
    pub NMBNLPOHJCM: ::std::string::String,
    // @@protoc_insertion_point(field:DNJFGOLLCCB.CDNBELIAJFN)
    pub CDNBELIAJFN: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:DNJFGOLLCCB.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a DNJFGOLLCCB {
    fn default() -> &'a DNJFGOLLCCB {
        <DNJFGOLLCCB as ::protobuf::Message>::default_instance()
    }
}

impl DNJFGOLLCCB {
    pub fn new() -> DNJFGOLLCCB {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(7);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "LGMNKILABNL",
            |m: &DNJFGOLLCCB| { &m.LGMNKILABNL },
            |m: &mut DNJFGOLLCCB| { &mut m.LGMNKILABNL },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "CJBODNKDFAG",
            |m: &DNJFGOLLCCB| { &m.CJBODNKDFAG },
            |m: &mut DNJFGOLLCCB| { &mut m.CJBODNKDFAG },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "AJLGJKMEFJL",
            |m: &DNJFGOLLCCB| { &m.AJLGJKMEFJL },
            |m: &mut DNJFGOLLCCB| { &mut m.AJLGJKMEFJL },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "GNCPFFHBIPN",
            |m: &DNJFGOLLCCB| { &m.GNCPFFHBIPN },
            |m: &mut DNJFGOLLCCB| { &mut m.GNCPFFHBIPN },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "COOFHIGHJDN",
            |m: &DNJFGOLLCCB| { &m.COOFHIGHJDN },
            |m: &mut DNJFGOLLCCB| { &mut m.COOFHIGHJDN },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "NMBNLPOHJCM",
            |m: &DNJFGOLLCCB| { &m.NMBNLPOHJCM },
            |m: &mut DNJFGOLLCCB| { &mut m.NMBNLPOHJCM },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "CDNBELIAJFN",
            |m: &DNJFGOLLCCB| { &m.CDNBELIAJFN },
            |m: &mut DNJFGOLLCCB| { &mut m.CDNBELIAJFN },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<DNJFGOLLCCB>(
            "DNJFGOLLCCB",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for DNJFGOLLCCB {
    const NAME: &'static str = "DNJFGOLLCCB";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.LGMNKILABNL = is.read_string()?;
                },
                18 => {
                    self.CJBODNKDFAG = is.read_string()?;
                },
                26 => {
                    self.AJLGJKMEFJL = is.read_string()?;
                },
                34 => {
                    self.GNCPFFHBIPN = is.read_string()?;
                },
                42 => {
                    self.COOFHIGHJDN = is.read_string()?;
                },
                50 => {
                    self.NMBNLPOHJCM = is.read_string()?;
                },
                58 => {
                    self.CDNBELIAJFN = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.LGMNKILABNL.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.LGMNKILABNL);
        }
        if !self.CJBODNKDFAG.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.CJBODNKDFAG);
        }
        if !self.AJLGJKMEFJL.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.AJLGJKMEFJL);
        }
        if !self.GNCPFFHBIPN.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.GNCPFFHBIPN);
        }
        if !self.COOFHIGHJDN.is_empty() {
            my_size += ::protobuf::rt::string_size(5, &self.COOFHIGHJDN);
        }
        if !self.NMBNLPOHJCM.is_empty() {
            my_size += ::protobuf::rt::string_size(6, &self.NMBNLPOHJCM);
        }
        if !self.CDNBELIAJFN.is_empty() {
            my_size += ::protobuf::rt::string_size(7, &self.CDNBELIAJFN);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.LGMNKILABNL.is_empty() {
            os.write_string(1, &self.LGMNKILABNL)?;
        }
        if !self.CJBODNKDFAG.is_empty() {
            os.write_string(2, &self.CJBODNKDFAG)?;
        }
        if !self.AJLGJKMEFJL.is_empty() {
            os.write_string(3, &self.AJLGJKMEFJL)?;
        }
        if !self.GNCPFFHBIPN.is_empty() {
            os.write_string(4, &self.GNCPFFHBIPN)?;
        }
        if !self.COOFHIGHJDN.is_empty() {
            os.write_string(5, &self.COOFHIGHJDN)?;
        }
        if !self.NMBNLPOHJCM.is_empty() {
            os.write_string(6, &self.NMBNLPOHJCM)?;
        }
        if !self.CDNBELIAJFN.is_empty() {
            os.write_string(7, &self.CDNBELIAJFN)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> DNJFGOLLCCB {
        DNJFGOLLCCB::new()
    }

    fn clear(&mut self) {
        self.LGMNKILABNL.clear();
        self.CJBODNKDFAG.clear();
        self.AJLGJKMEFJL.clear();
        self.GNCPFFHBIPN.clear();
        self.COOFHIGHJDN.clear();
        self.NMBNLPOHJCM.clear();
        self.CDNBELIAJFN.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static DNJFGOLLCCB {
        static instance: DNJFGOLLCCB = DNJFGOLLCCB {
            LGMNKILABNL: ::std::string::String::new(),
            CJBODNKDFAG: ::std::string::String::new(),
            AJLGJKMEFJL: ::std::string::String::new(),
            GNCPFFHBIPN: ::std::string::String::new(),
            COOFHIGHJDN: ::std::string::String::new(),
            NMBNLPOHJCM: ::std::string::String::new(),
            CDNBELIAJFN: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for DNJFGOLLCCB {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("DNJFGOLLCCB").unwrap()).clone()
    }
}

impl ::std::fmt::Display for DNJFGOLLCCB {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for DNJFGOLLCCB {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11DNJFGOLLCCB.proto\"\xfb\x01\n\x0bDNJFGOLLCCB\x12\x20\n\x0bLGMNKILA\
    BNL\x18\x01\x20\x01(\tR\x0bLGMNKILABNL\x12\x20\n\x0bCJBODNKDFAG\x18\x02\
    \x20\x01(\tR\x0bCJBODNKDFAG\x12\x20\n\x0bAJLGJKMEFJL\x18\x03\x20\x01(\tR\
    \x0bAJLGJKMEFJL\x12\x20\n\x0bGNCPFFHBIPN\x18\x04\x20\x01(\tR\x0bGNCPFFHB\
    IPN\x12\x20\n\x0bCOOFHIGHJDN\x18\x05\x20\x01(\tR\x0bCOOFHIGHJDN\x12\x20\
    \n\x0bNMBNLPOHJCM\x18\x06\x20\x01(\tR\x0bNMBNLPOHJCM\x12\x20\n\x0bCDNBEL\
    IAJFN\x18\x07\x20\x01(\tR\x0bCDNBELIAJFNb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(DNJFGOLLCCB::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
