// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `DPOGOCFMOFP.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:DPOGOCFMOFP)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct DPOGOCFMOFP {
    // message fields
    // @@protoc_insertion_point(field:DPOGOCFMOFP.ODDFEAEEJJD)
    pub ODDFEAEEJJD: u32,
    // @@protoc_insertion_point(field:DPOGOCFMOFP.COFELCKDBJE)
    pub COFELCKDBJE: u32,
    // @@protoc_insertion_point(field:DPOGOCFMOFP.EDNIACNOPMN)
    pub EDNIACNOPMN: u32,
    // @@protoc_insertion_point(field:DPOGOCFMOFP.friend_recommend_list)
    pub friend_recommend_list: ::std::vec::Vec<super::CLHDILKAKEP::CLHDILKAKEP>,
    // special fields
    // @@protoc_insertion_point(special_field:DPOGOCFMOFP.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a DPOGOCFMOFP {
    fn default() -> &'a DPOGOCFMOFP {
        <DPOGOCFMOFP as ::protobuf::Message>::default_instance()
    }
}

impl DPOGOCFMOFP {
    pub fn new() -> DPOGOCFMOFP {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "ODDFEAEEJJD",
            |m: &DPOGOCFMOFP| { &m.ODDFEAEEJJD },
            |m: &mut DPOGOCFMOFP| { &mut m.ODDFEAEEJJD },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "COFELCKDBJE",
            |m: &DPOGOCFMOFP| { &m.COFELCKDBJE },
            |m: &mut DPOGOCFMOFP| { &mut m.COFELCKDBJE },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "EDNIACNOPMN",
            |m: &DPOGOCFMOFP| { &m.EDNIACNOPMN },
            |m: &mut DPOGOCFMOFP| { &mut m.EDNIACNOPMN },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "friend_recommend_list",
            |m: &DPOGOCFMOFP| { &m.friend_recommend_list },
            |m: &mut DPOGOCFMOFP| { &mut m.friend_recommend_list },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<DPOGOCFMOFP>(
            "DPOGOCFMOFP",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for DPOGOCFMOFP {
    const NAME: &'static str = "DPOGOCFMOFP";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                96 => {
                    self.ODDFEAEEJJD = is.read_uint32()?;
                },
                32 => {
                    self.COFELCKDBJE = is.read_uint32()?;
                },
                56 => {
                    self.EDNIACNOPMN = is.read_uint32()?;
                },
                50 => {
                    self.friend_recommend_list.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.ODDFEAEEJJD != 0 {
            my_size += ::protobuf::rt::uint32_size(12, self.ODDFEAEEJJD);
        }
        if self.COFELCKDBJE != 0 {
            my_size += ::protobuf::rt::uint32_size(4, self.COFELCKDBJE);
        }
        if self.EDNIACNOPMN != 0 {
            my_size += ::protobuf::rt::uint32_size(7, self.EDNIACNOPMN);
        }
        for value in &self.friend_recommend_list {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.ODDFEAEEJJD != 0 {
            os.write_uint32(12, self.ODDFEAEEJJD)?;
        }
        if self.COFELCKDBJE != 0 {
            os.write_uint32(4, self.COFELCKDBJE)?;
        }
        if self.EDNIACNOPMN != 0 {
            os.write_uint32(7, self.EDNIACNOPMN)?;
        }
        for v in &self.friend_recommend_list {
            ::protobuf::rt::write_message_field_with_cached_size(6, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> DPOGOCFMOFP {
        DPOGOCFMOFP::new()
    }

    fn clear(&mut self) {
        self.ODDFEAEEJJD = 0;
        self.COFELCKDBJE = 0;
        self.EDNIACNOPMN = 0;
        self.friend_recommend_list.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static DPOGOCFMOFP {
        static instance: DPOGOCFMOFP = DPOGOCFMOFP {
            ODDFEAEEJJD: 0,
            COFELCKDBJE: 0,
            EDNIACNOPMN: 0,
            friend_recommend_list: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for DPOGOCFMOFP {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("DPOGOCFMOFP").unwrap()).clone()
    }
}

impl ::std::fmt::Display for DPOGOCFMOFP {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for DPOGOCFMOFP {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11DPOGOCFMOFP.proto\x1a\x11CLHDILKAKEP.proto\"\xb5\x01\n\x0bDPOGOCFM\
    OFP\x12\x20\n\x0bODDFEAEEJJD\x18\x0c\x20\x01(\rR\x0bODDFEAEEJJD\x12\x20\
    \n\x0bCOFELCKDBJE\x18\x04\x20\x01(\rR\x0bCOFELCKDBJE\x12\x20\n\x0bEDNIAC\
    NOPMN\x18\x07\x20\x01(\rR\x0bEDNIACNOPMN\x12@\n\x15friend_recommend_list\
    \x18\x06\x20\x03(\x0b2\x0c.CLHDILKAKEPR\x13friendRecommendListb\x06proto\
    3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::CLHDILKAKEP::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(DPOGOCFMOFP::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
