// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `FAJGLOFICEI.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:FAJGLOFICEI)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct FAJGLOFICEI {
    // message fields
    // @@protoc_insertion_point(field:FAJGLOFICEI.content_id)
    pub content_id: u32,
    // @@protoc_insertion_point(field:FAJGLOFICEI.NFDAJHJDGOJ)
    pub NFDAJHJDGOJ: u32,
    // @@protoc_insertion_point(field:FAJGLOFICEI.JMIENBBMPAG)
    pub JMIENBBMPAG: u32,
    // @@protoc_insertion_point(field:FAJGLOFICEI.ANBBPPHBCJH)
    pub ANBBPPHBCJH: u32,
    // special fields
    // @@protoc_insertion_point(special_field:FAJGLOFICEI.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a FAJGLOFICEI {
    fn default() -> &'a FAJGLOFICEI {
        <FAJGLOFICEI as ::protobuf::Message>::default_instance()
    }
}

impl FAJGLOFICEI {
    pub fn new() -> FAJGLOFICEI {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "content_id",
            |m: &FAJGLOFICEI| { &m.content_id },
            |m: &mut FAJGLOFICEI| { &mut m.content_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "NFDAJHJDGOJ",
            |m: &FAJGLOFICEI| { &m.NFDAJHJDGOJ },
            |m: &mut FAJGLOFICEI| { &mut m.NFDAJHJDGOJ },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "JMIENBBMPAG",
            |m: &FAJGLOFICEI| { &m.JMIENBBMPAG },
            |m: &mut FAJGLOFICEI| { &mut m.JMIENBBMPAG },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "ANBBPPHBCJH",
            |m: &FAJGLOFICEI| { &m.ANBBPPHBCJH },
            |m: &mut FAJGLOFICEI| { &mut m.ANBBPPHBCJH },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<FAJGLOFICEI>(
            "FAJGLOFICEI",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for FAJGLOFICEI {
    const NAME: &'static str = "FAJGLOFICEI";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                88 => {
                    self.content_id = is.read_uint32()?;
                },
                40 => {
                    self.NFDAJHJDGOJ = is.read_uint32()?;
                },
                80 => {
                    self.JMIENBBMPAG = is.read_uint32()?;
                },
                120 => {
                    self.ANBBPPHBCJH = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.content_id != 0 {
            my_size += ::protobuf::rt::uint32_size(11, self.content_id);
        }
        if self.NFDAJHJDGOJ != 0 {
            my_size += ::protobuf::rt::uint32_size(5, self.NFDAJHJDGOJ);
        }
        if self.JMIENBBMPAG != 0 {
            my_size += ::protobuf::rt::uint32_size(10, self.JMIENBBMPAG);
        }
        if self.ANBBPPHBCJH != 0 {
            my_size += ::protobuf::rt::uint32_size(15, self.ANBBPPHBCJH);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.content_id != 0 {
            os.write_uint32(11, self.content_id)?;
        }
        if self.NFDAJHJDGOJ != 0 {
            os.write_uint32(5, self.NFDAJHJDGOJ)?;
        }
        if self.JMIENBBMPAG != 0 {
            os.write_uint32(10, self.JMIENBBMPAG)?;
        }
        if self.ANBBPPHBCJH != 0 {
            os.write_uint32(15, self.ANBBPPHBCJH)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> FAJGLOFICEI {
        FAJGLOFICEI::new()
    }

    fn clear(&mut self) {
        self.content_id = 0;
        self.NFDAJHJDGOJ = 0;
        self.JMIENBBMPAG = 0;
        self.ANBBPPHBCJH = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static FAJGLOFICEI {
        static instance: FAJGLOFICEI = FAJGLOFICEI {
            content_id: 0,
            NFDAJHJDGOJ: 0,
            JMIENBBMPAG: 0,
            ANBBPPHBCJH: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for FAJGLOFICEI {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("FAJGLOFICEI").unwrap()).clone()
    }
}

impl ::std::fmt::Display for FAJGLOFICEI {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for FAJGLOFICEI {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11FAJGLOFICEI.proto\"\x92\x01\n\x0bFAJGLOFICEI\x12\x1d\n\ncontent_id\
    \x18\x0b\x20\x01(\rR\tcontentId\x12\x20\n\x0bNFDAJHJDGOJ\x18\x05\x20\x01\
    (\rR\x0bNFDAJHJDGOJ\x12\x20\n\x0bJMIENBBMPAG\x18\n\x20\x01(\rR\x0bJMIENB\
    BMPAG\x12\x20\n\x0bANBBPPHBCJH\x18\x0f\x20\x01(\rR\x0bANBBPPHBCJHb\x06pr\
    oto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(FAJGLOFICEI::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
