// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `FKANIBDJNKG.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:FKANIBDJNKG)
pub enum FKANIBDJNKG {
    // @@protoc_insertion_point(enum_value:FKANIBDJNKG.FKANIBDJNKG_OFGHJKIHMIB)
    FKANIBDJNKG_OFGHJKIHMIB = 0,
    // @@protoc_insertion_point(enum_value:FKANIBDJNKG.FKANIBDJNKG_LADEPBBHHGO)
    FKANIBDJNKG_LADEPBBHHGO = 1,
    // @@protoc_insertion_point(enum_value:FKANIBDJNKG.FKANIBDJNKG_ANEGGGOEBBN)
    FKANIBDJNKG_ANEGGGOEBBN = 2,
    // @@protoc_insertion_point(enum_value:FKANIBDJNKG.FKANIBDJNKG_HEFAIOFDANA)
    FKANIBDJNKG_HEFAIOFDANA = 3,
    // @@protoc_insertion_point(enum_value:FKANIBDJNKG.FKANIBDJNKG_FODCLFOALCI)
    FKANIBDJNKG_FODCLFOALCI = 4,
    // @@protoc_insertion_point(enum_value:FKANIBDJNKG.FKANIBDJNKG_FCEHNMJJABE)
    FKANIBDJNKG_FCEHNMJJABE = 5,
    // @@protoc_insertion_point(enum_value:FKANIBDJNKG.FKANIBDJNKG_FNKDIEBKOHA)
    FKANIBDJNKG_FNKDIEBKOHA = 6,
    // @@protoc_insertion_point(enum_value:FKANIBDJNKG.FKANIBDJNKG_MMNHGLDDFBC)
    FKANIBDJNKG_MMNHGLDDFBC = 7,
}

impl ::protobuf::Enum for FKANIBDJNKG {
    const NAME: &'static str = "FKANIBDJNKG";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<FKANIBDJNKG> {
        match value {
            0 => ::std::option::Option::Some(FKANIBDJNKG::FKANIBDJNKG_OFGHJKIHMIB),
            1 => ::std::option::Option::Some(FKANIBDJNKG::FKANIBDJNKG_LADEPBBHHGO),
            2 => ::std::option::Option::Some(FKANIBDJNKG::FKANIBDJNKG_ANEGGGOEBBN),
            3 => ::std::option::Option::Some(FKANIBDJNKG::FKANIBDJNKG_HEFAIOFDANA),
            4 => ::std::option::Option::Some(FKANIBDJNKG::FKANIBDJNKG_FODCLFOALCI),
            5 => ::std::option::Option::Some(FKANIBDJNKG::FKANIBDJNKG_FCEHNMJJABE),
            6 => ::std::option::Option::Some(FKANIBDJNKG::FKANIBDJNKG_FNKDIEBKOHA),
            7 => ::std::option::Option::Some(FKANIBDJNKG::FKANIBDJNKG_MMNHGLDDFBC),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<FKANIBDJNKG> {
        match str {
            "FKANIBDJNKG_OFGHJKIHMIB" => ::std::option::Option::Some(FKANIBDJNKG::FKANIBDJNKG_OFGHJKIHMIB),
            "FKANIBDJNKG_LADEPBBHHGO" => ::std::option::Option::Some(FKANIBDJNKG::FKANIBDJNKG_LADEPBBHHGO),
            "FKANIBDJNKG_ANEGGGOEBBN" => ::std::option::Option::Some(FKANIBDJNKG::FKANIBDJNKG_ANEGGGOEBBN),
            "FKANIBDJNKG_HEFAIOFDANA" => ::std::option::Option::Some(FKANIBDJNKG::FKANIBDJNKG_HEFAIOFDANA),
            "FKANIBDJNKG_FODCLFOALCI" => ::std::option::Option::Some(FKANIBDJNKG::FKANIBDJNKG_FODCLFOALCI),
            "FKANIBDJNKG_FCEHNMJJABE" => ::std::option::Option::Some(FKANIBDJNKG::FKANIBDJNKG_FCEHNMJJABE),
            "FKANIBDJNKG_FNKDIEBKOHA" => ::std::option::Option::Some(FKANIBDJNKG::FKANIBDJNKG_FNKDIEBKOHA),
            "FKANIBDJNKG_MMNHGLDDFBC" => ::std::option::Option::Some(FKANIBDJNKG::FKANIBDJNKG_MMNHGLDDFBC),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [FKANIBDJNKG] = &[
        FKANIBDJNKG::FKANIBDJNKG_OFGHJKIHMIB,
        FKANIBDJNKG::FKANIBDJNKG_LADEPBBHHGO,
        FKANIBDJNKG::FKANIBDJNKG_ANEGGGOEBBN,
        FKANIBDJNKG::FKANIBDJNKG_HEFAIOFDANA,
        FKANIBDJNKG::FKANIBDJNKG_FODCLFOALCI,
        FKANIBDJNKG::FKANIBDJNKG_FCEHNMJJABE,
        FKANIBDJNKG::FKANIBDJNKG_FNKDIEBKOHA,
        FKANIBDJNKG::FKANIBDJNKG_MMNHGLDDFBC,
    ];
}

impl ::protobuf::EnumFull for FKANIBDJNKG {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("FKANIBDJNKG").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for FKANIBDJNKG {
    fn default() -> Self {
        FKANIBDJNKG::FKANIBDJNKG_OFGHJKIHMIB
    }
}

impl FKANIBDJNKG {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<FKANIBDJNKG>("FKANIBDJNKG")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11FKANIBDJNKG.proto*\xf5\x01\n\x0bFKANIBDJNKG\x12\x1b\n\x17FKANIBDJN\
    KG_OFGHJKIHMIB\x10\0\x12\x1b\n\x17FKANIBDJNKG_LADEPBBHHGO\x10\x01\x12\
    \x1b\n\x17FKANIBDJNKG_ANEGGGOEBBN\x10\x02\x12\x1b\n\x17FKANIBDJNKG_HEFAI\
    OFDANA\x10\x03\x12\x1b\n\x17FKANIBDJNKG_FODCLFOALCI\x10\x04\x12\x1b\n\
    \x17FKANIBDJNKG_FCEHNMJJABE\x10\x05\x12\x1b\n\x17FKANIBDJNKG_FNKDIEBKOHA\
    \x10\x06\x12\x1b\n\x17FKANIBDJNKG_MMNHGLDDFBC\x10\x07b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(FKANIBDJNKG::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
