// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `GCHPNHBDCDO.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:GCHPNHBDCDO)
pub enum GCHPNHBDCDO {
    // @@protoc_insertion_point(enum_value:GCHPNHBDCDO.GCHPNHBDCDO_BFKFDKMGLHO)
    GCHPNHBDCDO_BFKFDKMGLHO = 0,
    // @@protoc_insertion_point(enum_value:GCHPNHBDCDO.GCHPNHBDCDO_NOFGAIIPIDK)
    GCHPNHBDCDO_NOFGAIIPIDK = 1,
    // @@protoc_insertion_point(enum_value:GCHPNHBDCDO.GCHPNHBDCDO_GNGGEPLIMJE)
    GCHPNHBDCDO_GNGGEPLIMJE = 2,
}

impl ::protobuf::Enum for GCHPNHBDCDO {
    const NAME: &'static str = "GCHPNHBDCDO";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<GCHPNHBDCDO> {
        match value {
            0 => ::std::option::Option::Some(GCHPNHBDCDO::GCHPNHBDCDO_BFKFDKMGLHO),
            1 => ::std::option::Option::Some(GCHPNHBDCDO::GCHPNHBDCDO_NOFGAIIPIDK),
            2 => ::std::option::Option::Some(GCHPNHBDCDO::GCHPNHBDCDO_GNGGEPLIMJE),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<GCHPNHBDCDO> {
        match str {
            "GCHPNHBDCDO_BFKFDKMGLHO" => ::std::option::Option::Some(GCHPNHBDCDO::GCHPNHBDCDO_BFKFDKMGLHO),
            "GCHPNHBDCDO_NOFGAIIPIDK" => ::std::option::Option::Some(GCHPNHBDCDO::GCHPNHBDCDO_NOFGAIIPIDK),
            "GCHPNHBDCDO_GNGGEPLIMJE" => ::std::option::Option::Some(GCHPNHBDCDO::GCHPNHBDCDO_GNGGEPLIMJE),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [GCHPNHBDCDO] = &[
        GCHPNHBDCDO::GCHPNHBDCDO_BFKFDKMGLHO,
        GCHPNHBDCDO::GCHPNHBDCDO_NOFGAIIPIDK,
        GCHPNHBDCDO::GCHPNHBDCDO_GNGGEPLIMJE,
    ];
}

impl ::protobuf::EnumFull for GCHPNHBDCDO {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("GCHPNHBDCDO").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for GCHPNHBDCDO {
    fn default() -> Self {
        GCHPNHBDCDO::GCHPNHBDCDO_BFKFDKMGLHO
    }
}

impl GCHPNHBDCDO {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<GCHPNHBDCDO>("GCHPNHBDCDO")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11GCHPNHBDCDO.proto*d\n\x0bGCHPNHBDCDO\x12\x1b\n\x17GCHPNHBDCDO_BFKF\
    DKMGLHO\x10\0\x12\x1b\n\x17GCHPNHBDCDO_NOFGAIIPIDK\x10\x01\x12\x1b\n\x17\
    GCHPNHBDCDO_GNGGEPLIMJE\x10\x02b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(GCHPNHBDCDO::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
