// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `GetElfRestaurantDataScRsp.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:GetElfRestaurantDataScRsp)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct GetElfRestaurantDataScRsp {
    // message fields
    // @@protoc_insertion_point(field:GetElfRestaurantDataScRsp.BNJBFPCDAFE)
    pub BNJBFPCDAFE: ::protobuf::MessageField<super::BCNJMGCEGAA::BCNJMGCEGAA>,
    // @@protoc_insertion_point(field:GetElfRestaurantDataScRsp.OCGNOACLJAJ)
    pub OCGNOACLJAJ: ::protobuf::MessageField<super::NCPCAIKAJGD::NCPCAIKAJGD>,
    // @@protoc_insertion_point(field:GetElfRestaurantDataScRsp.retcode)
    pub retcode: u32,
    // @@protoc_insertion_point(field:GetElfRestaurantDataScRsp.DCIDLIFMNLA)
    pub DCIDLIFMNLA: ::protobuf::MessageField<super::BBCLLNPDIAH::BBCLLNPDIAH>,
    // @@protoc_insertion_point(field:GetElfRestaurantDataScRsp.LIBKPMMGGLJ)
    pub LIBKPMMGGLJ: ::protobuf::MessageField<super::AFOECDHJPII::AFOECDHJPII>,
    // @@protoc_insertion_point(field:GetElfRestaurantDataScRsp.KIIINGJLEHG)
    pub KIIINGJLEHG: ::protobuf::MessageField<super::MFLDHBJNEOO::MFLDHBJNEOO>,
    // special fields
    // @@protoc_insertion_point(special_field:GetElfRestaurantDataScRsp.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a GetElfRestaurantDataScRsp {
    fn default() -> &'a GetElfRestaurantDataScRsp {
        <GetElfRestaurantDataScRsp as ::protobuf::Message>::default_instance()
    }
}

impl GetElfRestaurantDataScRsp {
    pub fn new() -> GetElfRestaurantDataScRsp {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(6);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::BCNJMGCEGAA::BCNJMGCEGAA>(
            "BNJBFPCDAFE",
            |m: &GetElfRestaurantDataScRsp| { &m.BNJBFPCDAFE },
            |m: &mut GetElfRestaurantDataScRsp| { &mut m.BNJBFPCDAFE },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::NCPCAIKAJGD::NCPCAIKAJGD>(
            "OCGNOACLJAJ",
            |m: &GetElfRestaurantDataScRsp| { &m.OCGNOACLJAJ },
            |m: &mut GetElfRestaurantDataScRsp| { &mut m.OCGNOACLJAJ },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "retcode",
            |m: &GetElfRestaurantDataScRsp| { &m.retcode },
            |m: &mut GetElfRestaurantDataScRsp| { &mut m.retcode },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::BBCLLNPDIAH::BBCLLNPDIAH>(
            "DCIDLIFMNLA",
            |m: &GetElfRestaurantDataScRsp| { &m.DCIDLIFMNLA },
            |m: &mut GetElfRestaurantDataScRsp| { &mut m.DCIDLIFMNLA },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::AFOECDHJPII::AFOECDHJPII>(
            "LIBKPMMGGLJ",
            |m: &GetElfRestaurantDataScRsp| { &m.LIBKPMMGGLJ },
            |m: &mut GetElfRestaurantDataScRsp| { &mut m.LIBKPMMGGLJ },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::MFLDHBJNEOO::MFLDHBJNEOO>(
            "KIIINGJLEHG",
            |m: &GetElfRestaurantDataScRsp| { &m.KIIINGJLEHG },
            |m: &mut GetElfRestaurantDataScRsp| { &mut m.KIIINGJLEHG },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<GetElfRestaurantDataScRsp>(
            "GetElfRestaurantDataScRsp",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for GetElfRestaurantDataScRsp {
    const NAME: &'static str = "GetElfRestaurantDataScRsp";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                58 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.BNJBFPCDAFE)?;
                },
                66 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.OCGNOACLJAJ)?;
                },
                16 => {
                    self.retcode = is.read_uint32()?;
                },
                90 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.DCIDLIFMNLA)?;
                },
                26 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.LIBKPMMGGLJ)?;
                },
                98 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.KIIINGJLEHG)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.BNJBFPCDAFE.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.OCGNOACLJAJ.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if self.retcode != 0 {
            my_size += ::protobuf::rt::uint32_size(2, self.retcode);
        }
        if let Some(v) = self.DCIDLIFMNLA.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.LIBKPMMGGLJ.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.KIIINGJLEHG.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.BNJBFPCDAFE.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(7, v, os)?;
        }
        if let Some(v) = self.OCGNOACLJAJ.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(8, v, os)?;
        }
        if self.retcode != 0 {
            os.write_uint32(2, self.retcode)?;
        }
        if let Some(v) = self.DCIDLIFMNLA.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(11, v, os)?;
        }
        if let Some(v) = self.LIBKPMMGGLJ.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        }
        if let Some(v) = self.KIIINGJLEHG.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(12, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> GetElfRestaurantDataScRsp {
        GetElfRestaurantDataScRsp::new()
    }

    fn clear(&mut self) {
        self.BNJBFPCDAFE.clear();
        self.OCGNOACLJAJ.clear();
        self.retcode = 0;
        self.DCIDLIFMNLA.clear();
        self.LIBKPMMGGLJ.clear();
        self.KIIINGJLEHG.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static GetElfRestaurantDataScRsp {
        static instance: GetElfRestaurantDataScRsp = GetElfRestaurantDataScRsp {
            BNJBFPCDAFE: ::protobuf::MessageField::none(),
            OCGNOACLJAJ: ::protobuf::MessageField::none(),
            retcode: 0,
            DCIDLIFMNLA: ::protobuf::MessageField::none(),
            LIBKPMMGGLJ: ::protobuf::MessageField::none(),
            KIIINGJLEHG: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for GetElfRestaurantDataScRsp {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("GetElfRestaurantDataScRsp").unwrap()).clone()
    }
}

impl ::std::fmt::Display for GetElfRestaurantDataScRsp {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for GetElfRestaurantDataScRsp {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1fGetElfRestaurantDataScRsp.proto\x1a\x11AFOECDHJPII.proto\x1a\x11BB\
    CLLNPDIAH.proto\x1a\x11BCNJMGCEGAA.proto\x1a\x11MFLDHBJNEOO.proto\x1a\
    \x11NCPCAIKAJGD.proto\"\xa5\x02\n\x19GetElfRestaurantDataScRsp\x12.\n\
    \x0bBNJBFPCDAFE\x18\x07\x20\x01(\x0b2\x0c.BCNJMGCEGAAR\x0bBNJBFPCDAFE\
    \x12.\n\x0bOCGNOACLJAJ\x18\x08\x20\x01(\x0b2\x0c.NCPCAIKAJGDR\x0bOCGNOAC\
    LJAJ\x12\x18\n\x07retcode\x18\x02\x20\x01(\rR\x07retcode\x12.\n\x0bDCIDL\
    IFMNLA\x18\x0b\x20\x01(\x0b2\x0c.BBCLLNPDIAHR\x0bDCIDLIFMNLA\x12.\n\x0bL\
    IBKPMMGGLJ\x18\x03\x20\x01(\x0b2\x0c.AFOECDHJPIIR\x0bLIBKPMMGGLJ\x12.\n\
    \x0bKIIINGJLEHG\x18\x0c\x20\x01(\x0b2\x0c.MFLDHBJNEOOR\x0bKIIINGJLEHGb\
    \x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(5);
            deps.push(super::AFOECDHJPII::file_descriptor().clone());
            deps.push(super::BBCLLNPDIAH::file_descriptor().clone());
            deps.push(super::BCNJMGCEGAA::file_descriptor().clone());
            deps.push(super::MFLDHBJNEOO::file_descriptor().clone());
            deps.push(super::NCPCAIKAJGD::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(GetElfRestaurantDataScRsp::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
