// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `GetSystemDataRsp.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:GetSystemDataRsp)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct GetSystemDataRsp {
    // message fields
    // @@protoc_insertion_point(field:GetSystemDataRsp.FKOBFPNGDCG)
    pub FKOBFPNGDCG: ::std::vec::Vec<u32>,
    // @@protoc_insertion_point(field:GetSystemDataRsp.retcode)
    pub retcode: u32,
    // @@protoc_insertion_point(field:GetSystemDataRsp.DKCGALDKDFA)
    pub DKCGALDKDFA: ::protobuf::MessageField<super::DABNCEPBKMG::DABNCEPBKMG>,
    // @@protoc_insertion_point(field:GetSystemDataRsp.avatar_list)
    pub avatar_list: ::std::vec::Vec<super::DiceCombatAvatar::DiceCombatAvatar>,
    // @@protoc_insertion_point(field:GetSystemDataRsp.FAMFCIPLGON)
    pub FAMFCIPLGON: ::std::vec::Vec<super::INACEGAAALJ::INACEGAAALJ>,
    // @@protoc_insertion_point(field:GetSystemDataRsp.DAMDPNDCACK)
    pub DAMDPNDCACK: ::std::vec::Vec<u32>,
    // @@protoc_insertion_point(field:GetSystemDataRsp.JEBJGKACBKD)
    pub JEBJGKACBKD: u32,
    // special fields
    // @@protoc_insertion_point(special_field:GetSystemDataRsp.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a GetSystemDataRsp {
    fn default() -> &'a GetSystemDataRsp {
        <GetSystemDataRsp as ::protobuf::Message>::default_instance()
    }
}

impl GetSystemDataRsp {
    pub fn new() -> GetSystemDataRsp {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(7);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "FKOBFPNGDCG",
            |m: &GetSystemDataRsp| { &m.FKOBFPNGDCG },
            |m: &mut GetSystemDataRsp| { &mut m.FKOBFPNGDCG },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "retcode",
            |m: &GetSystemDataRsp| { &m.retcode },
            |m: &mut GetSystemDataRsp| { &mut m.retcode },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::DABNCEPBKMG::DABNCEPBKMG>(
            "DKCGALDKDFA",
            |m: &GetSystemDataRsp| { &m.DKCGALDKDFA },
            |m: &mut GetSystemDataRsp| { &mut m.DKCGALDKDFA },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "avatar_list",
            |m: &GetSystemDataRsp| { &m.avatar_list },
            |m: &mut GetSystemDataRsp| { &mut m.avatar_list },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "FAMFCIPLGON",
            |m: &GetSystemDataRsp| { &m.FAMFCIPLGON },
            |m: &mut GetSystemDataRsp| { &mut m.FAMFCIPLGON },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "DAMDPNDCACK",
            |m: &GetSystemDataRsp| { &m.DAMDPNDCACK },
            |m: &mut GetSystemDataRsp| { &mut m.DAMDPNDCACK },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "JEBJGKACBKD",
            |m: &GetSystemDataRsp| { &m.JEBJGKACBKD },
            |m: &mut GetSystemDataRsp| { &mut m.JEBJGKACBKD },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<GetSystemDataRsp>(
            "GetSystemDataRsp",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for GetSystemDataRsp {
    const NAME: &'static str = "GetSystemDataRsp";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                74 => {
                    is.read_repeated_packed_uint32_into(&mut self.FKOBFPNGDCG)?;
                },
                72 => {
                    self.FKOBFPNGDCG.push(is.read_uint32()?);
                },
                64 => {
                    self.retcode = is.read_uint32()?;
                },
                114 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.DKCGALDKDFA)?;
                },
                50 => {
                    self.avatar_list.push(is.read_message()?);
                },
                90 => {
                    self.FAMFCIPLGON.push(is.read_message()?);
                },
                26 => {
                    is.read_repeated_packed_uint32_into(&mut self.DAMDPNDCACK)?;
                },
                24 => {
                    self.DAMDPNDCACK.push(is.read_uint32()?);
                },
                104 => {
                    self.JEBJGKACBKD = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::vec_packed_uint32_size(9, &self.FKOBFPNGDCG);
        if self.retcode != 0 {
            my_size += ::protobuf::rt::uint32_size(8, self.retcode);
        }
        if let Some(v) = self.DKCGALDKDFA.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        for value in &self.avatar_list {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        for value in &self.FAMFCIPLGON {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::vec_packed_uint32_size(3, &self.DAMDPNDCACK);
        if self.JEBJGKACBKD != 0 {
            my_size += ::protobuf::rt::uint32_size(13, self.JEBJGKACBKD);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        os.write_repeated_packed_uint32(9, &self.FKOBFPNGDCG)?;
        if self.retcode != 0 {
            os.write_uint32(8, self.retcode)?;
        }
        if let Some(v) = self.DKCGALDKDFA.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(14, v, os)?;
        }
        for v in &self.avatar_list {
            ::protobuf::rt::write_message_field_with_cached_size(6, v, os)?;
        };
        for v in &self.FAMFCIPLGON {
            ::protobuf::rt::write_message_field_with_cached_size(11, v, os)?;
        };
        os.write_repeated_packed_uint32(3, &self.DAMDPNDCACK)?;
        if self.JEBJGKACBKD != 0 {
            os.write_uint32(13, self.JEBJGKACBKD)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> GetSystemDataRsp {
        GetSystemDataRsp::new()
    }

    fn clear(&mut self) {
        self.FKOBFPNGDCG.clear();
        self.retcode = 0;
        self.DKCGALDKDFA.clear();
        self.avatar_list.clear();
        self.FAMFCIPLGON.clear();
        self.DAMDPNDCACK.clear();
        self.JEBJGKACBKD = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static GetSystemDataRsp {
        static instance: GetSystemDataRsp = GetSystemDataRsp {
            FKOBFPNGDCG: ::std::vec::Vec::new(),
            retcode: 0,
            DKCGALDKDFA: ::protobuf::MessageField::none(),
            avatar_list: ::std::vec::Vec::new(),
            FAMFCIPLGON: ::std::vec::Vec::new(),
            DAMDPNDCACK: ::std::vec::Vec::new(),
            JEBJGKACBKD: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for GetSystemDataRsp {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("GetSystemDataRsp").unwrap()).clone()
    }
}

impl ::std::fmt::Display for GetSystemDataRsp {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for GetSystemDataRsp {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x16GetSystemDataRsp.proto\x1a\x11DABNCEPBKMG.proto\x1a\x16DiceCombatA\
    vatar.proto\x1a\x11INACEGAAALJ.proto\"\xa6\x02\n\x10GetSystemDataRsp\x12\
    \x20\n\x0bFKOBFPNGDCG\x18\t\x20\x03(\rR\x0bFKOBFPNGDCG\x12\x18\n\x07retc\
    ode\x18\x08\x20\x01(\rR\x07retcode\x12.\n\x0bDKCGALDKDFA\x18\x0e\x20\x01\
    (\x0b2\x0c.DABNCEPBKMGR\x0bDKCGALDKDFA\x122\n\x0bavatar_list\x18\x06\x20\
    \x03(\x0b2\x11.DiceCombatAvatarR\navatarList\x12.\n\x0bFAMFCIPLGON\x18\
    \x0b\x20\x03(\x0b2\x0c.INACEGAAALJR\x0bFAMFCIPLGON\x12\x20\n\x0bDAMDPNDC\
    ACK\x18\x03\x20\x03(\rR\x0bDAMDPNDCACK\x12\x20\n\x0bJEBJGKACBKD\x18\r\
    \x20\x01(\rR\x0bJEBJGKACBKDb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(3);
            deps.push(super::DABNCEPBKMG::file_descriptor().clone());
            deps.push(super::DiceCombatAvatar::file_descriptor().clone());
            deps.push(super::INACEGAAALJ::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(GetSystemDataRsp::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
