// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `GNKDJFAGCBC.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:GNKDJFAGCBC)
pub enum GNKDJFAGCBC {
    // @@protoc_insertion_point(enum_value:GNKDJFAGCBC.GNKDJFAGCBC_KGPAHOCDGIN)
    GNKDJFAGCBC_KGPAHOCDGIN = 0,
    // @@protoc_insertion_point(enum_value:GNKDJFAGCBC.GNKDJFAGCBC_LPOOLDIFEDB)
    GNKDJFAGCBC_LPOOLDIFEDB = 1,
    // @@protoc_insertion_point(enum_value:GNKDJFAGCBC.GNKDJFAGCBC_FBKFJENNEBD)
    GNKDJFAGCBC_FBKFJENNEBD = 2,
    // @@protoc_insertion_point(enum_value:GNKDJFAGCBC.GNKDJFAGCBC_LCLAEBGJPED)
    GNKDJFAGCBC_LCLAEBGJPED = 3,
    // @@protoc_insertion_point(enum_value:GNKDJFAGCBC.GNKDJFAGCBC_CFEDNIAIJPP)
    GNKDJFAGCBC_CFEDNIAIJPP = 4,
    // @@protoc_insertion_point(enum_value:GNKDJFAGCBC.GNKDJFAGCBC_DNBLKAPCECA)
    GNKDJFAGCBC_DNBLKAPCECA = 5,
    // @@protoc_insertion_point(enum_value:GNKDJFAGCBC.GNKDJFAGCBC_GDKEHBCDABJ)
    GNKDJFAGCBC_GDKEHBCDABJ = 6,
}

impl ::protobuf::Enum for GNKDJFAGCBC {
    const NAME: &'static str = "GNKDJFAGCBC";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<GNKDJFAGCBC> {
        match value {
            0 => ::std::option::Option::Some(GNKDJFAGCBC::GNKDJFAGCBC_KGPAHOCDGIN),
            1 => ::std::option::Option::Some(GNKDJFAGCBC::GNKDJFAGCBC_LPOOLDIFEDB),
            2 => ::std::option::Option::Some(GNKDJFAGCBC::GNKDJFAGCBC_FBKFJENNEBD),
            3 => ::std::option::Option::Some(GNKDJFAGCBC::GNKDJFAGCBC_LCLAEBGJPED),
            4 => ::std::option::Option::Some(GNKDJFAGCBC::GNKDJFAGCBC_CFEDNIAIJPP),
            5 => ::std::option::Option::Some(GNKDJFAGCBC::GNKDJFAGCBC_DNBLKAPCECA),
            6 => ::std::option::Option::Some(GNKDJFAGCBC::GNKDJFAGCBC_GDKEHBCDABJ),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<GNKDJFAGCBC> {
        match str {
            "GNKDJFAGCBC_KGPAHOCDGIN" => ::std::option::Option::Some(GNKDJFAGCBC::GNKDJFAGCBC_KGPAHOCDGIN),
            "GNKDJFAGCBC_LPOOLDIFEDB" => ::std::option::Option::Some(GNKDJFAGCBC::GNKDJFAGCBC_LPOOLDIFEDB),
            "GNKDJFAGCBC_FBKFJENNEBD" => ::std::option::Option::Some(GNKDJFAGCBC::GNKDJFAGCBC_FBKFJENNEBD),
            "GNKDJFAGCBC_LCLAEBGJPED" => ::std::option::Option::Some(GNKDJFAGCBC::GNKDJFAGCBC_LCLAEBGJPED),
            "GNKDJFAGCBC_CFEDNIAIJPP" => ::std::option::Option::Some(GNKDJFAGCBC::GNKDJFAGCBC_CFEDNIAIJPP),
            "GNKDJFAGCBC_DNBLKAPCECA" => ::std::option::Option::Some(GNKDJFAGCBC::GNKDJFAGCBC_DNBLKAPCECA),
            "GNKDJFAGCBC_GDKEHBCDABJ" => ::std::option::Option::Some(GNKDJFAGCBC::GNKDJFAGCBC_GDKEHBCDABJ),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [GNKDJFAGCBC] = &[
        GNKDJFAGCBC::GNKDJFAGCBC_KGPAHOCDGIN,
        GNKDJFAGCBC::GNKDJFAGCBC_LPOOLDIFEDB,
        GNKDJFAGCBC::GNKDJFAGCBC_FBKFJENNEBD,
        GNKDJFAGCBC::GNKDJFAGCBC_LCLAEBGJPED,
        GNKDJFAGCBC::GNKDJFAGCBC_CFEDNIAIJPP,
        GNKDJFAGCBC::GNKDJFAGCBC_DNBLKAPCECA,
        GNKDJFAGCBC::GNKDJFAGCBC_GDKEHBCDABJ,
    ];
}

impl ::protobuf::EnumFull for GNKDJFAGCBC {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("GNKDJFAGCBC").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for GNKDJFAGCBC {
    fn default() -> Self {
        GNKDJFAGCBC::GNKDJFAGCBC_KGPAHOCDGIN
    }
}

impl GNKDJFAGCBC {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<GNKDJFAGCBC>("GNKDJFAGCBC")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11GNKDJFAGCBC.proto*\xd8\x01\n\x0bGNKDJFAGCBC\x12\x1b\n\x17GNKDJFAGC\
    BC_KGPAHOCDGIN\x10\0\x12\x1b\n\x17GNKDJFAGCBC_LPOOLDIFEDB\x10\x01\x12\
    \x1b\n\x17GNKDJFAGCBC_FBKFJENNEBD\x10\x02\x12\x1b\n\x17GNKDJFAGCBC_LCLAE\
    BGJPED\x10\x03\x12\x1b\n\x17GNKDJFAGCBC_CFEDNIAIJPP\x10\x04\x12\x1b\n\
    \x17GNKDJFAGCBC_DNBLKAPCECA\x10\x05\x12\x1b\n\x17GNKDJFAGCBC_GDKEHBCDABJ\
    \x10\x06b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(GNKDJFAGCBC::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
