// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `IPLEKCNLEMG.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:IPLEKCNLEMG)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct IPLEKCNLEMG {
    // message fields
    // @@protoc_insertion_point(field:IPLEKCNLEMG.FIKFMPBHIHM)
    pub FIKFMPBHIHM: u32,
    // @@protoc_insertion_point(field:IPLEKCNLEMG.KPOOFBPGMLN)
    pub KPOOFBPGMLN: u32,
    // @@protoc_insertion_point(field:IPLEKCNLEMG.IBOPJGBFCJI)
    pub IBOPJGBFCJI: u32,
    // @@protoc_insertion_point(field:IPLEKCNLEMG.PNHOEDHBGNM)
    pub PNHOEDHBGNM: u32,
    // special fields
    // @@protoc_insertion_point(special_field:IPLEKCNLEMG.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a IPLEKCNLEMG {
    fn default() -> &'a IPLEKCNLEMG {
        <IPLEKCNLEMG as ::protobuf::Message>::default_instance()
    }
}

impl IPLEKCNLEMG {
    pub fn new() -> IPLEKCNLEMG {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "FIKFMPBHIHM",
            |m: &IPLEKCNLEMG| { &m.FIKFMPBHIHM },
            |m: &mut IPLEKCNLEMG| { &mut m.FIKFMPBHIHM },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "KPOOFBPGMLN",
            |m: &IPLEKCNLEMG| { &m.KPOOFBPGMLN },
            |m: &mut IPLEKCNLEMG| { &mut m.KPOOFBPGMLN },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "IBOPJGBFCJI",
            |m: &IPLEKCNLEMG| { &m.IBOPJGBFCJI },
            |m: &mut IPLEKCNLEMG| { &mut m.IBOPJGBFCJI },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "PNHOEDHBGNM",
            |m: &IPLEKCNLEMG| { &m.PNHOEDHBGNM },
            |m: &mut IPLEKCNLEMG| { &mut m.PNHOEDHBGNM },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<IPLEKCNLEMG>(
            "IPLEKCNLEMG",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for IPLEKCNLEMG {
    const NAME: &'static str = "IPLEKCNLEMG";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                72 => {
                    self.FIKFMPBHIHM = is.read_uint32()?;
                },
                8 => {
                    self.KPOOFBPGMLN = is.read_uint32()?;
                },
                32 => {
                    self.IBOPJGBFCJI = is.read_uint32()?;
                },
                40 => {
                    self.PNHOEDHBGNM = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.FIKFMPBHIHM != 0 {
            my_size += ::protobuf::rt::uint32_size(9, self.FIKFMPBHIHM);
        }
        if self.KPOOFBPGMLN != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.KPOOFBPGMLN);
        }
        if self.IBOPJGBFCJI != 0 {
            my_size += ::protobuf::rt::uint32_size(4, self.IBOPJGBFCJI);
        }
        if self.PNHOEDHBGNM != 0 {
            my_size += ::protobuf::rt::uint32_size(5, self.PNHOEDHBGNM);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.FIKFMPBHIHM != 0 {
            os.write_uint32(9, self.FIKFMPBHIHM)?;
        }
        if self.KPOOFBPGMLN != 0 {
            os.write_uint32(1, self.KPOOFBPGMLN)?;
        }
        if self.IBOPJGBFCJI != 0 {
            os.write_uint32(4, self.IBOPJGBFCJI)?;
        }
        if self.PNHOEDHBGNM != 0 {
            os.write_uint32(5, self.PNHOEDHBGNM)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> IPLEKCNLEMG {
        IPLEKCNLEMG::new()
    }

    fn clear(&mut self) {
        self.FIKFMPBHIHM = 0;
        self.KPOOFBPGMLN = 0;
        self.IBOPJGBFCJI = 0;
        self.PNHOEDHBGNM = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static IPLEKCNLEMG {
        static instance: IPLEKCNLEMG = IPLEKCNLEMG {
            FIKFMPBHIHM: 0,
            KPOOFBPGMLN: 0,
            IBOPJGBFCJI: 0,
            PNHOEDHBGNM: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for IPLEKCNLEMG {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("IPLEKCNLEMG").unwrap()).clone()
    }
}

impl ::std::fmt::Display for IPLEKCNLEMG {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for IPLEKCNLEMG {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11IPLEKCNLEMG.proto\"\x95\x01\n\x0bIPLEKCNLEMG\x12\x20\n\x0bFIKFMPBH\
    IHM\x18\t\x20\x01(\rR\x0bFIKFMPBHIHM\x12\x20\n\x0bKPOOFBPGMLN\x18\x01\
    \x20\x01(\rR\x0bKPOOFBPGMLN\x12\x20\n\x0bIBOPJGBFCJI\x18\x04\x20\x01(\rR\
    \x0bIBOPJGBFCJI\x12\x20\n\x0bPNHOEDHBGNM\x18\x05\x20\x01(\rR\x0bPNHOEDHB\
    GNMb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(IPLEKCNLEMG::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
