// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `KINHLMIMDIG.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:KINHLMIMDIG)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct KINHLMIMDIG {
    // message fields
    // @@protoc_insertion_point(field:KINHLMIMDIG.KHCPCKIBNKB)
    pub KHCPCKIBNKB: i32,
    // @@protoc_insertion_point(field:KINHLMIMDIG.item_id)
    pub item_id: u32,
    // @@protoc_insertion_point(field:KINHLMIMDIG.MGNGPGPPIAA)
    pub MGNGPGPPIAA: u32,
    // @@protoc_insertion_point(field:KINHLMIMDIG.total_damage)
    pub total_damage: i32,
    // @@protoc_insertion_point(field:KINHLMIMDIG.PHLEIBBBDDN)
    pub PHLEIBBBDDN: i32,
    // special fields
    // @@protoc_insertion_point(special_field:KINHLMIMDIG.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a KINHLMIMDIG {
    fn default() -> &'a KINHLMIMDIG {
        <KINHLMIMDIG as ::protobuf::Message>::default_instance()
    }
}

impl KINHLMIMDIG {
    pub fn new() -> KINHLMIMDIG {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "KHCPCKIBNKB",
            |m: &KINHLMIMDIG| { &m.KHCPCKIBNKB },
            |m: &mut KINHLMIMDIG| { &mut m.KHCPCKIBNKB },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "item_id",
            |m: &KINHLMIMDIG| { &m.item_id },
            |m: &mut KINHLMIMDIG| { &mut m.item_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "MGNGPGPPIAA",
            |m: &KINHLMIMDIG| { &m.MGNGPGPPIAA },
            |m: &mut KINHLMIMDIG| { &mut m.MGNGPGPPIAA },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "total_damage",
            |m: &KINHLMIMDIG| { &m.total_damage },
            |m: &mut KINHLMIMDIG| { &mut m.total_damage },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "PHLEIBBBDDN",
            |m: &KINHLMIMDIG| { &m.PHLEIBBBDDN },
            |m: &mut KINHLMIMDIG| { &mut m.PHLEIBBBDDN },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<KINHLMIMDIG>(
            "KINHLMIMDIG",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for KINHLMIMDIG {
    const NAME: &'static str = "KINHLMIMDIG";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                64 => {
                    self.KHCPCKIBNKB = is.read_int32()?;
                },
                120 => {
                    self.item_id = is.read_uint32()?;
                },
                72 => {
                    self.MGNGPGPPIAA = is.read_uint32()?;
                },
                96 => {
                    self.total_damage = is.read_int32()?;
                },
                104 => {
                    self.PHLEIBBBDDN = is.read_int32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.KHCPCKIBNKB != 0 {
            my_size += ::protobuf::rt::int32_size(8, self.KHCPCKIBNKB);
        }
        if self.item_id != 0 {
            my_size += ::protobuf::rt::uint32_size(15, self.item_id);
        }
        if self.MGNGPGPPIAA != 0 {
            my_size += ::protobuf::rt::uint32_size(9, self.MGNGPGPPIAA);
        }
        if self.total_damage != 0 {
            my_size += ::protobuf::rt::int32_size(12, self.total_damage);
        }
        if self.PHLEIBBBDDN != 0 {
            my_size += ::protobuf::rt::int32_size(13, self.PHLEIBBBDDN);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.KHCPCKIBNKB != 0 {
            os.write_int32(8, self.KHCPCKIBNKB)?;
        }
        if self.item_id != 0 {
            os.write_uint32(15, self.item_id)?;
        }
        if self.MGNGPGPPIAA != 0 {
            os.write_uint32(9, self.MGNGPGPPIAA)?;
        }
        if self.total_damage != 0 {
            os.write_int32(12, self.total_damage)?;
        }
        if self.PHLEIBBBDDN != 0 {
            os.write_int32(13, self.PHLEIBBBDDN)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> KINHLMIMDIG {
        KINHLMIMDIG::new()
    }

    fn clear(&mut self) {
        self.KHCPCKIBNKB = 0;
        self.item_id = 0;
        self.MGNGPGPPIAA = 0;
        self.total_damage = 0;
        self.PHLEIBBBDDN = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static KINHLMIMDIG {
        static instance: KINHLMIMDIG = KINHLMIMDIG {
            KHCPCKIBNKB: 0,
            item_id: 0,
            MGNGPGPPIAA: 0,
            total_damage: 0,
            PHLEIBBBDDN: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for KINHLMIMDIG {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("KINHLMIMDIG").unwrap()).clone()
    }
}

impl ::std::fmt::Display for KINHLMIMDIG {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for KINHLMIMDIG {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11KINHLMIMDIG.proto\"\xaf\x01\n\x0bKINHLMIMDIG\x12\x20\n\x0bKHCPCKIB\
    NKB\x18\x08\x20\x01(\x05R\x0bKHCPCKIBNKB\x12\x17\n\x07item_id\x18\x0f\
    \x20\x01(\rR\x06itemId\x12\x20\n\x0bMGNGPGPPIAA\x18\t\x20\x01(\rR\x0bMGN\
    GPGPPIAA\x12!\n\x0ctotal_damage\x18\x0c\x20\x01(\x05R\x0btotalDamage\x12\
    \x20\n\x0bPHLEIBBBDDN\x18\r\x20\x01(\x05R\x0bPHLEIBBBDDNb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(KINHLMIMDIG::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
