// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `KPBGMOCCMLA.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:KPBGMOCCMLA)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct KPBGMOCCMLA {
    // message fields
    // @@protoc_insertion_point(field:KPBGMOCCMLA.EOPNFAAPPIO)
    pub EOPNFAAPPIO: ::std::vec::Vec<super::ILDFFLCOFCN::ILDFFLCOFCN>,
    // @@protoc_insertion_point(field:KPBGMOCCMLA.NLBGEBPPDJO)
    pub NLBGEBPPDJO: u32,
    // @@protoc_insertion_point(field:KPBGMOCCMLA.JBOCOPNEJLB)
    pub JBOCOPNEJLB: ::std::vec::Vec<super::PGNAFAEAIDN::PGNAFAEAIDN>,
    // @@protoc_insertion_point(field:KPBGMOCCMLA.MGIHLOHMOJC)
    pub MGIHLOHMOJC: u32,
    // @@protoc_insertion_point(field:KPBGMOCCMLA.MGMPPOJIGBC)
    pub MGMPPOJIGBC: ::std::vec::Vec<super::AOMPLKEILJD::AOMPLKEILJD>,
    // @@protoc_insertion_point(field:KPBGMOCCMLA.buff_list)
    pub buff_list: ::std::vec::Vec<super::IKJOFCNBMKF::IKJOFCNBMKF>,
    // @@protoc_insertion_point(field:KPBGMOCCMLA.target_side)
    pub target_side: u32,
    // @@protoc_insertion_point(field:KPBGMOCCMLA.ADMJNJKCDFN)
    pub ADMJNJKCDFN: bool,
    // @@protoc_insertion_point(field:KPBGMOCCMLA.OPDAJBALNEK)
    pub OPDAJBALNEK: bool,
    // @@protoc_insertion_point(field:KPBGMOCCMLA.AHAAPPCDLFF)
    pub AHAAPPCDLFF: u32,
    // @@protoc_insertion_point(field:KPBGMOCCMLA.avatar_list)
    pub avatar_list: ::std::vec::Vec<super::AOMPLKEILJD::AOMPLKEILJD>,
    // @@protoc_insertion_point(field:KPBGMOCCMLA.map_id)
    pub map_id: u32,
    // @@protoc_insertion_point(field:KPBGMOCCMLA.item_list)
    pub item_list: ::std::vec::Vec<super::HMKMGAGPAKA::HMKMGAGPAKA>,
    // @@protoc_insertion_point(field:KPBGMOCCMLA.NPHLEPECMAH)
    pub NPHLEPECMAH: u32,
    // @@protoc_insertion_point(field:KPBGMOCCMLA.DCKEEAKEOLC)
    pub DCKEEAKEOLC: u32,
    // @@protoc_insertion_point(field:KPBGMOCCMLA.IMBCJKHMOAB)
    pub IMBCJKHMOAB: ::std::vec::Vec<super::JCEEENOLDIF::JCEEENOLDIF>,
    // @@protoc_insertion_point(field:KPBGMOCCMLA.OJPCGMHCEBN)
    pub OJPCGMHCEBN: bool,
    // @@protoc_insertion_point(field:KPBGMOCCMLA.JDFDJACPCKC)
    pub JDFDJACPCKC: u32,
    // special fields
    // @@protoc_insertion_point(special_field:KPBGMOCCMLA.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a KPBGMOCCMLA {
    fn default() -> &'a KPBGMOCCMLA {
        <KPBGMOCCMLA as ::protobuf::Message>::default_instance()
    }
}

impl KPBGMOCCMLA {
    pub fn new() -> KPBGMOCCMLA {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(18);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "EOPNFAAPPIO",
            |m: &KPBGMOCCMLA| { &m.EOPNFAAPPIO },
            |m: &mut KPBGMOCCMLA| { &mut m.EOPNFAAPPIO },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "NLBGEBPPDJO",
            |m: &KPBGMOCCMLA| { &m.NLBGEBPPDJO },
            |m: &mut KPBGMOCCMLA| { &mut m.NLBGEBPPDJO },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "JBOCOPNEJLB",
            |m: &KPBGMOCCMLA| { &m.JBOCOPNEJLB },
            |m: &mut KPBGMOCCMLA| { &mut m.JBOCOPNEJLB },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "MGIHLOHMOJC",
            |m: &KPBGMOCCMLA| { &m.MGIHLOHMOJC },
            |m: &mut KPBGMOCCMLA| { &mut m.MGIHLOHMOJC },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "MGMPPOJIGBC",
            |m: &KPBGMOCCMLA| { &m.MGMPPOJIGBC },
            |m: &mut KPBGMOCCMLA| { &mut m.MGMPPOJIGBC },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "buff_list",
            |m: &KPBGMOCCMLA| { &m.buff_list },
            |m: &mut KPBGMOCCMLA| { &mut m.buff_list },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "target_side",
            |m: &KPBGMOCCMLA| { &m.target_side },
            |m: &mut KPBGMOCCMLA| { &mut m.target_side },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "ADMJNJKCDFN",
            |m: &KPBGMOCCMLA| { &m.ADMJNJKCDFN },
            |m: &mut KPBGMOCCMLA| { &mut m.ADMJNJKCDFN },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "OPDAJBALNEK",
            |m: &KPBGMOCCMLA| { &m.OPDAJBALNEK },
            |m: &mut KPBGMOCCMLA| { &mut m.OPDAJBALNEK },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "AHAAPPCDLFF",
            |m: &KPBGMOCCMLA| { &m.AHAAPPCDLFF },
            |m: &mut KPBGMOCCMLA| { &mut m.AHAAPPCDLFF },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "avatar_list",
            |m: &KPBGMOCCMLA| { &m.avatar_list },
            |m: &mut KPBGMOCCMLA| { &mut m.avatar_list },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "map_id",
            |m: &KPBGMOCCMLA| { &m.map_id },
            |m: &mut KPBGMOCCMLA| { &mut m.map_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "item_list",
            |m: &KPBGMOCCMLA| { &m.item_list },
            |m: &mut KPBGMOCCMLA| { &mut m.item_list },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "NPHLEPECMAH",
            |m: &KPBGMOCCMLA| { &m.NPHLEPECMAH },
            |m: &mut KPBGMOCCMLA| { &mut m.NPHLEPECMAH },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "DCKEEAKEOLC",
            |m: &KPBGMOCCMLA| { &m.DCKEEAKEOLC },
            |m: &mut KPBGMOCCMLA| { &mut m.DCKEEAKEOLC },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "IMBCJKHMOAB",
            |m: &KPBGMOCCMLA| { &m.IMBCJKHMOAB },
            |m: &mut KPBGMOCCMLA| { &mut m.IMBCJKHMOAB },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "OJPCGMHCEBN",
            |m: &KPBGMOCCMLA| { &m.OJPCGMHCEBN },
            |m: &mut KPBGMOCCMLA| { &mut m.OJPCGMHCEBN },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "JDFDJACPCKC",
            |m: &KPBGMOCCMLA| { &m.JDFDJACPCKC },
            |m: &mut KPBGMOCCMLA| { &mut m.JDFDJACPCKC },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<KPBGMOCCMLA>(
            "KPBGMOCCMLA",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for KPBGMOCCMLA {
    const NAME: &'static str = "KPBGMOCCMLA";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                1202 => {
                    self.EOPNFAAPPIO.push(is.read_message()?);
                },
                56 => {
                    self.NLBGEBPPDJO = is.read_uint32()?;
                },
                90 => {
                    self.JBOCOPNEJLB.push(is.read_message()?);
                },
                104 => {
                    self.MGIHLOHMOJC = is.read_uint32()?;
                },
                12002 => {
                    self.MGMPPOJIGBC.push(is.read_message()?);
                },
                8242 => {
                    self.buff_list.push(is.read_message()?);
                },
                80 => {
                    self.target_side = is.read_uint32()?;
                },
                16368 => {
                    self.ADMJNJKCDFN = is.read_bool()?;
                },
                3184 => {
                    self.OPDAJBALNEK = is.read_bool()?;
                },
                6952 => {
                    self.AHAAPPCDLFF = is.read_uint32()?;
                },
                754 => {
                    self.avatar_list.push(is.read_message()?);
                },
                32 => {
                    self.map_id = is.read_uint32()?;
                },
                8562 => {
                    self.item_list.push(is.read_message()?);
                },
                64 => {
                    self.NPHLEPECMAH = is.read_uint32()?;
                },
                24 => {
                    self.DCKEEAKEOLC = is.read_uint32()?;
                },
                10 => {
                    self.IMBCJKHMOAB.push(is.read_message()?);
                },
                6888 => {
                    self.OJPCGMHCEBN = is.read_bool()?;
                },
                112 => {
                    self.JDFDJACPCKC = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.EOPNFAAPPIO {
            let len = value.compute_size();
            my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if self.NLBGEBPPDJO != 0 {
            my_size += ::protobuf::rt::uint32_size(7, self.NLBGEBPPDJO);
        }
        for value in &self.JBOCOPNEJLB {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if self.MGIHLOHMOJC != 0 {
            my_size += ::protobuf::rt::uint32_size(13, self.MGIHLOHMOJC);
        }
        for value in &self.MGMPPOJIGBC {
            let len = value.compute_size();
            my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        for value in &self.buff_list {
            let len = value.compute_size();
            my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if self.target_side != 0 {
            my_size += ::protobuf::rt::uint32_size(10, self.target_side);
        }
        if self.ADMJNJKCDFN != false {
            my_size += 2 + 1;
        }
        if self.OPDAJBALNEK != false {
            my_size += 2 + 1;
        }
        if self.AHAAPPCDLFF != 0 {
            my_size += ::protobuf::rt::uint32_size(869, self.AHAAPPCDLFF);
        }
        for value in &self.avatar_list {
            let len = value.compute_size();
            my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if self.map_id != 0 {
            my_size += ::protobuf::rt::uint32_size(4, self.map_id);
        }
        for value in &self.item_list {
            let len = value.compute_size();
            my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if self.NPHLEPECMAH != 0 {
            my_size += ::protobuf::rt::uint32_size(8, self.NPHLEPECMAH);
        }
        if self.DCKEEAKEOLC != 0 {
            my_size += ::protobuf::rt::uint32_size(3, self.DCKEEAKEOLC);
        }
        for value in &self.IMBCJKHMOAB {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if self.OJPCGMHCEBN != false {
            my_size += 2 + 1;
        }
        if self.JDFDJACPCKC != 0 {
            my_size += ::protobuf::rt::uint32_size(14, self.JDFDJACPCKC);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.EOPNFAAPPIO {
            ::protobuf::rt::write_message_field_with_cached_size(150, v, os)?;
        };
        if self.NLBGEBPPDJO != 0 {
            os.write_uint32(7, self.NLBGEBPPDJO)?;
        }
        for v in &self.JBOCOPNEJLB {
            ::protobuf::rt::write_message_field_with_cached_size(11, v, os)?;
        };
        if self.MGIHLOHMOJC != 0 {
            os.write_uint32(13, self.MGIHLOHMOJC)?;
        }
        for v in &self.MGMPPOJIGBC {
            ::protobuf::rt::write_message_field_with_cached_size(1500, v, os)?;
        };
        for v in &self.buff_list {
            ::protobuf::rt::write_message_field_with_cached_size(1030, v, os)?;
        };
        if self.target_side != 0 {
            os.write_uint32(10, self.target_side)?;
        }
        if self.ADMJNJKCDFN != false {
            os.write_bool(2046, self.ADMJNJKCDFN)?;
        }
        if self.OPDAJBALNEK != false {
            os.write_bool(398, self.OPDAJBALNEK)?;
        }
        if self.AHAAPPCDLFF != 0 {
            os.write_uint32(869, self.AHAAPPCDLFF)?;
        }
        for v in &self.avatar_list {
            ::protobuf::rt::write_message_field_with_cached_size(94, v, os)?;
        };
        if self.map_id != 0 {
            os.write_uint32(4, self.map_id)?;
        }
        for v in &self.item_list {
            ::protobuf::rt::write_message_field_with_cached_size(1070, v, os)?;
        };
        if self.NPHLEPECMAH != 0 {
            os.write_uint32(8, self.NPHLEPECMAH)?;
        }
        if self.DCKEEAKEOLC != 0 {
            os.write_uint32(3, self.DCKEEAKEOLC)?;
        }
        for v in &self.IMBCJKHMOAB {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        if self.OJPCGMHCEBN != false {
            os.write_bool(861, self.OJPCGMHCEBN)?;
        }
        if self.JDFDJACPCKC != 0 {
            os.write_uint32(14, self.JDFDJACPCKC)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> KPBGMOCCMLA {
        KPBGMOCCMLA::new()
    }

    fn clear(&mut self) {
        self.EOPNFAAPPIO.clear();
        self.NLBGEBPPDJO = 0;
        self.JBOCOPNEJLB.clear();
        self.MGIHLOHMOJC = 0;
        self.MGMPPOJIGBC.clear();
        self.buff_list.clear();
        self.target_side = 0;
        self.ADMJNJKCDFN = false;
        self.OPDAJBALNEK = false;
        self.AHAAPPCDLFF = 0;
        self.avatar_list.clear();
        self.map_id = 0;
        self.item_list.clear();
        self.NPHLEPECMAH = 0;
        self.DCKEEAKEOLC = 0;
        self.IMBCJKHMOAB.clear();
        self.OJPCGMHCEBN = false;
        self.JDFDJACPCKC = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static KPBGMOCCMLA {
        static instance: KPBGMOCCMLA = KPBGMOCCMLA {
            EOPNFAAPPIO: ::std::vec::Vec::new(),
            NLBGEBPPDJO: 0,
            JBOCOPNEJLB: ::std::vec::Vec::new(),
            MGIHLOHMOJC: 0,
            MGMPPOJIGBC: ::std::vec::Vec::new(),
            buff_list: ::std::vec::Vec::new(),
            target_side: 0,
            ADMJNJKCDFN: false,
            OPDAJBALNEK: false,
            AHAAPPCDLFF: 0,
            avatar_list: ::std::vec::Vec::new(),
            map_id: 0,
            item_list: ::std::vec::Vec::new(),
            NPHLEPECMAH: 0,
            DCKEEAKEOLC: 0,
            IMBCJKHMOAB: ::std::vec::Vec::new(),
            OJPCGMHCEBN: false,
            JDFDJACPCKC: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for KPBGMOCCMLA {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("KPBGMOCCMLA").unwrap()).clone()
    }
}

impl ::std::fmt::Display for KPBGMOCCMLA {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for KPBGMOCCMLA {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11KPBGMOCCMLA.proto\x1a\x11AOMPLKEILJD.proto\x1a\x11HMKMGAGPAKA.prot\
    o\x1a\x11IKJOFCNBMKF.proto\x1a\x11ILDFFLCOFCN.proto\x1a\x11JCEEENOLDIF.p\
    roto\x1a\x11PGNAFAEAIDN.proto\"\xc4\x05\n\x0bKPBGMOCCMLA\x12/\n\x0bEOPNF\
    AAPPIO\x18\x96\x01\x20\x03(\x0b2\x0c.ILDFFLCOFCNR\x0bEOPNFAAPPIO\x12\x20\
    \n\x0bNLBGEBPPDJO\x18\x07\x20\x01(\rR\x0bNLBGEBPPDJO\x12.\n\x0bJBOCOPNEJ\
    LB\x18\x0b\x20\x03(\x0b2\x0c.PGNAFAEAIDNR\x0bJBOCOPNEJLB\x12\x20\n\x0bMG\
    IHLOHMOJC\x18\r\x20\x01(\rR\x0bMGIHLOHMOJC\x12/\n\x0bMGMPPOJIGBC\x18\xdc\
    \x0b\x20\x03(\x0b2\x0c.AOMPLKEILJDR\x0bMGMPPOJIGBC\x12*\n\tbuff_list\x18\
    \x86\x08\x20\x03(\x0b2\x0c.IKJOFCNBMKFR\x08buffList\x12\x1f\n\x0btarget_\
    side\x18\n\x20\x01(\rR\ntargetSide\x12!\n\x0bADMJNJKCDFN\x18\xfe\x0f\x20\
    \x01(\x08R\x0bADMJNJKCDFN\x12!\n\x0bOPDAJBALNEK\x18\x8e\x03\x20\x01(\x08\
    R\x0bOPDAJBALNEK\x12!\n\x0bAHAAPPCDLFF\x18\xe5\x06\x20\x01(\rR\x0bAHAAPP\
    CDLFF\x12-\n\x0bavatar_list\x18^\x20\x03(\x0b2\x0c.AOMPLKEILJDR\navatarL\
    ist\x12\x15\n\x06map_id\x18\x04\x20\x01(\rR\x05mapId\x12*\n\titem_list\
    \x18\xae\x08\x20\x03(\x0b2\x0c.HMKMGAGPAKAR\x08itemList\x12\x20\n\x0bNPH\
    LEPECMAH\x18\x08\x20\x01(\rR\x0bNPHLEPECMAH\x12\x20\n\x0bDCKEEAKEOLC\x18\
    \x03\x20\x01(\rR\x0bDCKEEAKEOLC\x12.\n\x0bIMBCJKHMOAB\x18\x01\x20\x03(\
    \x0b2\x0c.JCEEENOLDIFR\x0bIMBCJKHMOAB\x12!\n\x0bOJPCGMHCEBN\x18\xdd\x06\
    \x20\x01(\x08R\x0bOJPCGMHCEBN\x12\x20\n\x0bJDFDJACPCKC\x18\x0e\x20\x01(\
    \rR\x0bJDFDJACPCKCb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(6);
            deps.push(super::AOMPLKEILJD::file_descriptor().clone());
            deps.push(super::HMKMGAGPAKA::file_descriptor().clone());
            deps.push(super::IKJOFCNBMKF::file_descriptor().clone());
            deps.push(super::ILDFFLCOFCN::file_descriptor().clone());
            deps.push(super::JCEEENOLDIF::file_descriptor().clone());
            deps.push(super::PGNAFAEAIDN::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(KPBGMOCCMLA::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
