// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `LMHFOFIEIMN.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:LMHFOFIEIMN)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct LMHFOFIEIMN {
    // message fields
    // @@protoc_insertion_point(field:LMHFOFIEIMN.OOPOADNHABK)
    pub OOPOADNHABK: u32,
    // @@protoc_insertion_point(field:LMHFOFIEIMN.NJMONGKLJJC)
    pub NJMONGKLJJC: i64,
    // @@protoc_insertion_point(field:LMHFOFIEIMN.dice_slot_id)
    pub dice_slot_id: u32,
    // special fields
    // @@protoc_insertion_point(special_field:LMHFOFIEIMN.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a LMHFOFIEIMN {
    fn default() -> &'a LMHFOFIEIMN {
        <LMHFOFIEIMN as ::protobuf::Message>::default_instance()
    }
}

impl LMHFOFIEIMN {
    pub fn new() -> LMHFOFIEIMN {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "OOPOADNHABK",
            |m: &LMHFOFIEIMN| { &m.OOPOADNHABK },
            |m: &mut LMHFOFIEIMN| { &mut m.OOPOADNHABK },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "NJMONGKLJJC",
            |m: &LMHFOFIEIMN| { &m.NJMONGKLJJC },
            |m: &mut LMHFOFIEIMN| { &mut m.NJMONGKLJJC },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "dice_slot_id",
            |m: &LMHFOFIEIMN| { &m.dice_slot_id },
            |m: &mut LMHFOFIEIMN| { &mut m.dice_slot_id },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<LMHFOFIEIMN>(
            "LMHFOFIEIMN",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for LMHFOFIEIMN {
    const NAME: &'static str = "LMHFOFIEIMN";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                40 => {
                    self.OOPOADNHABK = is.read_uint32()?;
                },
                120 => {
                    self.NJMONGKLJJC = is.read_int64()?;
                },
                88 => {
                    self.dice_slot_id = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.OOPOADNHABK != 0 {
            my_size += ::protobuf::rt::uint32_size(5, self.OOPOADNHABK);
        }
        if self.NJMONGKLJJC != 0 {
            my_size += ::protobuf::rt::int64_size(15, self.NJMONGKLJJC);
        }
        if self.dice_slot_id != 0 {
            my_size += ::protobuf::rt::uint32_size(11, self.dice_slot_id);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.OOPOADNHABK != 0 {
            os.write_uint32(5, self.OOPOADNHABK)?;
        }
        if self.NJMONGKLJJC != 0 {
            os.write_int64(15, self.NJMONGKLJJC)?;
        }
        if self.dice_slot_id != 0 {
            os.write_uint32(11, self.dice_slot_id)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> LMHFOFIEIMN {
        LMHFOFIEIMN::new()
    }

    fn clear(&mut self) {
        self.OOPOADNHABK = 0;
        self.NJMONGKLJJC = 0;
        self.dice_slot_id = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static LMHFOFIEIMN {
        static instance: LMHFOFIEIMN = LMHFOFIEIMN {
            OOPOADNHABK: 0,
            NJMONGKLJJC: 0,
            dice_slot_id: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for LMHFOFIEIMN {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("LMHFOFIEIMN").unwrap()).clone()
    }
}

impl ::std::fmt::Display for LMHFOFIEIMN {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for LMHFOFIEIMN {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11LMHFOFIEIMN.proto\"s\n\x0bLMHFOFIEIMN\x12\x20\n\x0bOOPOADNHABK\x18\
    \x05\x20\x01(\rR\x0bOOPOADNHABK\x12\x20\n\x0bNJMONGKLJJC\x18\x0f\x20\x01\
    (\x03R\x0bNJMONGKLJJC\x12\x20\n\x0cdice_slot_id\x18\x0b\x20\x01(\rR\ndic\
    eSlotIdb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(LMHFOFIEIMN::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
