// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `MCPPIEJEBEF.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:MCPPIEJEBEF)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct MCPPIEJEBEF {
    // message fields
    // @@protoc_insertion_point(field:MCPPIEJEBEF.LEKGBMCOJDB)
    pub LEKGBMCOJDB: ::protobuf::MessageField<super::NKLAFFLJCHG::NKLAFFLJCHG>,
    // @@protoc_insertion_point(field:MCPPIEJEBEF.KBHPIPFKPAC)
    pub KBHPIPFKPAC: ::std::vec::Vec<super::BHFONEFGGAG::BHFONEFGGAG>,
    // @@protoc_insertion_point(field:MCPPIEJEBEF.HAJPKJOCBCL)
    pub HAJPKJOCBCL: bool,
    // special fields
    // @@protoc_insertion_point(special_field:MCPPIEJEBEF.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a MCPPIEJEBEF {
    fn default() -> &'a MCPPIEJEBEF {
        <MCPPIEJEBEF as ::protobuf::Message>::default_instance()
    }
}

impl MCPPIEJEBEF {
    pub fn new() -> MCPPIEJEBEF {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::NKLAFFLJCHG::NKLAFFLJCHG>(
            "LEKGBMCOJDB",
            |m: &MCPPIEJEBEF| { &m.LEKGBMCOJDB },
            |m: &mut MCPPIEJEBEF| { &mut m.LEKGBMCOJDB },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "KBHPIPFKPAC",
            |m: &MCPPIEJEBEF| { &m.KBHPIPFKPAC },
            |m: &mut MCPPIEJEBEF| { &mut m.KBHPIPFKPAC },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "HAJPKJOCBCL",
            |m: &MCPPIEJEBEF| { &m.HAJPKJOCBCL },
            |m: &mut MCPPIEJEBEF| { &mut m.HAJPKJOCBCL },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<MCPPIEJEBEF>(
            "MCPPIEJEBEF",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for MCPPIEJEBEF {
    const NAME: &'static str = "MCPPIEJEBEF";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.LEKGBMCOJDB)?;
                },
                18 => {
                    self.KBHPIPFKPAC.push(is.read_message()?);
                },
                24 => {
                    self.HAJPKJOCBCL = is.read_bool()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.LEKGBMCOJDB.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        for value in &self.KBHPIPFKPAC {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if self.HAJPKJOCBCL != false {
            my_size += 1 + 1;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.LEKGBMCOJDB.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        for v in &self.KBHPIPFKPAC {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        if self.HAJPKJOCBCL != false {
            os.write_bool(3, self.HAJPKJOCBCL)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> MCPPIEJEBEF {
        MCPPIEJEBEF::new()
    }

    fn clear(&mut self) {
        self.LEKGBMCOJDB.clear();
        self.KBHPIPFKPAC.clear();
        self.HAJPKJOCBCL = false;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static MCPPIEJEBEF {
        static instance: MCPPIEJEBEF = MCPPIEJEBEF {
            LEKGBMCOJDB: ::protobuf::MessageField::none(),
            KBHPIPFKPAC: ::std::vec::Vec::new(),
            HAJPKJOCBCL: false,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for MCPPIEJEBEF {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("MCPPIEJEBEF").unwrap()).clone()
    }
}

impl ::std::fmt::Display for MCPPIEJEBEF {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for MCPPIEJEBEF {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11MCPPIEJEBEF.proto\x1a\x11BHFONEFGGAG.proto\x1a\x11NKLAFFLJCHG.prot\
    o\"\x8f\x01\n\x0bMCPPIEJEBEF\x12.\n\x0bLEKGBMCOJDB\x18\x01\x20\x01(\x0b2\
    \x0c.NKLAFFLJCHGR\x0bLEKGBMCOJDB\x12.\n\x0bKBHPIPFKPAC\x18\x02\x20\x03(\
    \x0b2\x0c.BHFONEFGGAGR\x0bKBHPIPFKPAC\x12\x20\n\x0bHAJPKJOCBCL\x18\x03\
    \x20\x01(\x08R\x0bHAJPKJOCBCLb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(2);
            deps.push(super::BHFONEFGGAG::file_descriptor().clone());
            deps.push(super::NKLAFFLJCHG::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(MCPPIEJEBEF::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
