// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `MHANIEBKGHH.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:MHANIEBKGHH)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct MHANIEBKGHH {
    // message fields
    // @@protoc_insertion_point(field:MHANIEBKGHH.EKCPIKGLIJI)
    pub EKCPIKGLIJI: u32,
    // @@protoc_insertion_point(field:MHANIEBKGHH.HLKAFPCLMEO)
    pub HLKAFPCLMEO: bool,
    // @@protoc_insertion_point(field:MHANIEBKGHH.KBAKJDJPCOF)
    pub KBAKJDJPCOF: ::protobuf::MessageField<super::HHIPKINNCAP::HHIPKINNCAP>,
    // special fields
    // @@protoc_insertion_point(special_field:MHANIEBKGHH.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a MHANIEBKGHH {
    fn default() -> &'a MHANIEBKGHH {
        <MHANIEBKGHH as ::protobuf::Message>::default_instance()
    }
}

impl MHANIEBKGHH {
    pub fn new() -> MHANIEBKGHH {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "EKCPIKGLIJI",
            |m: &MHANIEBKGHH| { &m.EKCPIKGLIJI },
            |m: &mut MHANIEBKGHH| { &mut m.EKCPIKGLIJI },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "HLKAFPCLMEO",
            |m: &MHANIEBKGHH| { &m.HLKAFPCLMEO },
            |m: &mut MHANIEBKGHH| { &mut m.HLKAFPCLMEO },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::HHIPKINNCAP::HHIPKINNCAP>(
            "KBAKJDJPCOF",
            |m: &MHANIEBKGHH| { &m.KBAKJDJPCOF },
            |m: &mut MHANIEBKGHH| { &mut m.KBAKJDJPCOF },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<MHANIEBKGHH>(
            "MHANIEBKGHH",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for MHANIEBKGHH {
    const NAME: &'static str = "MHANIEBKGHH";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.EKCPIKGLIJI = is.read_uint32()?;
                },
                16 => {
                    self.HLKAFPCLMEO = is.read_bool()?;
                },
                26 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.KBAKJDJPCOF)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.EKCPIKGLIJI != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.EKCPIKGLIJI);
        }
        if self.HLKAFPCLMEO != false {
            my_size += 1 + 1;
        }
        if let Some(v) = self.KBAKJDJPCOF.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.EKCPIKGLIJI != 0 {
            os.write_uint32(1, self.EKCPIKGLIJI)?;
        }
        if self.HLKAFPCLMEO != false {
            os.write_bool(2, self.HLKAFPCLMEO)?;
        }
        if let Some(v) = self.KBAKJDJPCOF.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> MHANIEBKGHH {
        MHANIEBKGHH::new()
    }

    fn clear(&mut self) {
        self.EKCPIKGLIJI = 0;
        self.HLKAFPCLMEO = false;
        self.KBAKJDJPCOF.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static MHANIEBKGHH {
        static instance: MHANIEBKGHH = MHANIEBKGHH {
            EKCPIKGLIJI: 0,
            HLKAFPCLMEO: false,
            KBAKJDJPCOF: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for MHANIEBKGHH {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("MHANIEBKGHH").unwrap()).clone()
    }
}

impl ::std::fmt::Display for MHANIEBKGHH {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for MHANIEBKGHH {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11MHANIEBKGHH.proto\x1a\x11HHIPKINNCAP.proto\"\x81\x01\n\x0bMHANIEBK\
    GHH\x12\x20\n\x0bEKCPIKGLIJI\x18\x01\x20\x01(\rR\x0bEKCPIKGLIJI\x12\x20\
    \n\x0bHLKAFPCLMEO\x18\x02\x20\x01(\x08R\x0bHLKAFPCLMEO\x12.\n\x0bKBAKJDJ\
    PCOF\x18\x03\x20\x01(\x0b2\x0c.HHIPKINNCAPR\x0bKBAKJDJPCOFb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::HHIPKINNCAP::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(MHANIEBKGHH::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
