// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `MonopolyGameBingoFlipCardScRsp.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:MonopolyGameBingoFlipCardScRsp)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct MonopolyGameBingoFlipCardScRsp {
    // message fields
    // @@protoc_insertion_point(field:MonopolyGameBingoFlipCardScRsp.retcode)
    pub retcode: u32,
    // @@protoc_insertion_point(field:MonopolyGameBingoFlipCardScRsp.JKLFMOHICMO)
    pub JKLFMOHICMO: bool,
    // @@protoc_insertion_point(field:MonopolyGameBingoFlipCardScRsp.EPLBCNFMLIL)
    pub EPLBCNFMLIL: u32,
    // @@protoc_insertion_point(field:MonopolyGameBingoFlipCardScRsp.EAOFJFAFAHO)
    pub EAOFJFAFAHO: ::std::vec::Vec<u32>,
    // special fields
    // @@protoc_insertion_point(special_field:MonopolyGameBingoFlipCardScRsp.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a MonopolyGameBingoFlipCardScRsp {
    fn default() -> &'a MonopolyGameBingoFlipCardScRsp {
        <MonopolyGameBingoFlipCardScRsp as ::protobuf::Message>::default_instance()
    }
}

impl MonopolyGameBingoFlipCardScRsp {
    pub fn new() -> MonopolyGameBingoFlipCardScRsp {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "retcode",
            |m: &MonopolyGameBingoFlipCardScRsp| { &m.retcode },
            |m: &mut MonopolyGameBingoFlipCardScRsp| { &mut m.retcode },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "JKLFMOHICMO",
            |m: &MonopolyGameBingoFlipCardScRsp| { &m.JKLFMOHICMO },
            |m: &mut MonopolyGameBingoFlipCardScRsp| { &mut m.JKLFMOHICMO },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "EPLBCNFMLIL",
            |m: &MonopolyGameBingoFlipCardScRsp| { &m.EPLBCNFMLIL },
            |m: &mut MonopolyGameBingoFlipCardScRsp| { &mut m.EPLBCNFMLIL },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "EAOFJFAFAHO",
            |m: &MonopolyGameBingoFlipCardScRsp| { &m.EAOFJFAFAHO },
            |m: &mut MonopolyGameBingoFlipCardScRsp| { &mut m.EAOFJFAFAHO },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<MonopolyGameBingoFlipCardScRsp>(
            "MonopolyGameBingoFlipCardScRsp",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for MonopolyGameBingoFlipCardScRsp {
    const NAME: &'static str = "MonopolyGameBingoFlipCardScRsp";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                104 => {
                    self.retcode = is.read_uint32()?;
                },
                16 => {
                    self.JKLFMOHICMO = is.read_bool()?;
                },
                112 => {
                    self.EPLBCNFMLIL = is.read_uint32()?;
                },
                26 => {
                    is.read_repeated_packed_uint32_into(&mut self.EAOFJFAFAHO)?;
                },
                24 => {
                    self.EAOFJFAFAHO.push(is.read_uint32()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.retcode != 0 {
            my_size += ::protobuf::rt::uint32_size(13, self.retcode);
        }
        if self.JKLFMOHICMO != false {
            my_size += 1 + 1;
        }
        if self.EPLBCNFMLIL != 0 {
            my_size += ::protobuf::rt::uint32_size(14, self.EPLBCNFMLIL);
        }
        my_size += ::protobuf::rt::vec_packed_uint32_size(3, &self.EAOFJFAFAHO);
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.retcode != 0 {
            os.write_uint32(13, self.retcode)?;
        }
        if self.JKLFMOHICMO != false {
            os.write_bool(2, self.JKLFMOHICMO)?;
        }
        if self.EPLBCNFMLIL != 0 {
            os.write_uint32(14, self.EPLBCNFMLIL)?;
        }
        os.write_repeated_packed_uint32(3, &self.EAOFJFAFAHO)?;
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> MonopolyGameBingoFlipCardScRsp {
        MonopolyGameBingoFlipCardScRsp::new()
    }

    fn clear(&mut self) {
        self.retcode = 0;
        self.JKLFMOHICMO = false;
        self.EPLBCNFMLIL = 0;
        self.EAOFJFAFAHO.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static MonopolyGameBingoFlipCardScRsp {
        static instance: MonopolyGameBingoFlipCardScRsp = MonopolyGameBingoFlipCardScRsp {
            retcode: 0,
            JKLFMOHICMO: false,
            EPLBCNFMLIL: 0,
            EAOFJFAFAHO: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for MonopolyGameBingoFlipCardScRsp {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("MonopolyGameBingoFlipCardScRsp").unwrap()).clone()
    }
}

impl ::std::fmt::Display for MonopolyGameBingoFlipCardScRsp {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for MonopolyGameBingoFlipCardScRsp {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n$MonopolyGameBingoFlipCardScRsp.proto\"\xa0\x01\n\x1eMonopolyGameBingo\
    FlipCardScRsp\x12\x18\n\x07retcode\x18\r\x20\x01(\rR\x07retcode\x12\x20\
    \n\x0bJKLFMOHICMO\x18\x02\x20\x01(\x08R\x0bJKLFMOHICMO\x12\x20\n\x0bEPLB\
    CNFMLIL\x18\x0e\x20\x01(\rR\x0bEPLBCNFMLIL\x12\x20\n\x0bEAOFJFAFAHO\x18\
    \x03\x20\x03(\rR\x0bEAOFJFAFAHOb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(MonopolyGameBingoFlipCardScRsp::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
