// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `NHEELAHAPCI.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:NHEELAHAPCI)
pub enum NHEELAHAPCI {
    // @@protoc_insertion_point(enum_value:NHEELAHAPCI.NHEELAHAPCI_PCPDHELPKEM)
    NHEELAHAPCI_PCPDHELPKEM = 0,
    // @@protoc_insertion_point(enum_value:NHEELAHAPCI.NHEELAHAPCI_HLIDGDLNFHM)
    NHEELAHAPCI_HLIDGDLNFHM = 1,
    // @@protoc_insertion_point(enum_value:NHEELAHAPCI.NHEELAHAPCI_EGFBGJGIEKM)
    NHEELAHAPCI_EGFBGJGIEKM = 2,
    // @@protoc_insertion_point(enum_value:NHEELAHAPCI.NHEELAHAPCI_NPDCOJCAHPE)
    NHEELAHAPCI_NPDCOJCAHPE = 3,
    // @@protoc_insertion_point(enum_value:NHEELAHAPCI.NHEELAHAPCI_GALGFIOMOIO)
    NHEELAHAPCI_GALGFIOMOIO = 4,
}

impl ::protobuf::Enum for NHEELAHAPCI {
    const NAME: &'static str = "NHEELAHAPCI";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<NHEELAHAPCI> {
        match value {
            0 => ::std::option::Option::Some(NHEELAHAPCI::NHEELAHAPCI_PCPDHELPKEM),
            1 => ::std::option::Option::Some(NHEELAHAPCI::NHEELAHAPCI_HLIDGDLNFHM),
            2 => ::std::option::Option::Some(NHEELAHAPCI::NHEELAHAPCI_EGFBGJGIEKM),
            3 => ::std::option::Option::Some(NHEELAHAPCI::NHEELAHAPCI_NPDCOJCAHPE),
            4 => ::std::option::Option::Some(NHEELAHAPCI::NHEELAHAPCI_GALGFIOMOIO),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<NHEELAHAPCI> {
        match str {
            "NHEELAHAPCI_PCPDHELPKEM" => ::std::option::Option::Some(NHEELAHAPCI::NHEELAHAPCI_PCPDHELPKEM),
            "NHEELAHAPCI_HLIDGDLNFHM" => ::std::option::Option::Some(NHEELAHAPCI::NHEELAHAPCI_HLIDGDLNFHM),
            "NHEELAHAPCI_EGFBGJGIEKM" => ::std::option::Option::Some(NHEELAHAPCI::NHEELAHAPCI_EGFBGJGIEKM),
            "NHEELAHAPCI_NPDCOJCAHPE" => ::std::option::Option::Some(NHEELAHAPCI::NHEELAHAPCI_NPDCOJCAHPE),
            "NHEELAHAPCI_GALGFIOMOIO" => ::std::option::Option::Some(NHEELAHAPCI::NHEELAHAPCI_GALGFIOMOIO),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [NHEELAHAPCI] = &[
        NHEELAHAPCI::NHEELAHAPCI_PCPDHELPKEM,
        NHEELAHAPCI::NHEELAHAPCI_HLIDGDLNFHM,
        NHEELAHAPCI::NHEELAHAPCI_EGFBGJGIEKM,
        NHEELAHAPCI::NHEELAHAPCI_NPDCOJCAHPE,
        NHEELAHAPCI::NHEELAHAPCI_GALGFIOMOIO,
    ];
}

impl ::protobuf::EnumFull for NHEELAHAPCI {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("NHEELAHAPCI").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for NHEELAHAPCI {
    fn default() -> Self {
        NHEELAHAPCI::NHEELAHAPCI_PCPDHELPKEM
    }
}

impl NHEELAHAPCI {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<NHEELAHAPCI>("NHEELAHAPCI")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11NHEELAHAPCI.proto*\x9e\x01\n\x0bNHEELAHAPCI\x12\x1b\n\x17NHEELAHAP\
    CI_PCPDHELPKEM\x10\0\x12\x1b\n\x17NHEELAHAPCI_HLIDGDLNFHM\x10\x01\x12\
    \x1b\n\x17NHEELAHAPCI_EGFBGJGIEKM\x10\x02\x12\x1b\n\x17NHEELAHAPCI_NPDCO\
    JCAHPE\x10\x03\x12\x1b\n\x17NHEELAHAPCI_GALGFIOMOIO\x10\x04b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(NHEELAHAPCI::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
