// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `OMHAOBFKIKE.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:OMHAOBFKIKE)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct OMHAOBFKIKE {
    // message fields
    // @@protoc_insertion_point(field:OMHAOBFKIKE.avatar_id)
    pub avatar_id: u32,
    // @@protoc_insertion_point(field:OMHAOBFKIKE.AAGBLPKDJJP)
    pub AAGBLPKDJJP: ::protobuf::MessageField<super::MGGLDHHPNBM::MGGLDHHPNBM>,
    // @@protoc_insertion_point(field:OMHAOBFKIKE.HIMECMGJKOM)
    pub HIMECMGJKOM: ::protobuf::EnumOrUnknown<super::MDIKAOAEJHN::MDIKAOAEJHN>,
    // special fields
    // @@protoc_insertion_point(special_field:OMHAOBFKIKE.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a OMHAOBFKIKE {
    fn default() -> &'a OMHAOBFKIKE {
        <OMHAOBFKIKE as ::protobuf::Message>::default_instance()
    }
}

impl OMHAOBFKIKE {
    pub fn new() -> OMHAOBFKIKE {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "avatar_id",
            |m: &OMHAOBFKIKE| { &m.avatar_id },
            |m: &mut OMHAOBFKIKE| { &mut m.avatar_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::MGGLDHHPNBM::MGGLDHHPNBM>(
            "AAGBLPKDJJP",
            |m: &OMHAOBFKIKE| { &m.AAGBLPKDJJP },
            |m: &mut OMHAOBFKIKE| { &mut m.AAGBLPKDJJP },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "HIMECMGJKOM",
            |m: &OMHAOBFKIKE| { &m.HIMECMGJKOM },
            |m: &mut OMHAOBFKIKE| { &mut m.HIMECMGJKOM },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<OMHAOBFKIKE>(
            "OMHAOBFKIKE",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for OMHAOBFKIKE {
    const NAME: &'static str = "OMHAOBFKIKE";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                96 => {
                    self.avatar_id = is.read_uint32()?;
                },
                42 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.AAGBLPKDJJP)?;
                },
                16 => {
                    self.HIMECMGJKOM = is.read_enum_or_unknown()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.avatar_id != 0 {
            my_size += ::protobuf::rt::uint32_size(12, self.avatar_id);
        }
        if let Some(v) = self.AAGBLPKDJJP.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if self.HIMECMGJKOM != ::protobuf::EnumOrUnknown::new(super::MDIKAOAEJHN::MDIKAOAEJHN::MDIKAOAEJHN_IHPFCMLEKCG) {
            my_size += ::protobuf::rt::int32_size(2, self.HIMECMGJKOM.value());
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.avatar_id != 0 {
            os.write_uint32(12, self.avatar_id)?;
        }
        if let Some(v) = self.AAGBLPKDJJP.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(5, v, os)?;
        }
        if self.HIMECMGJKOM != ::protobuf::EnumOrUnknown::new(super::MDIKAOAEJHN::MDIKAOAEJHN::MDIKAOAEJHN_IHPFCMLEKCG) {
            os.write_enum(2, ::protobuf::EnumOrUnknown::value(&self.HIMECMGJKOM))?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> OMHAOBFKIKE {
        OMHAOBFKIKE::new()
    }

    fn clear(&mut self) {
        self.avatar_id = 0;
        self.AAGBLPKDJJP.clear();
        self.HIMECMGJKOM = ::protobuf::EnumOrUnknown::new(super::MDIKAOAEJHN::MDIKAOAEJHN::MDIKAOAEJHN_IHPFCMLEKCG);
        self.special_fields.clear();
    }

    fn default_instance() -> &'static OMHAOBFKIKE {
        static instance: OMHAOBFKIKE = OMHAOBFKIKE {
            avatar_id: 0,
            AAGBLPKDJJP: ::protobuf::MessageField::none(),
            HIMECMGJKOM: ::protobuf::EnumOrUnknown::from_i32(0),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for OMHAOBFKIKE {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("OMHAOBFKIKE").unwrap()).clone()
    }
}

impl ::std::fmt::Display for OMHAOBFKIKE {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for OMHAOBFKIKE {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11OMHAOBFKIKE.proto\x1a\x11MDIKAOAEJHN.proto\x1a\x11MGGLDHHPNBM.prot\
    o\"\x8a\x01\n\x0bOMHAOBFKIKE\x12\x1b\n\tavatar_id\x18\x0c\x20\x01(\rR\
    \x08avatarId\x12.\n\x0bAAGBLPKDJJP\x18\x05\x20\x01(\x0b2\x0c.MGGLDHHPNBM\
    R\x0bAAGBLPKDJJP\x12.\n\x0bHIMECMGJKOM\x18\x02\x20\x01(\x0e2\x0c.MDIKAOA\
    EJHNR\x0bHIMECMGJKOMb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(2);
            deps.push(super::MDIKAOAEJHN::file_descriptor().clone());
            deps.push(super::MGGLDHHPNBM::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(OMHAOBFKIKE::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
