// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `PKNLNBGNFDF.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:PKNLNBGNFDF)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct PKNLNBGNFDF {
    // message fields
    // @@protoc_insertion_point(field:PKNLNBGNFDF.BGDGGALAODO)
    pub BGDGGALAODO: ::protobuf::MessageField<super::DMAJILEBABM::DMAJILEBABM>,
    // @@protoc_insertion_point(field:PKNLNBGNFDF.DGJHEEPIGLH)
    pub DGJHEEPIGLH: bool,
    // special fields
    // @@protoc_insertion_point(special_field:PKNLNBGNFDF.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a PKNLNBGNFDF {
    fn default() -> &'a PKNLNBGNFDF {
        <PKNLNBGNFDF as ::protobuf::Message>::default_instance()
    }
}

impl PKNLNBGNFDF {
    pub fn new() -> PKNLNBGNFDF {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::DMAJILEBABM::DMAJILEBABM>(
            "BGDGGALAODO",
            |m: &PKNLNBGNFDF| { &m.BGDGGALAODO },
            |m: &mut PKNLNBGNFDF| { &mut m.BGDGGALAODO },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "DGJHEEPIGLH",
            |m: &PKNLNBGNFDF| { &m.DGJHEEPIGLH },
            |m: &mut PKNLNBGNFDF| { &mut m.DGJHEEPIGLH },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<PKNLNBGNFDF>(
            "PKNLNBGNFDF",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for PKNLNBGNFDF {
    const NAME: &'static str = "PKNLNBGNFDF";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                98 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.BGDGGALAODO)?;
                },
                80 => {
                    self.DGJHEEPIGLH = is.read_bool()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.BGDGGALAODO.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if self.DGJHEEPIGLH != false {
            my_size += 1 + 1;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.BGDGGALAODO.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(12, v, os)?;
        }
        if self.DGJHEEPIGLH != false {
            os.write_bool(10, self.DGJHEEPIGLH)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> PKNLNBGNFDF {
        PKNLNBGNFDF::new()
    }

    fn clear(&mut self) {
        self.BGDGGALAODO.clear();
        self.DGJHEEPIGLH = false;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static PKNLNBGNFDF {
        static instance: PKNLNBGNFDF = PKNLNBGNFDF {
            BGDGGALAODO: ::protobuf::MessageField::none(),
            DGJHEEPIGLH: false,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for PKNLNBGNFDF {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("PKNLNBGNFDF").unwrap()).clone()
    }
}

impl ::std::fmt::Display for PKNLNBGNFDF {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for PKNLNBGNFDF {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11PKNLNBGNFDF.proto\x1a\x11DMAJILEBABM.proto\"_\n\x0bPKNLNBGNFDF\x12\
    .\n\x0bBGDGGALAODO\x18\x0c\x20\x01(\x0b2\x0c.DMAJILEBABMR\x0bBGDGGALAODO\
    \x12\x20\n\x0bDGJHEEPIGLH\x18\n\x20\x01(\x08R\x0bDGJHEEPIGLHb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::DMAJILEBABM::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(PKNLNBGNFDF::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
