// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `PLIEEDKHGNN.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:PLIEEDKHGNN)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct PLIEEDKHGNN {
    // message fields
    // @@protoc_insertion_point(field:PLIEEDKHGNN.DGLIPLAHMBF)
    pub DGLIPLAHMBF: ::std::vec::Vec<u32>,
    // @@protoc_insertion_point(field:PLIEEDKHGNN.CAJCAGNBGEK)
    pub CAJCAGNBGEK: bool,
    // @@protoc_insertion_point(field:PLIEEDKHGNN.ADDEMHFJJAH)
    pub ADDEMHFJJAH: u32,
    // @@protoc_insertion_point(field:PLIEEDKHGNN.HCAFCGKLKFD)
    pub HCAFCGKLKFD: ::std::vec::Vec<u32>,
    // @@protoc_insertion_point(field:PLIEEDKHGNN.BMGEBFHHCOD)
    pub BMGEBFHHCOD: u32,
    // @@protoc_insertion_point(field:PLIEEDKHGNN.JLDPAIPAMNB)
    pub JLDPAIPAMNB: u32,
    // special fields
    // @@protoc_insertion_point(special_field:PLIEEDKHGNN.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a PLIEEDKHGNN {
    fn default() -> &'a PLIEEDKHGNN {
        <PLIEEDKHGNN as ::protobuf::Message>::default_instance()
    }
}

impl PLIEEDKHGNN {
    pub fn new() -> PLIEEDKHGNN {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(6);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "DGLIPLAHMBF",
            |m: &PLIEEDKHGNN| { &m.DGLIPLAHMBF },
            |m: &mut PLIEEDKHGNN| { &mut m.DGLIPLAHMBF },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "CAJCAGNBGEK",
            |m: &PLIEEDKHGNN| { &m.CAJCAGNBGEK },
            |m: &mut PLIEEDKHGNN| { &mut m.CAJCAGNBGEK },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "ADDEMHFJJAH",
            |m: &PLIEEDKHGNN| { &m.ADDEMHFJJAH },
            |m: &mut PLIEEDKHGNN| { &mut m.ADDEMHFJJAH },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "HCAFCGKLKFD",
            |m: &PLIEEDKHGNN| { &m.HCAFCGKLKFD },
            |m: &mut PLIEEDKHGNN| { &mut m.HCAFCGKLKFD },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "BMGEBFHHCOD",
            |m: &PLIEEDKHGNN| { &m.BMGEBFHHCOD },
            |m: &mut PLIEEDKHGNN| { &mut m.BMGEBFHHCOD },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "JLDPAIPAMNB",
            |m: &PLIEEDKHGNN| { &m.JLDPAIPAMNB },
            |m: &mut PLIEEDKHGNN| { &mut m.JLDPAIPAMNB },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<PLIEEDKHGNN>(
            "PLIEEDKHGNN",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for PLIEEDKHGNN {
    const NAME: &'static str = "PLIEEDKHGNN";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    is.read_repeated_packed_uint32_into(&mut self.DGLIPLAHMBF)?;
                },
                8 => {
                    self.DGLIPLAHMBF.push(is.read_uint32()?);
                },
                40 => {
                    self.CAJCAGNBGEK = is.read_bool()?;
                },
                72 => {
                    self.ADDEMHFJJAH = is.read_uint32()?;
                },
                58 => {
                    is.read_repeated_packed_uint32_into(&mut self.HCAFCGKLKFD)?;
                },
                56 => {
                    self.HCAFCGKLKFD.push(is.read_uint32()?);
                },
                120 => {
                    self.BMGEBFHHCOD = is.read_uint32()?;
                },
                104 => {
                    self.JLDPAIPAMNB = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::vec_packed_uint32_size(1, &self.DGLIPLAHMBF);
        if self.CAJCAGNBGEK != false {
            my_size += 1 + 1;
        }
        if self.ADDEMHFJJAH != 0 {
            my_size += ::protobuf::rt::uint32_size(9, self.ADDEMHFJJAH);
        }
        my_size += ::protobuf::rt::vec_packed_uint32_size(7, &self.HCAFCGKLKFD);
        if self.BMGEBFHHCOD != 0 {
            my_size += ::protobuf::rt::uint32_size(15, self.BMGEBFHHCOD);
        }
        if self.JLDPAIPAMNB != 0 {
            my_size += ::protobuf::rt::uint32_size(13, self.JLDPAIPAMNB);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        os.write_repeated_packed_uint32(1, &self.DGLIPLAHMBF)?;
        if self.CAJCAGNBGEK != false {
            os.write_bool(5, self.CAJCAGNBGEK)?;
        }
        if self.ADDEMHFJJAH != 0 {
            os.write_uint32(9, self.ADDEMHFJJAH)?;
        }
        os.write_repeated_packed_uint32(7, &self.HCAFCGKLKFD)?;
        if self.BMGEBFHHCOD != 0 {
            os.write_uint32(15, self.BMGEBFHHCOD)?;
        }
        if self.JLDPAIPAMNB != 0 {
            os.write_uint32(13, self.JLDPAIPAMNB)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> PLIEEDKHGNN {
        PLIEEDKHGNN::new()
    }

    fn clear(&mut self) {
        self.DGLIPLAHMBF.clear();
        self.CAJCAGNBGEK = false;
        self.ADDEMHFJJAH = 0;
        self.HCAFCGKLKFD.clear();
        self.BMGEBFHHCOD = 0;
        self.JLDPAIPAMNB = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static PLIEEDKHGNN {
        static instance: PLIEEDKHGNN = PLIEEDKHGNN {
            DGLIPLAHMBF: ::std::vec::Vec::new(),
            CAJCAGNBGEK: false,
            ADDEMHFJJAH: 0,
            HCAFCGKLKFD: ::std::vec::Vec::new(),
            BMGEBFHHCOD: 0,
            JLDPAIPAMNB: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for PLIEEDKHGNN {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("PLIEEDKHGNN").unwrap()).clone()
    }
}

impl ::std::fmt::Display for PLIEEDKHGNN {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for PLIEEDKHGNN {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11PLIEEDKHGNN.proto\"\xd9\x01\n\x0bPLIEEDKHGNN\x12\x20\n\x0bDGLIPLAH\
    MBF\x18\x01\x20\x03(\rR\x0bDGLIPLAHMBF\x12\x20\n\x0bCAJCAGNBGEK\x18\x05\
    \x20\x01(\x08R\x0bCAJCAGNBGEK\x12\x20\n\x0bADDEMHFJJAH\x18\t\x20\x01(\rR\
    \x0bADDEMHFJJAH\x12\x20\n\x0bHCAFCGKLKFD\x18\x07\x20\x03(\rR\x0bHCAFCGKL\
    KFD\x12\x20\n\x0bBMGEBFHHCOD\x18\x0f\x20\x01(\rR\x0bBMGEBFHHCOD\x12\x20\
    \n\x0bJLDPAIPAMNB\x18\r\x20\x01(\rR\x0bJLDPAIPAMNBb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(PLIEEDKHGNN::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
