// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `SettleHipplenWorkCsReq.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:SettleHipplenWorkCsReq)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SettleHipplenWorkCsReq {
    // message oneof groups
    pub HDACCIEIJFO: ::std::option::Option<settle_hipplen_work_cs_req::HDACCIEIJFO>,
    // special fields
    // @@protoc_insertion_point(special_field:SettleHipplenWorkCsReq.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SettleHipplenWorkCsReq {
    fn default() -> &'a SettleHipplenWorkCsReq {
        <SettleHipplenWorkCsReq as ::protobuf::Message>::default_instance()
    }
}

impl SettleHipplenWorkCsReq {
    pub fn new() -> SettleHipplenWorkCsReq {
        ::std::default::Default::default()
    }

    // .KJBGALBCAEG BJGDFMJDJMH = 13;

    pub fn BJGDFMJDJMH(&self) -> &super::KJBGALBCAEG::KJBGALBCAEG {
        match self.HDACCIEIJFO {
            ::std::option::Option::Some(settle_hipplen_work_cs_req::HDACCIEIJFO::BJGDFMJDJMH(ref v)) => v,
            _ => <super::KJBGALBCAEG::KJBGALBCAEG as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_BJGDFMJDJMH(&mut self) {
        self.HDACCIEIJFO = ::std::option::Option::None;
    }

    pub fn has_BJGDFMJDJMH(&self) -> bool {
        match self.HDACCIEIJFO {
            ::std::option::Option::Some(settle_hipplen_work_cs_req::HDACCIEIJFO::BJGDFMJDJMH(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_BJGDFMJDJMH(&mut self, v: super::KJBGALBCAEG::KJBGALBCAEG) {
        self.HDACCIEIJFO = ::std::option::Option::Some(settle_hipplen_work_cs_req::HDACCIEIJFO::BJGDFMJDJMH(v))
    }

    // Mutable pointer to the field.
    pub fn mut_BJGDFMJDJMH(&mut self) -> &mut super::KJBGALBCAEG::KJBGALBCAEG {
        if let ::std::option::Option::Some(settle_hipplen_work_cs_req::HDACCIEIJFO::BJGDFMJDJMH(_)) = self.HDACCIEIJFO {
        } else {
            self.HDACCIEIJFO = ::std::option::Option::Some(settle_hipplen_work_cs_req::HDACCIEIJFO::BJGDFMJDJMH(super::KJBGALBCAEG::KJBGALBCAEG::new()));
        }
        match self.HDACCIEIJFO {
            ::std::option::Option::Some(settle_hipplen_work_cs_req::HDACCIEIJFO::BJGDFMJDJMH(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_BJGDFMJDJMH(&mut self) -> super::KJBGALBCAEG::KJBGALBCAEG {
        if self.has_BJGDFMJDJMH() {
            match self.HDACCIEIJFO.take() {
                ::std::option::Option::Some(settle_hipplen_work_cs_req::HDACCIEIJFO::BJGDFMJDJMH(v)) => v,
                _ => panic!(),
            }
        } else {
            super::KJBGALBCAEG::KJBGALBCAEG::new()
        }
    }

    // .ONCIMHEMJDD MNIMAFBIGGP = 3;

    pub fn MNIMAFBIGGP(&self) -> &super::ONCIMHEMJDD::ONCIMHEMJDD {
        match self.HDACCIEIJFO {
            ::std::option::Option::Some(settle_hipplen_work_cs_req::HDACCIEIJFO::MNIMAFBIGGP(ref v)) => v,
            _ => <super::ONCIMHEMJDD::ONCIMHEMJDD as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_MNIMAFBIGGP(&mut self) {
        self.HDACCIEIJFO = ::std::option::Option::None;
    }

    pub fn has_MNIMAFBIGGP(&self) -> bool {
        match self.HDACCIEIJFO {
            ::std::option::Option::Some(settle_hipplen_work_cs_req::HDACCIEIJFO::MNIMAFBIGGP(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_MNIMAFBIGGP(&mut self, v: super::ONCIMHEMJDD::ONCIMHEMJDD) {
        self.HDACCIEIJFO = ::std::option::Option::Some(settle_hipplen_work_cs_req::HDACCIEIJFO::MNIMAFBIGGP(v))
    }

    // Mutable pointer to the field.
    pub fn mut_MNIMAFBIGGP(&mut self) -> &mut super::ONCIMHEMJDD::ONCIMHEMJDD {
        if let ::std::option::Option::Some(settle_hipplen_work_cs_req::HDACCIEIJFO::MNIMAFBIGGP(_)) = self.HDACCIEIJFO {
        } else {
            self.HDACCIEIJFO = ::std::option::Option::Some(settle_hipplen_work_cs_req::HDACCIEIJFO::MNIMAFBIGGP(super::ONCIMHEMJDD::ONCIMHEMJDD::new()));
        }
        match self.HDACCIEIJFO {
            ::std::option::Option::Some(settle_hipplen_work_cs_req::HDACCIEIJFO::MNIMAFBIGGP(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_MNIMAFBIGGP(&mut self) -> super::ONCIMHEMJDD::ONCIMHEMJDD {
        if self.has_MNIMAFBIGGP() {
            match self.HDACCIEIJFO.take() {
                ::std::option::Option::Some(settle_hipplen_work_cs_req::HDACCIEIJFO::MNIMAFBIGGP(v)) => v,
                _ => panic!(),
            }
        } else {
            super::ONCIMHEMJDD::ONCIMHEMJDD::new()
        }
    }

    // .OJOLPAEPBDN PPJOJOKOOBF = 10;

    pub fn PPJOJOKOOBF(&self) -> &super::OJOLPAEPBDN::OJOLPAEPBDN {
        match self.HDACCIEIJFO {
            ::std::option::Option::Some(settle_hipplen_work_cs_req::HDACCIEIJFO::PPJOJOKOOBF(ref v)) => v,
            _ => <super::OJOLPAEPBDN::OJOLPAEPBDN as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_PPJOJOKOOBF(&mut self) {
        self.HDACCIEIJFO = ::std::option::Option::None;
    }

    pub fn has_PPJOJOKOOBF(&self) -> bool {
        match self.HDACCIEIJFO {
            ::std::option::Option::Some(settle_hipplen_work_cs_req::HDACCIEIJFO::PPJOJOKOOBF(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_PPJOJOKOOBF(&mut self, v: super::OJOLPAEPBDN::OJOLPAEPBDN) {
        self.HDACCIEIJFO = ::std::option::Option::Some(settle_hipplen_work_cs_req::HDACCIEIJFO::PPJOJOKOOBF(v))
    }

    // Mutable pointer to the field.
    pub fn mut_PPJOJOKOOBF(&mut self) -> &mut super::OJOLPAEPBDN::OJOLPAEPBDN {
        if let ::std::option::Option::Some(settle_hipplen_work_cs_req::HDACCIEIJFO::PPJOJOKOOBF(_)) = self.HDACCIEIJFO {
        } else {
            self.HDACCIEIJFO = ::std::option::Option::Some(settle_hipplen_work_cs_req::HDACCIEIJFO::PPJOJOKOOBF(super::OJOLPAEPBDN::OJOLPAEPBDN::new()));
        }
        match self.HDACCIEIJFO {
            ::std::option::Option::Some(settle_hipplen_work_cs_req::HDACCIEIJFO::PPJOJOKOOBF(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_PPJOJOKOOBF(&mut self) -> super::OJOLPAEPBDN::OJOLPAEPBDN {
        if self.has_PPJOJOKOOBF() {
            match self.HDACCIEIJFO.take() {
                ::std::option::Option::Some(settle_hipplen_work_cs_req::HDACCIEIJFO::PPJOJOKOOBF(v)) => v,
                _ => panic!(),
            }
        } else {
            super::OJOLPAEPBDN::OJOLPAEPBDN::new()
        }
    }

    // .CJEAIHMINMJ PGJIAGGHBBA = 2;

    pub fn PGJIAGGHBBA(&self) -> &super::CJEAIHMINMJ::CJEAIHMINMJ {
        match self.HDACCIEIJFO {
            ::std::option::Option::Some(settle_hipplen_work_cs_req::HDACCIEIJFO::PGJIAGGHBBA(ref v)) => v,
            _ => <super::CJEAIHMINMJ::CJEAIHMINMJ as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_PGJIAGGHBBA(&mut self) {
        self.HDACCIEIJFO = ::std::option::Option::None;
    }

    pub fn has_PGJIAGGHBBA(&self) -> bool {
        match self.HDACCIEIJFO {
            ::std::option::Option::Some(settle_hipplen_work_cs_req::HDACCIEIJFO::PGJIAGGHBBA(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_PGJIAGGHBBA(&mut self, v: super::CJEAIHMINMJ::CJEAIHMINMJ) {
        self.HDACCIEIJFO = ::std::option::Option::Some(settle_hipplen_work_cs_req::HDACCIEIJFO::PGJIAGGHBBA(v))
    }

    // Mutable pointer to the field.
    pub fn mut_PGJIAGGHBBA(&mut self) -> &mut super::CJEAIHMINMJ::CJEAIHMINMJ {
        if let ::std::option::Option::Some(settle_hipplen_work_cs_req::HDACCIEIJFO::PGJIAGGHBBA(_)) = self.HDACCIEIJFO {
        } else {
            self.HDACCIEIJFO = ::std::option::Option::Some(settle_hipplen_work_cs_req::HDACCIEIJFO::PGJIAGGHBBA(super::CJEAIHMINMJ::CJEAIHMINMJ::new()));
        }
        match self.HDACCIEIJFO {
            ::std::option::Option::Some(settle_hipplen_work_cs_req::HDACCIEIJFO::PGJIAGGHBBA(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_PGJIAGGHBBA(&mut self) -> super::CJEAIHMINMJ::CJEAIHMINMJ {
        if self.has_PGJIAGGHBBA() {
            match self.HDACCIEIJFO.take() {
                ::std::option::Option::Some(settle_hipplen_work_cs_req::HDACCIEIJFO::PGJIAGGHBBA(v)) => v,
                _ => panic!(),
            }
        } else {
            super::CJEAIHMINMJ::CJEAIHMINMJ::new()
        }
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(1);
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::KJBGALBCAEG::KJBGALBCAEG>(
            "BJGDFMJDJMH",
            SettleHipplenWorkCsReq::has_BJGDFMJDJMH,
            SettleHipplenWorkCsReq::BJGDFMJDJMH,
            SettleHipplenWorkCsReq::mut_BJGDFMJDJMH,
            SettleHipplenWorkCsReq::set_BJGDFMJDJMH,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::ONCIMHEMJDD::ONCIMHEMJDD>(
            "MNIMAFBIGGP",
            SettleHipplenWorkCsReq::has_MNIMAFBIGGP,
            SettleHipplenWorkCsReq::MNIMAFBIGGP,
            SettleHipplenWorkCsReq::mut_MNIMAFBIGGP,
            SettleHipplenWorkCsReq::set_MNIMAFBIGGP,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::OJOLPAEPBDN::OJOLPAEPBDN>(
            "PPJOJOKOOBF",
            SettleHipplenWorkCsReq::has_PPJOJOKOOBF,
            SettleHipplenWorkCsReq::PPJOJOKOOBF,
            SettleHipplenWorkCsReq::mut_PPJOJOKOOBF,
            SettleHipplenWorkCsReq::set_PPJOJOKOOBF,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::CJEAIHMINMJ::CJEAIHMINMJ>(
            "PGJIAGGHBBA",
            SettleHipplenWorkCsReq::has_PGJIAGGHBBA,
            SettleHipplenWorkCsReq::PGJIAGGHBBA,
            SettleHipplenWorkCsReq::mut_PGJIAGGHBBA,
            SettleHipplenWorkCsReq::set_PGJIAGGHBBA,
        ));
        oneofs.push(settle_hipplen_work_cs_req::HDACCIEIJFO::generated_oneof_descriptor_data());
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SettleHipplenWorkCsReq>(
            "SettleHipplenWorkCsReq",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SettleHipplenWorkCsReq {
    const NAME: &'static str = "SettleHipplenWorkCsReq";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                106 => {
                    self.HDACCIEIJFO = ::std::option::Option::Some(settle_hipplen_work_cs_req::HDACCIEIJFO::BJGDFMJDJMH(is.read_message()?));
                },
                26 => {
                    self.HDACCIEIJFO = ::std::option::Option::Some(settle_hipplen_work_cs_req::HDACCIEIJFO::MNIMAFBIGGP(is.read_message()?));
                },
                82 => {
                    self.HDACCIEIJFO = ::std::option::Option::Some(settle_hipplen_work_cs_req::HDACCIEIJFO::PPJOJOKOOBF(is.read_message()?));
                },
                18 => {
                    self.HDACCIEIJFO = ::std::option::Option::Some(settle_hipplen_work_cs_req::HDACCIEIJFO::PGJIAGGHBBA(is.read_message()?));
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let ::std::option::Option::Some(ref v) = self.HDACCIEIJFO {
            match v {
                &settle_hipplen_work_cs_req::HDACCIEIJFO::BJGDFMJDJMH(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &settle_hipplen_work_cs_req::HDACCIEIJFO::MNIMAFBIGGP(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &settle_hipplen_work_cs_req::HDACCIEIJFO::PPJOJOKOOBF(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &settle_hipplen_work_cs_req::HDACCIEIJFO::PGJIAGGHBBA(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let ::std::option::Option::Some(ref v) = self.HDACCIEIJFO {
            match v {
                &settle_hipplen_work_cs_req::HDACCIEIJFO::BJGDFMJDJMH(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(13, v, os)?;
                },
                &settle_hipplen_work_cs_req::HDACCIEIJFO::MNIMAFBIGGP(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
                },
                &settle_hipplen_work_cs_req::HDACCIEIJFO::PPJOJOKOOBF(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(10, v, os)?;
                },
                &settle_hipplen_work_cs_req::HDACCIEIJFO::PGJIAGGHBBA(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
                },
            };
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SettleHipplenWorkCsReq {
        SettleHipplenWorkCsReq::new()
    }

    fn clear(&mut self) {
        self.HDACCIEIJFO = ::std::option::Option::None;
        self.HDACCIEIJFO = ::std::option::Option::None;
        self.HDACCIEIJFO = ::std::option::Option::None;
        self.HDACCIEIJFO = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SettleHipplenWorkCsReq {
        static instance: SettleHipplenWorkCsReq = SettleHipplenWorkCsReq {
            HDACCIEIJFO: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SettleHipplenWorkCsReq {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SettleHipplenWorkCsReq").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SettleHipplenWorkCsReq {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SettleHipplenWorkCsReq {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `SettleHipplenWorkCsReq`
pub mod settle_hipplen_work_cs_req {

    #[derive(Clone,PartialEq,Debug)]
    #[non_exhaustive]
    // @@protoc_insertion_point(oneof:SettleHipplenWorkCsReq.HDACCIEIJFO)
    pub enum HDACCIEIJFO {
        // @@protoc_insertion_point(oneof_field:SettleHipplenWorkCsReq.BJGDFMJDJMH)
        BJGDFMJDJMH(super::super::KJBGALBCAEG::KJBGALBCAEG),
        // @@protoc_insertion_point(oneof_field:SettleHipplenWorkCsReq.MNIMAFBIGGP)
        MNIMAFBIGGP(super::super::ONCIMHEMJDD::ONCIMHEMJDD),
        // @@protoc_insertion_point(oneof_field:SettleHipplenWorkCsReq.PPJOJOKOOBF)
        PPJOJOKOOBF(super::super::OJOLPAEPBDN::OJOLPAEPBDN),
        // @@protoc_insertion_point(oneof_field:SettleHipplenWorkCsReq.PGJIAGGHBBA)
        PGJIAGGHBBA(super::super::CJEAIHMINMJ::CJEAIHMINMJ),
    }

    impl ::protobuf::Oneof for HDACCIEIJFO {
    }

    impl ::protobuf::OneofFull for HDACCIEIJFO {
        fn descriptor() -> ::protobuf::reflect::OneofDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::OneofDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| <super::SettleHipplenWorkCsReq as ::protobuf::MessageFull>::descriptor().oneof_by_name("HDACCIEIJFO").unwrap()).clone()
        }
    }

    impl HDACCIEIJFO {
        pub(in super) fn generated_oneof_descriptor_data() -> ::protobuf::reflect::GeneratedOneofDescriptorData {
            ::protobuf::reflect::GeneratedOneofDescriptorData::new::<HDACCIEIJFO>("HDACCIEIJFO")
        }
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1cSettleHipplenWorkCsReq.proto\x1a\x11CJEAIHMINMJ.proto\x1a\x11KJBGA\
    LBCAEG.proto\x1a\x11OJOLPAEPBDN.proto\x1a\x11ONCIMHEMJDD.proto\"\xef\x01\
    \n\x16SettleHipplenWorkCsReq\x120\n\x0bBJGDFMJDJMH\x18\r\x20\x01(\x0b2\
    \x0c.KJBGALBCAEGH\0R\x0bBJGDFMJDJMH\x120\n\x0bMNIMAFBIGGP\x18\x03\x20\
    \x01(\x0b2\x0c.ONCIMHEMJDDH\0R\x0bMNIMAFBIGGP\x120\n\x0bPPJOJOKOOBF\x18\
    \n\x20\x01(\x0b2\x0c.OJOLPAEPBDNH\0R\x0bPPJOJOKOOBF\x120\n\x0bPGJIAGGHBB\
    A\x18\x02\x20\x01(\x0b2\x0c.CJEAIHMINMJH\0R\x0bPGJIAGGHBBAB\r\n\x0bHDACC\
    IEIJFOb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(4);
            deps.push(super::CJEAIHMINMJ::file_descriptor().clone());
            deps.push(super::KJBGALBCAEG::file_descriptor().clone());
            deps.push(super::OJOLPAEPBDN::file_descriptor().clone());
            deps.push(super::ONCIMHEMJDD::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(SettleHipplenWorkCsReq::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
