// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `SocialPlayGameplayOperationScNotify.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:SocialPlayGameplayOperationScNotify)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SocialPlayGameplayOperationScNotify {
    // message fields
    // @@protoc_insertion_point(field:SocialPlayGameplayOperationScNotify.NCFHGIBCEBG)
    pub NCFHGIBCEBG: u32,
    // @@protoc_insertion_point(field:SocialPlayGameplayOperationScNotify.MFBDMLPDEOE)
    pub MFBDMLPDEOE: u32,
    // message oneof groups
    pub DCINAIHIPOC: ::std::option::Option<social_play_gameplay_operation_sc_notify::DCINAIHIPOC>,
    // special fields
    // @@protoc_insertion_point(special_field:SocialPlayGameplayOperationScNotify.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SocialPlayGameplayOperationScNotify {
    fn default() -> &'a SocialPlayGameplayOperationScNotify {
        <SocialPlayGameplayOperationScNotify as ::protobuf::Message>::default_instance()
    }
}

impl SocialPlayGameplayOperationScNotify {
    pub fn new() -> SocialPlayGameplayOperationScNotify {
        ::std::default::Default::default()
    }

    // .CCKCCKHEFFB IACKOCPGIAK = 684;

    pub fn IACKOCPGIAK(&self) -> &super::CCKCCKHEFFB::CCKCCKHEFFB {
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::IACKOCPGIAK(ref v)) => v,
            _ => <super::CCKCCKHEFFB::CCKCCKHEFFB as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_IACKOCPGIAK(&mut self) {
        self.DCINAIHIPOC = ::std::option::Option::None;
    }

    pub fn has_IACKOCPGIAK(&self) -> bool {
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::IACKOCPGIAK(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_IACKOCPGIAK(&mut self, v: super::CCKCCKHEFFB::CCKCCKHEFFB) {
        self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::IACKOCPGIAK(v))
    }

    // Mutable pointer to the field.
    pub fn mut_IACKOCPGIAK(&mut self) -> &mut super::CCKCCKHEFFB::CCKCCKHEFFB {
        if let ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::IACKOCPGIAK(_)) = self.DCINAIHIPOC {
        } else {
            self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::IACKOCPGIAK(super::CCKCCKHEFFB::CCKCCKHEFFB::new()));
        }
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::IACKOCPGIAK(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_IACKOCPGIAK(&mut self) -> super::CCKCCKHEFFB::CCKCCKHEFFB {
        if self.has_IACKOCPGIAK() {
            match self.DCINAIHIPOC.take() {
                ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::IACKOCPGIAK(v)) => v,
                _ => panic!(),
            }
        } else {
            super::CCKCCKHEFFB::CCKCCKHEFFB::new()
        }
    }

    // uint32 JKMNPPEOIJP = 294;

    pub fn JKMNPPEOIJP(&self) -> u32 {
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::JKMNPPEOIJP(v)) => v,
            _ => 0,
        }
    }

    pub fn clear_JKMNPPEOIJP(&mut self) {
        self.DCINAIHIPOC = ::std::option::Option::None;
    }

    pub fn has_JKMNPPEOIJP(&self) -> bool {
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::JKMNPPEOIJP(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_JKMNPPEOIJP(&mut self, v: u32) {
        self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::JKMNPPEOIJP(v))
    }

    // .OEBJBPNNOKO PEFPFCINABN = 1841;

    pub fn PEFPFCINABN(&self) -> &super::OEBJBPNNOKO::OEBJBPNNOKO {
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::PEFPFCINABN(ref v)) => v,
            _ => <super::OEBJBPNNOKO::OEBJBPNNOKO as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_PEFPFCINABN(&mut self) {
        self.DCINAIHIPOC = ::std::option::Option::None;
    }

    pub fn has_PEFPFCINABN(&self) -> bool {
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::PEFPFCINABN(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_PEFPFCINABN(&mut self, v: super::OEBJBPNNOKO::OEBJBPNNOKO) {
        self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::PEFPFCINABN(v))
    }

    // Mutable pointer to the field.
    pub fn mut_PEFPFCINABN(&mut self) -> &mut super::OEBJBPNNOKO::OEBJBPNNOKO {
        if let ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::PEFPFCINABN(_)) = self.DCINAIHIPOC {
        } else {
            self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::PEFPFCINABN(super::OEBJBPNNOKO::OEBJBPNNOKO::new()));
        }
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::PEFPFCINABN(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_PEFPFCINABN(&mut self) -> super::OEBJBPNNOKO::OEBJBPNNOKO {
        if self.has_PEFPFCINABN() {
            match self.DCINAIHIPOC.take() {
                ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::PEFPFCINABN(v)) => v,
                _ => panic!(),
            }
        } else {
            super::OEBJBPNNOKO::OEBJBPNNOKO::new()
        }
    }

    // .MKHIPFHEKCK INPEGNFEPAP = 1396;

    pub fn INPEGNFEPAP(&self) -> &super::MKHIPFHEKCK::MKHIPFHEKCK {
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::INPEGNFEPAP(ref v)) => v,
            _ => <super::MKHIPFHEKCK::MKHIPFHEKCK as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_INPEGNFEPAP(&mut self) {
        self.DCINAIHIPOC = ::std::option::Option::None;
    }

    pub fn has_INPEGNFEPAP(&self) -> bool {
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::INPEGNFEPAP(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_INPEGNFEPAP(&mut self, v: super::MKHIPFHEKCK::MKHIPFHEKCK) {
        self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::INPEGNFEPAP(v))
    }

    // Mutable pointer to the field.
    pub fn mut_INPEGNFEPAP(&mut self) -> &mut super::MKHIPFHEKCK::MKHIPFHEKCK {
        if let ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::INPEGNFEPAP(_)) = self.DCINAIHIPOC {
        } else {
            self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::INPEGNFEPAP(super::MKHIPFHEKCK::MKHIPFHEKCK::new()));
        }
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::INPEGNFEPAP(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_INPEGNFEPAP(&mut self) -> super::MKHIPFHEKCK::MKHIPFHEKCK {
        if self.has_INPEGNFEPAP() {
            match self.DCINAIHIPOC.take() {
                ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::INPEGNFEPAP(v)) => v,
                _ => panic!(),
            }
        } else {
            super::MKHIPFHEKCK::MKHIPFHEKCK::new()
        }
    }

    // uint32 NEAIFLAADFE = 1780;

    pub fn NEAIFLAADFE(&self) -> u32 {
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::NEAIFLAADFE(v)) => v,
            _ => 0,
        }
    }

    pub fn clear_NEAIFLAADFE(&mut self) {
        self.DCINAIHIPOC = ::std::option::Option::None;
    }

    pub fn has_NEAIFLAADFE(&self) -> bool {
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::NEAIFLAADFE(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_NEAIFLAADFE(&mut self, v: u32) {
        self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::NEAIFLAADFE(v))
    }

    // .KHCINCLHIOJ BLEDIOOJPNL = 1686;

    pub fn BLEDIOOJPNL(&self) -> &super::KHCINCLHIOJ::KHCINCLHIOJ {
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::BLEDIOOJPNL(ref v)) => v,
            _ => <super::KHCINCLHIOJ::KHCINCLHIOJ as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_BLEDIOOJPNL(&mut self) {
        self.DCINAIHIPOC = ::std::option::Option::None;
    }

    pub fn has_BLEDIOOJPNL(&self) -> bool {
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::BLEDIOOJPNL(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_BLEDIOOJPNL(&mut self, v: super::KHCINCLHIOJ::KHCINCLHIOJ) {
        self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::BLEDIOOJPNL(v))
    }

    // Mutable pointer to the field.
    pub fn mut_BLEDIOOJPNL(&mut self) -> &mut super::KHCINCLHIOJ::KHCINCLHIOJ {
        if let ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::BLEDIOOJPNL(_)) = self.DCINAIHIPOC {
        } else {
            self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::BLEDIOOJPNL(super::KHCINCLHIOJ::KHCINCLHIOJ::new()));
        }
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::BLEDIOOJPNL(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_BLEDIOOJPNL(&mut self) -> super::KHCINCLHIOJ::KHCINCLHIOJ {
        if self.has_BLEDIOOJPNL() {
            match self.DCINAIHIPOC.take() {
                ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::BLEDIOOJPNL(v)) => v,
                _ => panic!(),
            }
        } else {
            super::KHCINCLHIOJ::KHCINCLHIOJ::new()
        }
    }

    // .FOFNOBHLKGO KANBEFELFFE = 1176;

    pub fn KANBEFELFFE(&self) -> &super::FOFNOBHLKGO::FOFNOBHLKGO {
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::KANBEFELFFE(ref v)) => v,
            _ => <super::FOFNOBHLKGO::FOFNOBHLKGO as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_KANBEFELFFE(&mut self) {
        self.DCINAIHIPOC = ::std::option::Option::None;
    }

    pub fn has_KANBEFELFFE(&self) -> bool {
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::KANBEFELFFE(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_KANBEFELFFE(&mut self, v: super::FOFNOBHLKGO::FOFNOBHLKGO) {
        self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::KANBEFELFFE(v))
    }

    // Mutable pointer to the field.
    pub fn mut_KANBEFELFFE(&mut self) -> &mut super::FOFNOBHLKGO::FOFNOBHLKGO {
        if let ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::KANBEFELFFE(_)) = self.DCINAIHIPOC {
        } else {
            self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::KANBEFELFFE(super::FOFNOBHLKGO::FOFNOBHLKGO::new()));
        }
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::KANBEFELFFE(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_KANBEFELFFE(&mut self) -> super::FOFNOBHLKGO::FOFNOBHLKGO {
        if self.has_KANBEFELFFE() {
            match self.DCINAIHIPOC.take() {
                ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::KANBEFELFFE(v)) => v,
                _ => panic!(),
            }
        } else {
            super::FOFNOBHLKGO::FOFNOBHLKGO::new()
        }
    }

    // .ICHNLLCNBCC IHNNEJKHBHL = 1754;

    pub fn IHNNEJKHBHL(&self) -> &super::ICHNLLCNBCC::ICHNLLCNBCC {
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::IHNNEJKHBHL(ref v)) => v,
            _ => <super::ICHNLLCNBCC::ICHNLLCNBCC as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_IHNNEJKHBHL(&mut self) {
        self.DCINAIHIPOC = ::std::option::Option::None;
    }

    pub fn has_IHNNEJKHBHL(&self) -> bool {
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::IHNNEJKHBHL(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_IHNNEJKHBHL(&mut self, v: super::ICHNLLCNBCC::ICHNLLCNBCC) {
        self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::IHNNEJKHBHL(v))
    }

    // Mutable pointer to the field.
    pub fn mut_IHNNEJKHBHL(&mut self) -> &mut super::ICHNLLCNBCC::ICHNLLCNBCC {
        if let ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::IHNNEJKHBHL(_)) = self.DCINAIHIPOC {
        } else {
            self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::IHNNEJKHBHL(super::ICHNLLCNBCC::ICHNLLCNBCC::new()));
        }
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::IHNNEJKHBHL(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_IHNNEJKHBHL(&mut self) -> super::ICHNLLCNBCC::ICHNLLCNBCC {
        if self.has_IHNNEJKHBHL() {
            match self.DCINAIHIPOC.take() {
                ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::IHNNEJKHBHL(v)) => v,
                _ => panic!(),
            }
        } else {
            super::ICHNLLCNBCC::ICHNLLCNBCC::new()
        }
    }

    // .GFLKDHPBAMJ NGPGKFELCED = 826;

    pub fn NGPGKFELCED(&self) -> &super::GFLKDHPBAMJ::GFLKDHPBAMJ {
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::NGPGKFELCED(ref v)) => v,
            _ => <super::GFLKDHPBAMJ::GFLKDHPBAMJ as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_NGPGKFELCED(&mut self) {
        self.DCINAIHIPOC = ::std::option::Option::None;
    }

    pub fn has_NGPGKFELCED(&self) -> bool {
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::NGPGKFELCED(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_NGPGKFELCED(&mut self, v: super::GFLKDHPBAMJ::GFLKDHPBAMJ) {
        self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::NGPGKFELCED(v))
    }

    // Mutable pointer to the field.
    pub fn mut_NGPGKFELCED(&mut self) -> &mut super::GFLKDHPBAMJ::GFLKDHPBAMJ {
        if let ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::NGPGKFELCED(_)) = self.DCINAIHIPOC {
        } else {
            self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::NGPGKFELCED(super::GFLKDHPBAMJ::GFLKDHPBAMJ::new()));
        }
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::NGPGKFELCED(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_NGPGKFELCED(&mut self) -> super::GFLKDHPBAMJ::GFLKDHPBAMJ {
        if self.has_NGPGKFELCED() {
            match self.DCINAIHIPOC.take() {
                ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::NGPGKFELCED(v)) => v,
                _ => panic!(),
            }
        } else {
            super::GFLKDHPBAMJ::GFLKDHPBAMJ::new()
        }
    }

    // .MKHIPFHEKCK FHJFKLICFBE = 1322;

    pub fn FHJFKLICFBE(&self) -> &super::MKHIPFHEKCK::MKHIPFHEKCK {
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::FHJFKLICFBE(ref v)) => v,
            _ => <super::MKHIPFHEKCK::MKHIPFHEKCK as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_FHJFKLICFBE(&mut self) {
        self.DCINAIHIPOC = ::std::option::Option::None;
    }

    pub fn has_FHJFKLICFBE(&self) -> bool {
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::FHJFKLICFBE(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_FHJFKLICFBE(&mut self, v: super::MKHIPFHEKCK::MKHIPFHEKCK) {
        self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::FHJFKLICFBE(v))
    }

    // Mutable pointer to the field.
    pub fn mut_FHJFKLICFBE(&mut self) -> &mut super::MKHIPFHEKCK::MKHIPFHEKCK {
        if let ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::FHJFKLICFBE(_)) = self.DCINAIHIPOC {
        } else {
            self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::FHJFKLICFBE(super::MKHIPFHEKCK::MKHIPFHEKCK::new()));
        }
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::FHJFKLICFBE(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_FHJFKLICFBE(&mut self) -> super::MKHIPFHEKCK::MKHIPFHEKCK {
        if self.has_FHJFKLICFBE() {
            match self.DCINAIHIPOC.take() {
                ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::FHJFKLICFBE(v)) => v,
                _ => panic!(),
            }
        } else {
            super::MKHIPFHEKCK::MKHIPFHEKCK::new()
        }
    }

    // int64 FIHMHJHGHOG = 380;

    pub fn FIHMHJHGHOG(&self) -> i64 {
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::FIHMHJHGHOG(v)) => v,
            _ => 0,
        }
    }

    pub fn clear_FIHMHJHGHOG(&mut self) {
        self.DCINAIHIPOC = ::std::option::Option::None;
    }

    pub fn has_FIHMHJHGHOG(&self) -> bool {
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::FIHMHJHGHOG(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_FIHMHJHGHOG(&mut self, v: i64) {
        self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::FIHMHJHGHOG(v))
    }

    // .HMDJNPFBOMM AFCCFJOEIOH = 565;

    pub fn AFCCFJOEIOH(&self) -> &super::HMDJNPFBOMM::HMDJNPFBOMM {
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::AFCCFJOEIOH(ref v)) => v,
            _ => <super::HMDJNPFBOMM::HMDJNPFBOMM as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_AFCCFJOEIOH(&mut self) {
        self.DCINAIHIPOC = ::std::option::Option::None;
    }

    pub fn has_AFCCFJOEIOH(&self) -> bool {
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::AFCCFJOEIOH(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_AFCCFJOEIOH(&mut self, v: super::HMDJNPFBOMM::HMDJNPFBOMM) {
        self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::AFCCFJOEIOH(v))
    }

    // Mutable pointer to the field.
    pub fn mut_AFCCFJOEIOH(&mut self) -> &mut super::HMDJNPFBOMM::HMDJNPFBOMM {
        if let ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::AFCCFJOEIOH(_)) = self.DCINAIHIPOC {
        } else {
            self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::AFCCFJOEIOH(super::HMDJNPFBOMM::HMDJNPFBOMM::new()));
        }
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::AFCCFJOEIOH(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_AFCCFJOEIOH(&mut self) -> super::HMDJNPFBOMM::HMDJNPFBOMM {
        if self.has_AFCCFJOEIOH() {
            match self.DCINAIHIPOC.take() {
                ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::AFCCFJOEIOH(v)) => v,
                _ => panic!(),
            }
        } else {
            super::HMDJNPFBOMM::HMDJNPFBOMM::new()
        }
    }

    // uint32 KBPJEKKBBNO = 25;

    pub fn KBPJEKKBBNO(&self) -> u32 {
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::KBPJEKKBBNO(v)) => v,
            _ => 0,
        }
    }

    pub fn clear_KBPJEKKBBNO(&mut self) {
        self.DCINAIHIPOC = ::std::option::Option::None;
    }

    pub fn has_KBPJEKKBBNO(&self) -> bool {
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::KBPJEKKBBNO(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_KBPJEKKBBNO(&mut self, v: u32) {
        self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::KBPJEKKBBNO(v))
    }

    // uint32 PAIBKOMPFOE = 1763;

    pub fn PAIBKOMPFOE(&self) -> u32 {
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::PAIBKOMPFOE(v)) => v,
            _ => 0,
        }
    }

    pub fn clear_PAIBKOMPFOE(&mut self) {
        self.DCINAIHIPOC = ::std::option::Option::None;
    }

    pub fn has_PAIBKOMPFOE(&self) -> bool {
        match self.DCINAIHIPOC {
            ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::PAIBKOMPFOE(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_PAIBKOMPFOE(&mut self, v: u32) {
        self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::PAIBKOMPFOE(v))
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(16);
        let mut oneofs = ::std::vec::Vec::with_capacity(1);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "NCFHGIBCEBG",
            |m: &SocialPlayGameplayOperationScNotify| { &m.NCFHGIBCEBG },
            |m: &mut SocialPlayGameplayOperationScNotify| { &mut m.NCFHGIBCEBG },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "MFBDMLPDEOE",
            |m: &SocialPlayGameplayOperationScNotify| { &m.MFBDMLPDEOE },
            |m: &mut SocialPlayGameplayOperationScNotify| { &mut m.MFBDMLPDEOE },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::CCKCCKHEFFB::CCKCCKHEFFB>(
            "IACKOCPGIAK",
            SocialPlayGameplayOperationScNotify::has_IACKOCPGIAK,
            SocialPlayGameplayOperationScNotify::IACKOCPGIAK,
            SocialPlayGameplayOperationScNotify::mut_IACKOCPGIAK,
            SocialPlayGameplayOperationScNotify::set_IACKOCPGIAK,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_copy_has_get_set_simpler_accessors::<_, _>(
            "JKMNPPEOIJP",
            SocialPlayGameplayOperationScNotify::has_JKMNPPEOIJP,
            SocialPlayGameplayOperationScNotify::JKMNPPEOIJP,
            SocialPlayGameplayOperationScNotify::set_JKMNPPEOIJP,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::OEBJBPNNOKO::OEBJBPNNOKO>(
            "PEFPFCINABN",
            SocialPlayGameplayOperationScNotify::has_PEFPFCINABN,
            SocialPlayGameplayOperationScNotify::PEFPFCINABN,
            SocialPlayGameplayOperationScNotify::mut_PEFPFCINABN,
            SocialPlayGameplayOperationScNotify::set_PEFPFCINABN,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::MKHIPFHEKCK::MKHIPFHEKCK>(
            "INPEGNFEPAP",
            SocialPlayGameplayOperationScNotify::has_INPEGNFEPAP,
            SocialPlayGameplayOperationScNotify::INPEGNFEPAP,
            SocialPlayGameplayOperationScNotify::mut_INPEGNFEPAP,
            SocialPlayGameplayOperationScNotify::set_INPEGNFEPAP,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_copy_has_get_set_simpler_accessors::<_, _>(
            "NEAIFLAADFE",
            SocialPlayGameplayOperationScNotify::has_NEAIFLAADFE,
            SocialPlayGameplayOperationScNotify::NEAIFLAADFE,
            SocialPlayGameplayOperationScNotify::set_NEAIFLAADFE,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::KHCINCLHIOJ::KHCINCLHIOJ>(
            "BLEDIOOJPNL",
            SocialPlayGameplayOperationScNotify::has_BLEDIOOJPNL,
            SocialPlayGameplayOperationScNotify::BLEDIOOJPNL,
            SocialPlayGameplayOperationScNotify::mut_BLEDIOOJPNL,
            SocialPlayGameplayOperationScNotify::set_BLEDIOOJPNL,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::FOFNOBHLKGO::FOFNOBHLKGO>(
            "KANBEFELFFE",
            SocialPlayGameplayOperationScNotify::has_KANBEFELFFE,
            SocialPlayGameplayOperationScNotify::KANBEFELFFE,
            SocialPlayGameplayOperationScNotify::mut_KANBEFELFFE,
            SocialPlayGameplayOperationScNotify::set_KANBEFELFFE,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::ICHNLLCNBCC::ICHNLLCNBCC>(
            "IHNNEJKHBHL",
            SocialPlayGameplayOperationScNotify::has_IHNNEJKHBHL,
            SocialPlayGameplayOperationScNotify::IHNNEJKHBHL,
            SocialPlayGameplayOperationScNotify::mut_IHNNEJKHBHL,
            SocialPlayGameplayOperationScNotify::set_IHNNEJKHBHL,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::GFLKDHPBAMJ::GFLKDHPBAMJ>(
            "NGPGKFELCED",
            SocialPlayGameplayOperationScNotify::has_NGPGKFELCED,
            SocialPlayGameplayOperationScNotify::NGPGKFELCED,
            SocialPlayGameplayOperationScNotify::mut_NGPGKFELCED,
            SocialPlayGameplayOperationScNotify::set_NGPGKFELCED,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::MKHIPFHEKCK::MKHIPFHEKCK>(
            "FHJFKLICFBE",
            SocialPlayGameplayOperationScNotify::has_FHJFKLICFBE,
            SocialPlayGameplayOperationScNotify::FHJFKLICFBE,
            SocialPlayGameplayOperationScNotify::mut_FHJFKLICFBE,
            SocialPlayGameplayOperationScNotify::set_FHJFKLICFBE,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_copy_has_get_set_simpler_accessors::<_, _>(
            "FIHMHJHGHOG",
            SocialPlayGameplayOperationScNotify::has_FIHMHJHGHOG,
            SocialPlayGameplayOperationScNotify::FIHMHJHGHOG,
            SocialPlayGameplayOperationScNotify::set_FIHMHJHGHOG,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::HMDJNPFBOMM::HMDJNPFBOMM>(
            "AFCCFJOEIOH",
            SocialPlayGameplayOperationScNotify::has_AFCCFJOEIOH,
            SocialPlayGameplayOperationScNotify::AFCCFJOEIOH,
            SocialPlayGameplayOperationScNotify::mut_AFCCFJOEIOH,
            SocialPlayGameplayOperationScNotify::set_AFCCFJOEIOH,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_copy_has_get_set_simpler_accessors::<_, _>(
            "KBPJEKKBBNO",
            SocialPlayGameplayOperationScNotify::has_KBPJEKKBBNO,
            SocialPlayGameplayOperationScNotify::KBPJEKKBBNO,
            SocialPlayGameplayOperationScNotify::set_KBPJEKKBBNO,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_copy_has_get_set_simpler_accessors::<_, _>(
            "PAIBKOMPFOE",
            SocialPlayGameplayOperationScNotify::has_PAIBKOMPFOE,
            SocialPlayGameplayOperationScNotify::PAIBKOMPFOE,
            SocialPlayGameplayOperationScNotify::set_PAIBKOMPFOE,
        ));
        oneofs.push(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::generated_oneof_descriptor_data());
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SocialPlayGameplayOperationScNotify>(
            "SocialPlayGameplayOperationScNotify",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SocialPlayGameplayOperationScNotify {
    const NAME: &'static str = "SocialPlayGameplayOperationScNotify";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                40 => {
                    self.NCFHGIBCEBG = is.read_uint32()?;
                },
                48 => {
                    self.MFBDMLPDEOE = is.read_uint32()?;
                },
                5474 => {
                    self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::IACKOCPGIAK(is.read_message()?));
                },
                2352 => {
                    self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::JKMNPPEOIJP(is.read_uint32()?));
                },
                14730 => {
                    self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::PEFPFCINABN(is.read_message()?));
                },
                11170 => {
                    self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::INPEGNFEPAP(is.read_message()?));
                },
                14240 => {
                    self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::NEAIFLAADFE(is.read_uint32()?));
                },
                13490 => {
                    self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::BLEDIOOJPNL(is.read_message()?));
                },
                9410 => {
                    self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::KANBEFELFFE(is.read_message()?));
                },
                14034 => {
                    self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::IHNNEJKHBHL(is.read_message()?));
                },
                6610 => {
                    self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::NGPGKFELCED(is.read_message()?));
                },
                10578 => {
                    self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::FHJFKLICFBE(is.read_message()?));
                },
                3040 => {
                    self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::FIHMHJHGHOG(is.read_int64()?));
                },
                4522 => {
                    self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::AFCCFJOEIOH(is.read_message()?));
                },
                200 => {
                    self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::KBPJEKKBBNO(is.read_uint32()?));
                },
                14104 => {
                    self.DCINAIHIPOC = ::std::option::Option::Some(social_play_gameplay_operation_sc_notify::DCINAIHIPOC::PAIBKOMPFOE(is.read_uint32()?));
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.NCFHGIBCEBG != 0 {
            my_size += ::protobuf::rt::uint32_size(5, self.NCFHGIBCEBG);
        }
        if self.MFBDMLPDEOE != 0 {
            my_size += ::protobuf::rt::uint32_size(6, self.MFBDMLPDEOE);
        }
        if let ::std::option::Option::Some(ref v) = self.DCINAIHIPOC {
            match v {
                &social_play_gameplay_operation_sc_notify::DCINAIHIPOC::IACKOCPGIAK(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &social_play_gameplay_operation_sc_notify::DCINAIHIPOC::JKMNPPEOIJP(v) => {
                    my_size += ::protobuf::rt::uint32_size(294, v);
                },
                &social_play_gameplay_operation_sc_notify::DCINAIHIPOC::PEFPFCINABN(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &social_play_gameplay_operation_sc_notify::DCINAIHIPOC::INPEGNFEPAP(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &social_play_gameplay_operation_sc_notify::DCINAIHIPOC::NEAIFLAADFE(v) => {
                    my_size += ::protobuf::rt::uint32_size(1780, v);
                },
                &social_play_gameplay_operation_sc_notify::DCINAIHIPOC::BLEDIOOJPNL(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &social_play_gameplay_operation_sc_notify::DCINAIHIPOC::KANBEFELFFE(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &social_play_gameplay_operation_sc_notify::DCINAIHIPOC::IHNNEJKHBHL(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &social_play_gameplay_operation_sc_notify::DCINAIHIPOC::NGPGKFELCED(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &social_play_gameplay_operation_sc_notify::DCINAIHIPOC::FHJFKLICFBE(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &social_play_gameplay_operation_sc_notify::DCINAIHIPOC::FIHMHJHGHOG(v) => {
                    my_size += ::protobuf::rt::int64_size(380, v);
                },
                &social_play_gameplay_operation_sc_notify::DCINAIHIPOC::AFCCFJOEIOH(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &social_play_gameplay_operation_sc_notify::DCINAIHIPOC::KBPJEKKBBNO(v) => {
                    my_size += ::protobuf::rt::uint32_size(25, v);
                },
                &social_play_gameplay_operation_sc_notify::DCINAIHIPOC::PAIBKOMPFOE(v) => {
                    my_size += ::protobuf::rt::uint32_size(1763, v);
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.NCFHGIBCEBG != 0 {
            os.write_uint32(5, self.NCFHGIBCEBG)?;
        }
        if self.MFBDMLPDEOE != 0 {
            os.write_uint32(6, self.MFBDMLPDEOE)?;
        }
        if let ::std::option::Option::Some(ref v) = self.DCINAIHIPOC {
            match v {
                &social_play_gameplay_operation_sc_notify::DCINAIHIPOC::IACKOCPGIAK(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(684, v, os)?;
                },
                &social_play_gameplay_operation_sc_notify::DCINAIHIPOC::JKMNPPEOIJP(v) => {
                    os.write_uint32(294, v)?;
                },
                &social_play_gameplay_operation_sc_notify::DCINAIHIPOC::PEFPFCINABN(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(1841, v, os)?;
                },
                &social_play_gameplay_operation_sc_notify::DCINAIHIPOC::INPEGNFEPAP(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(1396, v, os)?;
                },
                &social_play_gameplay_operation_sc_notify::DCINAIHIPOC::NEAIFLAADFE(v) => {
                    os.write_uint32(1780, v)?;
                },
                &social_play_gameplay_operation_sc_notify::DCINAIHIPOC::BLEDIOOJPNL(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(1686, v, os)?;
                },
                &social_play_gameplay_operation_sc_notify::DCINAIHIPOC::KANBEFELFFE(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(1176, v, os)?;
                },
                &social_play_gameplay_operation_sc_notify::DCINAIHIPOC::IHNNEJKHBHL(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(1754, v, os)?;
                },
                &social_play_gameplay_operation_sc_notify::DCINAIHIPOC::NGPGKFELCED(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(826, v, os)?;
                },
                &social_play_gameplay_operation_sc_notify::DCINAIHIPOC::FHJFKLICFBE(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(1322, v, os)?;
                },
                &social_play_gameplay_operation_sc_notify::DCINAIHIPOC::FIHMHJHGHOG(v) => {
                    os.write_int64(380, v)?;
                },
                &social_play_gameplay_operation_sc_notify::DCINAIHIPOC::AFCCFJOEIOH(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(565, v, os)?;
                },
                &social_play_gameplay_operation_sc_notify::DCINAIHIPOC::KBPJEKKBBNO(v) => {
                    os.write_uint32(25, v)?;
                },
                &social_play_gameplay_operation_sc_notify::DCINAIHIPOC::PAIBKOMPFOE(v) => {
                    os.write_uint32(1763, v)?;
                },
            };
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SocialPlayGameplayOperationScNotify {
        SocialPlayGameplayOperationScNotify::new()
    }

    fn clear(&mut self) {
        self.NCFHGIBCEBG = 0;
        self.MFBDMLPDEOE = 0;
        self.DCINAIHIPOC = ::std::option::Option::None;
        self.DCINAIHIPOC = ::std::option::Option::None;
        self.DCINAIHIPOC = ::std::option::Option::None;
        self.DCINAIHIPOC = ::std::option::Option::None;
        self.DCINAIHIPOC = ::std::option::Option::None;
        self.DCINAIHIPOC = ::std::option::Option::None;
        self.DCINAIHIPOC = ::std::option::Option::None;
        self.DCINAIHIPOC = ::std::option::Option::None;
        self.DCINAIHIPOC = ::std::option::Option::None;
        self.DCINAIHIPOC = ::std::option::Option::None;
        self.DCINAIHIPOC = ::std::option::Option::None;
        self.DCINAIHIPOC = ::std::option::Option::None;
        self.DCINAIHIPOC = ::std::option::Option::None;
        self.DCINAIHIPOC = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SocialPlayGameplayOperationScNotify {
        static instance: SocialPlayGameplayOperationScNotify = SocialPlayGameplayOperationScNotify {
            NCFHGIBCEBG: 0,
            MFBDMLPDEOE: 0,
            DCINAIHIPOC: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SocialPlayGameplayOperationScNotify {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SocialPlayGameplayOperationScNotify").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SocialPlayGameplayOperationScNotify {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SocialPlayGameplayOperationScNotify {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `SocialPlayGameplayOperationScNotify`
pub mod social_play_gameplay_operation_sc_notify {

    #[derive(Clone,PartialEq,Debug)]
    #[non_exhaustive]
    // @@protoc_insertion_point(oneof:SocialPlayGameplayOperationScNotify.DCINAIHIPOC)
    pub enum DCINAIHIPOC {
        // @@protoc_insertion_point(oneof_field:SocialPlayGameplayOperationScNotify.IACKOCPGIAK)
        IACKOCPGIAK(super::super::CCKCCKHEFFB::CCKCCKHEFFB),
        // @@protoc_insertion_point(oneof_field:SocialPlayGameplayOperationScNotify.JKMNPPEOIJP)
        JKMNPPEOIJP(u32),
        // @@protoc_insertion_point(oneof_field:SocialPlayGameplayOperationScNotify.PEFPFCINABN)
        PEFPFCINABN(super::super::OEBJBPNNOKO::OEBJBPNNOKO),
        // @@protoc_insertion_point(oneof_field:SocialPlayGameplayOperationScNotify.INPEGNFEPAP)
        INPEGNFEPAP(super::super::MKHIPFHEKCK::MKHIPFHEKCK),
        // @@protoc_insertion_point(oneof_field:SocialPlayGameplayOperationScNotify.NEAIFLAADFE)
        NEAIFLAADFE(u32),
        // @@protoc_insertion_point(oneof_field:SocialPlayGameplayOperationScNotify.BLEDIOOJPNL)
        BLEDIOOJPNL(super::super::KHCINCLHIOJ::KHCINCLHIOJ),
        // @@protoc_insertion_point(oneof_field:SocialPlayGameplayOperationScNotify.KANBEFELFFE)
        KANBEFELFFE(super::super::FOFNOBHLKGO::FOFNOBHLKGO),
        // @@protoc_insertion_point(oneof_field:SocialPlayGameplayOperationScNotify.IHNNEJKHBHL)
        IHNNEJKHBHL(super::super::ICHNLLCNBCC::ICHNLLCNBCC),
        // @@protoc_insertion_point(oneof_field:SocialPlayGameplayOperationScNotify.NGPGKFELCED)
        NGPGKFELCED(super::super::GFLKDHPBAMJ::GFLKDHPBAMJ),
        // @@protoc_insertion_point(oneof_field:SocialPlayGameplayOperationScNotify.FHJFKLICFBE)
        FHJFKLICFBE(super::super::MKHIPFHEKCK::MKHIPFHEKCK),
        // @@protoc_insertion_point(oneof_field:SocialPlayGameplayOperationScNotify.FIHMHJHGHOG)
        FIHMHJHGHOG(i64),
        // @@protoc_insertion_point(oneof_field:SocialPlayGameplayOperationScNotify.AFCCFJOEIOH)
        AFCCFJOEIOH(super::super::HMDJNPFBOMM::HMDJNPFBOMM),
        // @@protoc_insertion_point(oneof_field:SocialPlayGameplayOperationScNotify.KBPJEKKBBNO)
        KBPJEKKBBNO(u32),
        // @@protoc_insertion_point(oneof_field:SocialPlayGameplayOperationScNotify.PAIBKOMPFOE)
        PAIBKOMPFOE(u32),
    }

    impl ::protobuf::Oneof for DCINAIHIPOC {
    }

    impl ::protobuf::OneofFull for DCINAIHIPOC {
        fn descriptor() -> ::protobuf::reflect::OneofDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::OneofDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| <super::SocialPlayGameplayOperationScNotify as ::protobuf::MessageFull>::descriptor().oneof_by_name("DCINAIHIPOC").unwrap()).clone()
        }
    }

    impl DCINAIHIPOC {
        pub(in super) fn generated_oneof_descriptor_data() -> ::protobuf::reflect::GeneratedOneofDescriptorData {
            ::protobuf::reflect::GeneratedOneofDescriptorData::new::<DCINAIHIPOC>("DCINAIHIPOC")
        }
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n)SocialPlayGameplayOperationScNotify.proto\x1a\x11CCKCCKHEFFB.proto\
    \x1a\x11FOFNOBHLKGO.proto\x1a\x11GFLKDHPBAMJ.proto\x1a\x11HMDJNPFBOMM.pr\
    oto\x1a\x11ICHNLLCNBCC.proto\x1a\x11KHCINCLHIOJ.proto\x1a\x11MKHIPFHEKCK\
    .proto\x1a\x11OEBJBPNNOKO.proto\"\xfb\x05\n#SocialPlayGameplayOperationS\
    cNotify\x12\x20\n\x0bNCFHGIBCEBG\x18\x05\x20\x01(\rR\x0bNCFHGIBCEBG\x12\
    \x20\n\x0bMFBDMLPDEOE\x18\x06\x20\x01(\rR\x0bMFBDMLPDEOE\x121\n\x0bIACKO\
    CPGIAK\x18\xac\x05\x20\x01(\x0b2\x0c.CCKCCKHEFFBH\0R\x0bIACKOCPGIAK\x12#\
    \n\x0bJKMNPPEOIJP\x18\xa6\x02\x20\x01(\rH\0R\x0bJKMNPPEOIJP\x121\n\x0bPE\
    FPFCINABN\x18\xb1\x0e\x20\x01(\x0b2\x0c.OEBJBPNNOKOH\0R\x0bPEFPFCINABN\
    \x121\n\x0bINPEGNFEPAP\x18\xf4\n\x20\x01(\x0b2\x0c.MKHIPFHEKCKH\0R\x0bIN\
    PEGNFEPAP\x12#\n\x0bNEAIFLAADFE\x18\xf4\r\x20\x01(\rH\0R\x0bNEAIFLAADFE\
    \x121\n\x0bBLEDIOOJPNL\x18\x96\r\x20\x01(\x0b2\x0c.KHCINCLHIOJH\0R\x0bBL\
    EDIOOJPNL\x121\n\x0bKANBEFELFFE\x18\x98\t\x20\x01(\x0b2\x0c.FOFNOBHLKGOH\
    \0R\x0bKANBEFELFFE\x121\n\x0bIHNNEJKHBHL\x18\xda\r\x20\x01(\x0b2\x0c.ICH\
    NLLCNBCCH\0R\x0bIHNNEJKHBHL\x121\n\x0bNGPGKFELCED\x18\xba\x06\x20\x01(\
    \x0b2\x0c.GFLKDHPBAMJH\0R\x0bNGPGKFELCED\x121\n\x0bFHJFKLICFBE\x18\xaa\n\
    \x20\x01(\x0b2\x0c.MKHIPFHEKCKH\0R\x0bFHJFKLICFBE\x12#\n\x0bFIHMHJHGHOG\
    \x18\xfc\x02\x20\x01(\x03H\0R\x0bFIHMHJHGHOG\x121\n\x0bAFCCFJOEIOH\x18\
    \xb5\x04\x20\x01(\x0b2\x0c.HMDJNPFBOMMH\0R\x0bAFCCFJOEIOH\x12\"\n\x0bKBP\
    JEKKBBNO\x18\x19\x20\x01(\rH\0R\x0bKBPJEKKBBNO\x12#\n\x0bPAIBKOMPFOE\x18\
    \xe3\r\x20\x01(\rH\0R\x0bPAIBKOMPFOEB\r\n\x0bDCINAIHIPOCb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(8);
            deps.push(super::CCKCCKHEFFB::file_descriptor().clone());
            deps.push(super::FOFNOBHLKGO::file_descriptor().clone());
            deps.push(super::GFLKDHPBAMJ::file_descriptor().clone());
            deps.push(super::HMDJNPFBOMM::file_descriptor().clone());
            deps.push(super::ICHNLLCNBCC::file_descriptor().clone());
            deps.push(super::KHCINCLHIOJ::file_descriptor().clone());
            deps.push(super::MKHIPFHEKCK::file_descriptor().clone());
            deps.push(super::OEBJBPNNOKO::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(SocialPlayGameplayOperationScNotify::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
