// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `TrainCakeCatchOpenBoxScRsp.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:TrainCakeCatchOpenBoxScRsp)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct TrainCakeCatchOpenBoxScRsp {
    // message fields
    // @@protoc_insertion_point(field:TrainCakeCatchOpenBoxScRsp.AFEJACMLOLH)
    pub AFEJACMLOLH: ::std::vec::Vec<super::NPLEDHFMFDM::NPLEDHFMFDM>,
    // @@protoc_insertion_point(field:TrainCakeCatchOpenBoxScRsp.retcode)
    pub retcode: u32,
    // @@protoc_insertion_point(field:TrainCakeCatchOpenBoxScRsp.DHLGCEGONIB)
    pub DHLGCEGONIB: i64,
    // special fields
    // @@protoc_insertion_point(special_field:TrainCakeCatchOpenBoxScRsp.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a TrainCakeCatchOpenBoxScRsp {
    fn default() -> &'a TrainCakeCatchOpenBoxScRsp {
        <TrainCakeCatchOpenBoxScRsp as ::protobuf::Message>::default_instance()
    }
}

impl TrainCakeCatchOpenBoxScRsp {
    pub fn new() -> TrainCakeCatchOpenBoxScRsp {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "AFEJACMLOLH",
            |m: &TrainCakeCatchOpenBoxScRsp| { &m.AFEJACMLOLH },
            |m: &mut TrainCakeCatchOpenBoxScRsp| { &mut m.AFEJACMLOLH },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "retcode",
            |m: &TrainCakeCatchOpenBoxScRsp| { &m.retcode },
            |m: &mut TrainCakeCatchOpenBoxScRsp| { &mut m.retcode },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "DHLGCEGONIB",
            |m: &TrainCakeCatchOpenBoxScRsp| { &m.DHLGCEGONIB },
            |m: &mut TrainCakeCatchOpenBoxScRsp| { &mut m.DHLGCEGONIB },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<TrainCakeCatchOpenBoxScRsp>(
            "TrainCakeCatchOpenBoxScRsp",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for TrainCakeCatchOpenBoxScRsp {
    const NAME: &'static str = "TrainCakeCatchOpenBoxScRsp";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                50 => {
                    self.AFEJACMLOLH.push(is.read_message()?);
                },
                120 => {
                    self.retcode = is.read_uint32()?;
                },
                96 => {
                    self.DHLGCEGONIB = is.read_int64()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.AFEJACMLOLH {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if self.retcode != 0 {
            my_size += ::protobuf::rt::uint32_size(15, self.retcode);
        }
        if self.DHLGCEGONIB != 0 {
            my_size += ::protobuf::rt::int64_size(12, self.DHLGCEGONIB);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.AFEJACMLOLH {
            ::protobuf::rt::write_message_field_with_cached_size(6, v, os)?;
        };
        if self.retcode != 0 {
            os.write_uint32(15, self.retcode)?;
        }
        if self.DHLGCEGONIB != 0 {
            os.write_int64(12, self.DHLGCEGONIB)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> TrainCakeCatchOpenBoxScRsp {
        TrainCakeCatchOpenBoxScRsp::new()
    }

    fn clear(&mut self) {
        self.AFEJACMLOLH.clear();
        self.retcode = 0;
        self.DHLGCEGONIB = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static TrainCakeCatchOpenBoxScRsp {
        static instance: TrainCakeCatchOpenBoxScRsp = TrainCakeCatchOpenBoxScRsp {
            AFEJACMLOLH: ::std::vec::Vec::new(),
            retcode: 0,
            DHLGCEGONIB: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for TrainCakeCatchOpenBoxScRsp {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("TrainCakeCatchOpenBoxScRsp").unwrap()).clone()
    }
}

impl ::std::fmt::Display for TrainCakeCatchOpenBoxScRsp {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TrainCakeCatchOpenBoxScRsp {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x20TrainCakeCatchOpenBoxScRsp.proto\x1a\x11NPLEDHFMFDM.proto\"\x88\
    \x01\n\x1aTrainCakeCatchOpenBoxScRsp\x12.\n\x0bAFEJACMLOLH\x18\x06\x20\
    \x03(\x0b2\x0c.NPLEDHFMFDMR\x0bAFEJACMLOLH\x12\x18\n\x07retcode\x18\x0f\
    \x20\x01(\rR\x07retcode\x12\x20\n\x0bDHLGCEGONIB\x18\x0c\x20\x01(\x03R\
    \x0bDHLGCEGONIBb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::NPLEDHFMFDM::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(TrainCakeCatchOpenBoxScRsp::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
